### ISSUE TITLE
Funding marker clustering

### ISSUE THREAD

**Issue by nayanuka** [mapsplugin/cordova-plugin-googlemaps#1006]
First of all, a massive thanks to all the people who have contributed to this plugin. Its great work! 

This issue is really about the marker clustering feature: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/699

I am creating a new issue because only collaborators can comment on the above issue so apologies if this is doubling up.

The company I work for is happy to fulfill the remainder of the bounty up to $1,000 so that this feature can be released publicly. However, before doing that, can we get some assurances that it is indeed going to be released publicly without delay (so we don't have to wait months to access the feature)?

Also, whats the best way to donate? Is there a English donate link and how much is left on the bounty?

Thanks

**Comment by wf9a5m75** [comment]
I'm still working on the multiple maps and improve the performance overall.
This cause the pulgin files are changed significantly.
After that , I will create the cluster feature.

**Comment by nayanuka** [comment]
Thanks Masashi -- can you please let us know when you are planning to work on the cluster feature? Is it more like in within the next one month or longer like 3 to 6 months?

**Comment by wf9a5m75** [comment]
No ETA. Sorry

**Comment by Mojo90** [comment]
I am also highly interested in this featured as already often mentioned. Can I support here somehow?

**Comment by astrolope** [comment]
+1 on willing to help to see this brought to fruition. I've been working on writing my own and instead of reworking the wheel I'd love to help spur this to finish.

**Comment by samazary** [comment]
+1 for clustering support, many waiting for this excellent feature!

**Comment by anavarro9731** [comment]
+1 If we could get a commitment on delivery dates, we would might donate for that.

**Comment by vash15** [comment]
+1

**Comment by lnicolet** [comment]
+1 for clustering support

**Comment by wf9a5m75** [comment]
Buy me a beer

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=SelfieW%2eme&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted)

**Comment by wasa4587** [comment]
+1

**Comment by wf9a5m75** [comment]
If someone donate at least additional $800USD to me, I will create the marker cluster in one month. I already recieved $200USD donation from two people.
The cluster feature will be implemented in the plugin v2-beta, not for the v1.3.9.

**Comment by pke** [comment]
That's not how I thought open source works. What other feature will cost extra next? Just release the branch and let is all finish it. Take any leaflet cluster plugin as a base and exchange the marker funcs.

**Comment by wf9a5m75** [comment]
You don't agree with what I talk, you don't need to donate anything. Just wait. Somebody might implement the feature, or someone donate then I will create.
Or you can create the feature, then send a pull request.
If you don't work anything on this project, you should not say anything.

**Comment by Pushplaybang** [comment]
Clustering as I understand it would not necessarily solve the problem of markers on top of each other would it?

**Comment by wf9a5m75** [comment]
Talking about the marker cluster for this plugin, please recognize two things:

----

1. I created the marker cluster at once, but I could not complete to implement it.
Because my real job was terribly busy, and I was so stressful.
(After that, I left this project at once)

This is a demo video two years ago (not for current version)
https://www.youtube.com/watch?v=XlPNhmpwag8

2. Hirbod with some contributers created another marker cluster,
but they did not complete for some reasons.
But you can try the cluster branch (but code is old, it means slow)

------

I developed the version 2 of this plugin. It is faster than v1.
I have been focus on releasing the version 2 currently.
So if you donate some amount, I don't develop it at this time.
(But donating some amount raises up the priority of feature implementations)

I'm planing to develop the cluster feature in next year for v2.

As I announced at the official community, the current version 1.4.0 is the last version of v1.x
No more development for v1.x

----

Donation will be used for buying new software or test devices.
Or paying thanksful for pull requesting that significantly improve this plugin.

**Comment by sam2x** [comment]
Hey, I have read multiple threads about clustering integration (like #699 #960 ), some of them highlighting the fact that clustering is "almost finished", but i can't understand the current situation, nor find any branch/pull request/WIP link. 

Could you please clarify the situation ? Is that going to be integrated soon, or are you facing some problems ? 
I have the feeling that everyone integrated his own clustering feature.

Thanks.

**Comment by wf9a5m75** [comment]
Update: the donation amount is leached to $1,000.
I will work on this feature for the multiple_maps branch (v2.0 beta).
After that, v2.0-beta will become to v2.0(beta2) or master.

I'm planing to release the marker-clustering feature by the end of July (Pacific Time).

Next update is planed around May 15.

**Comment by wf9a5m75** [comment]
Hi All,

This is the first demo of marker clustering (sample location data: 16077 position)

![cluster_demo1](https://cloud.githubusercontent.com/assets/167831/26082455/eeaccbba-3984-11e7-9529-7895f43507b3.gif)

I have been implementing the geohashing (using geomodel), which is grid based clustering algorithm.
In order to understand easily, I display blue polygon to show the bounds, that is covered by one grid cell.

For example, the number "2851" of the red marker means there are 2851 positions in the blue grid cell.
![sample](https://cloud.githubusercontent.com/assets/167831/26082630/c79444b2-3985-11e7-9b22-14eb371d0358.png)

Currently, the code is implemented only JavaScript.
I will implement the code using native side also. It would be more faster.

--------

Unfortunately the code is not ready to use yet, even the project donors (who are the people have the right to use the feature in advance).
But don't worry. The development in on the way.

**Comment by stalniy** [comment]
Correct me if I'm wrong but as far as I know Google Sdk supports marker clustering. So, the only thing which needs to be done is a bridge between native code and js.

**Comment by wf9a5m75** [comment]
@stalniy You are incorrect.
Google Maps Android API v2 and Google Maps SDK for iOS do not have marker clustering feature.
You are talking about additional library that is not created by Google. And the code of both Android and iOS are different implemented.

These libraries are not matched with this plugin, because this plugin has two side JS and native side. The difficult thing is JS and native side run on different threads.
If you feel it's easy, you can fork this plugin repository and try it.

In the past, @Hirbod tried to implement these libraries to this plugin (for v1.3.3?), but never completed for some reasons.

**Comment by stalniy** [comment]
I see. Thanks for explanation!

**Comment by wf9a5m75** [comment]
Hi all,

Sorry for waiting long time (especially this project donors).
This is the second demo  (sample location data: 16077 position).

![demo](https://user-images.githubusercontent.com/167831/27758402-b05daa70-5dc7-11e7-85b0-35b2912c3603.gif)

I have been working on native code and the stress testing.
I think this Android version becomes stable finally.
So I will continue to the iOS version.

The beta version will be available for the project donors soon.
Please wait for a while.

**Comment by wf9a5m75** [comment]
Hi All,

This is the third demo of marker clustering (sample location data: 6000+ position)

![demo3](https://user-images.githubusercontent.com/167831/28303766-8851617c-6b49-11e7-9679-f31673e2b9ec.gif)

The basic behavior is implemented, but I still need to improve performance more.

But you don't feel any stress if the target locations less than 1,000. (I hope so)

-----

I will invite donors as the first tester to the private repository tomorrow.

**Comment by wf9a5m75** [comment]
If you are interested in to use this marker cluster, please let me know by e-mail.

**Comment by wf9a5m75** [comment]
This is the fourth demo. 
The algorithm uses the Geocell grid + distance base.

![demo](https://user-images.githubusercontent.com/167831/28751890-d4492506-74c7-11e7-8312-0bdd802886d6.gif)

**Comment by wf9a5m75** [comment]
Hi all, this is the fifth demo.
The clustering speed has been improved significantly.

![demo](https://user-images.githubusercontent.com/167831/29001274-09f7b5d8-7a3a-11e7-9ed0-6588d7387280.gif)

**Comment by Hirbod** [comment]
looks very promising!

**Comment by VesperDev** [comment]
+1

**Comment by NgYueHong** [comment]
Looking good. When will this feature available?

**Comment by wf9a5m75** [comment]
Hi everyone, thank you for waiting and helping the marker cluster feature.
The marker cluster is finally general available.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/MarkerCluster

**Comment by wf9a5m75** [comment]
If you find any issues of the marker cluster, please make another issue thread. This thread is kind of long. I close this thread at once.
