### ISSUE TITLE
No known instance method for selector 'initWithWebView:' in GoogleMaps.m

### ISSUE THREAD

**Issue by Vishaliphone** [mapsplugin/cordova-plugin-googlemaps#1015]
Hi,
I had strange issue with this plugin.
I already installed this plugIn in fresh Project and it's working fine.

While i switched to the my existing project i got below 3 errors :
====================================

```
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:24:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
MyProject/platforms/ios/Uponor&more/Plugins/plugin.google.maps/GoogleMaps.m:28:45: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginScrollView.debugView.webView = self.webView;
                                            ^ ~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:34:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:167:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
        self.mapCtrl.webView = self.webView;
                             ^ ~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector 'initWithWebView:'
        Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
                                                          ^~~~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:186:38: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
            self.pluginLayer.webView = self.webView;
                                     ^ ~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector 'initWithWebView:'
                pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
                                                                   ^~~~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
    [self.webView stringByEvaluatingJavaScriptFromString:jsString];
     ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MyProject/Plugins/plugin.google.maps/GoogleMaps.m:404:34: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
        self.pluginLayer.webView = self.webView;
                                 ^ ~~~~~~~~~~~~
6 warnings and 3 errors generated.
```
====================================

If you are interested in ilist of installed plugins then below is complete list of installed plugins in my project :
By give "cordova plugin list" command i got below list of installed plugins :

```
com.googlemaps.ios 1.13.0 "Google Map iOS SDK for Cordova"
cordova-plugin-battery-status 1.1.2 "Battery"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-device-motion 1.2.1 "Device Motion"
cordova-plugin-device-orientation 1.0.3 "Device Orientation"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-listpicker 2.2.2 "ListPicker"
cordova-plugin-media 2.2.0 "Media"
cordova-plugin-media-capture 1.2.0 "Capture"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.1 "Vibration"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-barcodescanner 5.0.0 "BarcodeScanner"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"
```

Help me regarding this

**Comment by gurpritksaini** [comment]
We are also looking into the same type of plugin and always getting the similar issue. I think we have to check for the updated version of plugin and that will solve the issue. But till now after trying that so many times we are yet to get a proper solution on this.

**Comment by wf9a5m75** [comment]
Do you use the master branch version or the npm version?

**Comment by Vishaliphone** [comment]
I did use following command in my **Terminal** to install this plugin :

--> npm (current stable 1.3.9)

cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

**Comment by netomia** [comment]
I got the same errors on a clean cordova app. But this worked:

cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

**Comment by Vishaliphone** [comment]
Let me try & update you.
Thanks!

**Comment by mhfen** [comment]
@wf9a5m75 

Might want to change the README.md to reflect that v. 1.3.9 on npm is not stable.

Is Master considered the stable way to install this plugin now? Is this just temporary or is this true moving forward?

**Comment by mhfen** [comment]
To expand further on the current build errors when using the v.1.3.9 npm package:

xCode Version: 7.3 (7D175)

#### plugin.google.maps/GroundOverlay.m
```
100:47: Property 'request' not found on object of type 'UIView *'
```

#### plugin.google.maps/GoogleMaps.m
```
176:59: No known instance method for selector 'initWithWebView:'
245:68: No known instance method for selector 'initWithWebView:'
321:19: No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
```

It looks like that 1.3.9 build is behind a few breaking changes from Apple... I'm also seeing a lot of deprecation warnings that will soon turn into breaking change errors.

Since the Master branch seems to have addressed many of these, if not all... is there a process you follow for updating your stable npm build once issues have been cleared? Might be time to do that.

**Comment by wf9a5m75** [comment]
During v1.2.6-v1.3.9, I left this project, and I returned back to this project 3 month ago.
I know some codes are out-of-dated, and I find some not good code that is merged or somebody changed.

I have been working on the next version. The code will be changed significantly.
Check out the multiple_maps branch (not stable).
I know you might be frustrated but please wait to extend features.

**Comment by mhfen** [comment]
I'm not frustrated with the code as much as I'm frustrated with the lack of process. Your plugin is used by many developers (1,563 npm downloads in the last month), and those developers have clients who pay lots of money for an app, and those clients have customers who may or may not pay money to use that app. You have a responsibility to define a clear process for distributing stable versions of your code so that developers can have peace-of-mind when using your plugin for production applications. That may look something like this that you could put in the README.md or a DEVELOPER.md:

# Cordova Plugin GoogleMaps Release Cycle

## Milestone Planning
The team will set milestones for stable release versions. Each Milestone will contain Bugs and Issues the team wants to address during that release. The team will work for 2 weeks on each Milestone and address as many issues as possible. At the end of 2 weeks, the addressed issues are packaged into a new stable release, and the issues that weren't addressed fall to the next Milestone release.

## NPM Release
On completion of a Milestone, the team will release the stable version to npm with a new build number.

## Change Log
On release of a new stable version to npm, the team will update a CHANGELOG.md with what has changed, including addressed issues and any breaking changes.


If you have a clearly defined process and stick to it, more people will want to contribute to your project (because its easier to know what is expected) and you won't have to take as much responsibility fixing issues that arise.

Until you do that, at least update the README.md to reflect the latest npm release is not stable.

**Comment by wf9a5m75** [comment]
There are several reasons of why we (@Hirbod and I) don't declare of the Release Cycle.

- Basically we are so busy, and we don't work this as work. Only developing in the limited private times.
My private time is less than 1 hour per day.

- You says `more contribute`, but currently `no, but thank you anyway`.
Since our times are very limited, handling many people, many requests, many pull requests are very frustrated.
(And I lost my mother recently)

At least I don't have a plan to add another contributors to this project *currently* (not forever).
The reason of this is that this project uses JavaScript, Java and objective-c.
These are closely bound together.
There are some people of understand Javascript and either Java or Objective-C, but not both.
Adjusting of many people in limited time is killing me.
(That's why I left during v1.2.6 - v1.3.9)

- Cordova framework also changes many things frequently.
I need to modify the code of this plugin significantly sometimes.

---

Since the next version is still unstable, and even for me, I have been fumbling for better way,
we can not set the release cycle and no ETA at this time.

--- 

Regarding of the npm version, I don't touch about it currently.

And regarding of the master branch, I merge or fix only obvious critical issues.
If you can fix the issues, fork this repository, fix them, and send the pull requests, please.
(This is the way to save of our time).

**Comment by mhfen** [comment]
`Regarding of the npm version, I don't touch about it currently.`
Can you explain what you mean by that?

I realize you are doing this on your own time and I think everyone really appreciates that, but the fact that you do it on your own time does not stop you from creating a predictable process for distribution of your code.

At the very least, if you believe the current Master branch to be stable, can you create a new release on NPM and call that the stable release? That takes maybe 10 minutes.

**Comment by wf9a5m75** [comment]
>Regarding of the npm version, I don't touch about it currently.
Releasing to NPM started by @Hirbod , not me.

**Comment by mhfen** [comment]
Is it your project or does it belong to @Hirbod ? Can the person who is responsible update npm to a stable build? Not asking for a lot here...

**Comment by wf9a5m75** [comment]
This project started by me, @Hirbod joined later. But I left at once.
@Hirbod started providing NPM package while I'm leaving.
After that, I came back to this project.

**Comment by mhfen** [comment]
Ok, cool, so either you or @Hirbod can publish a stable build to npm.

Here is how to do that: https://docs.npmjs.com/getting-started/publishing-npm-packages

Hey @Hirbod - if you haven't given the npm credentials to @wf9a5m75 , can you do that? Thanks.

**Comment by Hirbod** [comment]
@mhfen to clear up things a bit: master IS stable for Cordova iOS prior version 4. (3.9.x)

We've never commited that npm version is working on iOS Cordova 4+

The current master is considered beta, it does not contain all the improvements that Masashi started on. I don't see any reason to push a beta version to npm, while its perfectly fine to pick up the master from GitHub.

Also the plugin name changed and we do not have any checks included to detect this and give a warning (preventing double installation of the plugin)

So there is some much work to do, before pushing this up. Just please grab the master. Masashi and I have very limited time currently (I have two sick parents) and struggling with providing time on open source projects. 

We'll be back soon on this, but please be patient.

**Comment by chadwhitaker** [comment]
Thanks for all your hard work @Hirbod and @wf9a5m75! While the plugin is currently a little unstable, it's a blessing to work with over Google Maps JS. :)

**Comment by wf9a5m75** [comment]
Since the v2-beta version is available, the version 1.x will be shutdown in near the future (not today, or tomorrow, but at least in couple of months).

Please retry this with the v2-beta version.
https://github.com/mapsplugin/v2.0-demo/

**Comment by pke** [comment]
@Hirbod 
>  I don't see any reason to push a beta version to npm, while its perfectly fine to pick up the master from GitHub.

Well, one reason is cleary: faster fetch from npm compared to a whole git clone. Especially in CI env this makes a huge difference.

npm is a system to quickly grab *any* version from the release train. Even pre-release versions.
Installing the code via git clone is 10 times slower than fetching a compact bundle from npm. If that is not reason enough? I am sure a lot of people are willing to help you guys out here. So why not give others npm push access rights?
