### ISSUE TITLE
trigger click event on a marker

### ISSUE THREAD

**Issue by arielgelbard** [mapsplugin/cordova-plugin-googlemaps#1067]
I can't seem to trigger an event on a marker...in particular the 'markerClick' event. Anyway to do this like the javascript API?

[Stackoverflow trigger event](http://stackoverflow.com/questions/6794405/trigger-google-maps-marker-click)

**Comment by wf9a5m75** [comment]
```js
marker.trigger(plugin.google.maps.event.MARKER_CLICK);
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/BaseClass#trigger

**Comment by guillerial** [comment]
Hello!

How can I do if I have only an array with "MarkerOptions" and a MarkerCluster?
I have not access to "Marker" objects, because I initialise the MarkerCluster with that array.

But i want to trigger the click event on one of the markers that i can see on the viewport. 
(So there must be a Marker object)
Is there any way to get the "Marker" objects that are shown on the viewport?
So I can then trigger the MARKER_CLICK event.

(I am using Ionic Framework 3)

Thanks in advance :)

**Comment by cxminer** [comment]
> w

I'd also like to know how to trigger a click on a marker made with `map.addMarkerCluster()`.

**Comment by cxminer** [comment]
@guillerial Figured it out. Markers are created in order they are provided. They are assigned an id that looks like `marker_0` - 0 being the index of the first marker you provde in array. So to trigger a click event. First get the marker with `const marker = markerClusterer.getMarkerById('marker_0');` then instead of triggering a `MARKER_CLICK` on the marker, trigger it on the clusterer, like so `markerClusterer.trigger(window.plugin.google.maps.event.MARKER_CLICK, latLng, marker);`. And that should do it. In my case the info window for that marker still didn't open but that was because the event was too fast. I simply did `window.setTimeout` for that `MARKER_CLICK` event and info window showed up.

Good luck.

**Comment by JZubero** [comment]
@cxminer Are you also using Ionic? It seems that the MarkerClusterer does not provide the `getMarkerById` method. Although the method seems to be implemented looking at the (VanillaJS) source files there are no TS typings for it. Hence we don't see any possibility to get the marker from the cluster.

**Comment by cxminer** [comment]
@JZubero I found `getMarkerById` by dumping the `MarkerClusterer` object to `console` and analyzing its properties - **it is not** part of the documentation. but **it is there** and **can be used**.

Note that `@ionic-native/google-maps` does **NOT** expose `getMarkerById`. You can only find it by creating the `MarkerClusterer` [directly](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/MarkerCluster/README.md).

**Comment by guillerial** [comment]
@wf9a5m75 would be possible to add `getMarkerById` method to the `@ionic-native/google-maps` plugin to solve this?

**Comment by wf9a5m75** [comment]
nop. It's an internal function.

**Comment by guillerial** [comment]
@wf9a5m75 So it's not possible to trigger a click on a marker made with map.addMarkerCluster() on Ionic?

**Comment by cxminer** [comment]
@guillerial Alright, I figured out how to do it in ionic-native wrapper. Beware that since this is not part of the official documentation the code might change at some point and stop working.

**Here is my approach:**

1. Generate an array of `MarkerOption`s.
```
 private _createMarkers(map: GoogleMap): Observable<GoogleMap> {
    return new Observable<GoogleMap>((subscriber: Subscriber<GoogleMap>) => {
      try {
        this._markers = this._dbService.parkingLots
          .filter(parking => parking.latitude && parking.longitude)
          .map(parking => this._parkingLotFactory.provide(parking))
          .map((parking, index) => {
            parking.objectIndex = index; // SAVE THE INDEX INSIDE THE OBJECT
            const icon = parking.payable
              ? 'assets/img/p1.png'
              : 'assets/img/p2.png';
            const options: MarkerOptions = {
              position: { lat: parking.latitude, lng: parking.longitude },
              icon: {
                url: icon
              }
            };
            return options;
          });

        subscriber.next(map);
        subscriber.complete();
      } catch (e) {
        subscriber.error(e);
      }
    });
  }
```

2. Create a `MarkerCluster`, pass in those `MarkerOption`s and subscribe to `MARKER_CLICK`.
```
private _createMarkerCluster(map: GoogleMap): Observable<GoogleMap> {
  return new Observable<GoogleMap>((subscriber: Subscriber<GoogleMap>) => {
    try {
      const icons: MarkerClusterIcon[] = [
        {
          min: 5,
          max: 50,
          size: { width: 52, height: 52 },
          anchor: { x: 26, y: 26 },
          url: './assets/img/m1.png'
        },
        {
          min: 50,
          max: 100,
          size: { width: 66, height: 66 },
          anchor: { x: 33, y: 33 },
          url: './assets/img/m3.png'
        },
        {
          min: 100,
          size: { width: 90, height: 90 },
          anchor: { x: 45, y: 45 },
          url: './assets/img/m5.png'
        }
      ];

      const options: MarkerClusterOptions = {
        markers: this._markers,
        icons: icons,
        boundsDraw: false
      };

      map.addMarkerCluster(options).then(markerCluster => {
        this._markerCluster = markerCluster;

        markerCluster.on(GoogleMapsEvent.MARKER_CLICK).subscribe(params => {
          this._destroyInfoWindow();

          const marker = params[1];
          const objectIndex = parseInt(
            marker
              .getId()
              .split('-')[1]
              .split('_')[1],
            10
          ); // marker ID also contains cluster ID
            // it looks something like this: markercluster_811374873427-marker_5
            // so split by -, then by _ and take the last item, which is 5 😄 

          const parking = this._dbService.parkingLots
            .map(x => this._parkingLotFactory.provide(x))
            .find(x => x.objectIndex === objectIndex);

          if (parking) {
            this._infoWindow = new HtmlInfoWindow();
            this._infoWindow.setContent(
              parking.getInfoWindowContent(this._platform)
            );
            this._infoWindow.open(marker);
          }
        });

        subscriber.next(map);
        subscriber.complete();
      });
    } catch (e) {
      subscriber.error(e);
    }
  });
}
```

3. Figure out where you want to navigate to, find the `Marker` and trigger a `MARKER_CLICK` event.
```
navigateToMarker(parkingToShow: ParkingLotExtended): void {
  this._destroyInfoWindow();

  const latLng = {
    lat: parkingToShow.latitude,
    lng: parkingToShow.longitude
  };

  this._map
    .animateCamera({
      target: latLng,
      zoom: 19,
      duration: 1000
    })
    .then(() => {
      const marker = (this
        ._markerCluster as any)._objectInstance.getMarkerById(
        'marker_' + parkingToShow.objectIndex
      );

      if (marker) {
        window.setTimeout(() => { // for me this was necessary
          this._markerCluster.trigger(
            GoogleMapsEvent.MARKER_CLICK,
            latLng,
            marker
          );
        }, 500);
      }
    });
}
```

**Comment by guillerial** [comment]
@cxminer Wow, thank you for the approach!

 It would be great if there was an official way to do it.

**Comment by cxminer** [comment]
@guillerial True. I don't quite understand why @wf9a5m75 is saying this is an internal function. It's not. I don't see an underscore in front of it... 🤣

**Comment by wf9a5m75** [comment]
That function is intended for internal use. Not for generic use, because marker is not always generated.

**Comment by vthorsell** [comment]
> I will provide alternative way.

Is there another way to trigger the click event on a marker?
