### ISSUE TITLE
native scrolling delay

### ISSUE THREAD

**Issue by Bloggerschmidt** [mapsplugin/cordova-plugin-googlemaps#1075]
Hello and thx for the great plugin. Unfortunately happens a little performance issue: If I scroll a page with a map, the map delays with the normal scrolling. This happens with the native scrolling under ionic. I tried

`$ionicConfigProvider.scrolling.jsScrolling(true);`

With this a map scrolls fine, but the scrolling self isn't what we want. I tried a function on-scroll

`$scope.refreshMap = function() {
   map.refreshLayout();
};`

This doesn't solve the problem with the delay. So, any recommendations or hints to make it smooth?

**Comment by wf9a5m75** [comment]
I am not familiar with ionic, but the scroll delay is one of the known issues that are not able to solved.
This plugin uses two scroll views in the native side, one is browser, and the other one is for map.
If the browser scroll view is moved, then the other scroll view is also moved after that.
That's why the delay is occurred.

There is no solution currently (as far as know). Please use the plugin as is.

**Comment by Bloggerschmidt** [comment]
Thank you for this information. Maybe we can solve it later. So I close the issue.

**Comment by joesleiman** [comment]
ionic2 same issue , are you find a solution
using cordova-plugin-googlemaps
