### ISSUE TITLE
Styled iOS SDK 

### ISSUE THREAD

**Issue by Hurinj** [mapsplugin/cordova-plugin-googlemaps#1109]
Hello,

I just find that the style is now available on SDK !!
https://developers.google.com/maps/documentation/ios-sdk/styling#apply_styles_to_your_map

Do you know if I load the JSON as they say in the GMSMapStyle in xcode project it is going to work ? Or we have to wait for a new version of the plugin ?

Thank :D

**Comment by wf9a5m75** [comment]
>we have to wait for a new version of the plugin?

Yes, please.

**Comment by ledil** [comment]
do you have some timelines ?

**Comment by wf9a5m75** [comment]
I'm working for the new version so hard recently.

**Comment by SylvainGuittard** [comment]
+1 for this feature :)
(Thanks for the hard work)

**Comment by rafaelpradella** [comment]
+1 for this feature o/

**Comment by jmordica** [comment]
+1 for this as well.

**Comment by samedii** [comment]
@wf9a5m75 How far have you gotten on this? Is it a waste of time to work on a PR?

Should it already be working on android? - I looked through the code and it didn't seem like styling was supported yet

Android:
https://developers.google.com/maps/documentation/android-api/styling

iOS:
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_style

**Comment by wf9a5m75** [comment]
Sending pull request is welcome.
Before craiming, move your hands.

**Comment by samedii** [comment]
@wf9a5m75 Okay, personal attack... it felt like a valid questions since you wrote "I'm working for the new version so hard recently."

**Comment by wf9a5m75** [comment]
New version is on the multiple_maps branch. 

https://github.com/mapsplugin/v2.0-demo

**Comment by wf9a5m75** [comment]
I know the feature (also have to implement it), but my time is really limited.
Unless somebody send a pull request, all features have to wait until implemented.
My time is really limited, so features are implemented one by one.

You can folk this repository anytime, and you can modify it as you want.

Helping is welcome (such as sending a pull request), but just "pushing a pressure" is not welcome (such as "just herry up!").
"+1" is acceptable, but "Should implement it soon" is not help at all.

**Please fork the repository, and implement it by yourself. Then sending a pull request is really appreciated. That's open source.**

----

I have been working on another feature on the new version currently.
New version is on the multiple_maps branch. 
https://github.com/mapsplugin/v2.0-demo

Why the new version is not on the master? Since it's still beta, and the XWalk has problem with the new version of this plugin.

**Comment by wf9a5m75** [comment]
Check out https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1180#issuecomment-261125046
