### ISSUE TITLE
Low performance if custom icon is PNG

### ISSUE THREAD

**Issue by Fayozjon** [mapsplugin/cordova-plugin-googlemaps#1198]
Hello! Im using crosswalk so i cant use v2 yet, at 1 version of plugin when im using PNG as a marker icon its slow down map performance. With native markers working at 5 - 10 mb of ram but with PNG markers app slows x10 times and EATS about 150 - 200 mb of ram

**Comment by wf9a5m75** [comment]
Please provide example project using github (or bitbucket).
I wonder it's your png file problem or others.

**Comment by Fayozjon** [comment]
@wf9a5m75 I can only provide png or you need whole project ?

**Comment by Fayozjon** [comment]
Can you give me example png for using. Dimensions, alpha etc. Just as example

**Comment by wf9a5m75** [comment]
Please provide your whole project (simplify is fine). Otherwise, I can't inspect your issue, then close this issue.

**Comment by pke** [comment]
That's probably because how this plugin loads marker icons. Instead of loading the bitmap once and using it for every marker, it loads a new bitmap for each marker. That's also the only reason why the `addMarker` function in this plugin is async instead of sync (like in the Google SDK). Bitmap loading should not be part of the `addMarker` function. It should be instead a separate function that creates a `MarkerIcon` from various sources. And then one would hand in the created icons to the `addMarker`.

**Comment by Fayozjon** [comment]
@pke Hello, can you provide example code please if you dont mind.
I will appriciate it.

**Comment by pke** [comment]
I don't have any example code you ask for. I am just testing this plugin and decide if I can use it. It has a few drawbacks, like the one you discovered with the memory hog.

**Comment by wf9a5m75** [comment]
Since no example png or project code are provided, I close this issue. If you provide them, I will check this one.
