### ISSUE TITLE
div inside map issue

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1256]
i have implemented the google maps places api .
i can't select options . i think clics are captured by the map
how make it works
![capture](https://cloud.githubusercontent.com/assets/15154710/21816750/81747c8a-d761-11e6-9e99-3fc4f08cdf04.PNG)

**Comment by wf9a5m75** [comment]
Use the v2 beta plugin.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

**Comment by bigbossmaher** [comment]
is the V2 version can solve also the same issue with panel sidebars ( element in side bars are not clickble )
![capture](https://cloud.githubusercontent.com/assets/15154710/21911730/5b3667b4-d922-11e6-98a9-d5f39fe57de9.PNG)

**Comment by wf9a5m75** [comment]
It depends on your code. The plugin v2 recognizes all html elements automatically, but some framework (I don't know how to implement the sidebar) blocks the plugin.
You have to adjust your code, or HTML for your purpose.

One hint is that specify higher value for `z-index` of CSS to sidebar.
This might be helpful.

If no, please share your project (whole project files) using github or bitbucket.
Otherwise, no more support is available.

**Comment by bigbossmaher** [comment]
this is my project
the html elements over the map are not working
z-index also not working
https://github.com/bigbossmaher/parking
