### ISSUE TITLE
Installing v2.0 and getting below error 

### ISSUE THREAD

**Issue by yogeshwar607** [mapsplugin/cordova-plugin-googlemaps#1296]
Failed to install 'cordova-plugin-googlemaps':Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-googlemaps can be added. You may use --force to add the plugin and overwrite the conflicting attributes

![screen shot 2017-02-09 at 1 14 00 am](https://cloud.githubusercontent.com/assets/10059011/22754392/5dfe8f64-ee65-11e6-8165-8751487eaca9.png)

**Comment by wf9a5m75** [comment]
It means another plugin (or your app) already specifies the `android:largeHeap` property, but the google maps plugin also tried to modified this attribute.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/457f5ee1cfde575f7e360aa27d1bedaa5761d066/plugin.xml#L181-L183

This plugin v2 uses memory cache internally, that's why I specified this attribute.
I think there is no problem with `--force` installation.
