### ISSUE TITLE
LatLngBounds and markers visibility

### ISSUE THREAD

**Issue by noveltys** [mapsplugin/cordova-plugin-googlemaps#1298]
Hi,

when i use LatLngBounds, the markers are not fully visible at the boundaries of the map. I can understand why, but is it normal behavior ?

cordova-plugin-googlemaps 1.4.0 + Ionic 1.3

![bounds](https://cloud.githubusercontent.com/assets/12413791/22783510/6ca7c6b8-eecc-11e6-8754-b151e849c13b.png)

**Comment by battika** [comment]
Same here, but I have always considered it normal. What would your expectation be?

**Comment by noveltys** [comment]
@battika i would like to see the markers entirely. Maybe by zooming out a bit ? ;)

**Comment by wf9a5m75** [comment]
The LatLngBounds consider only coordinates.
In your screen capture,  the bottom of all markers are located in the screen.
So this is correct.
You need to zoom out a bit.

**Comment by noveltys** [comment]
Do you have any tips on how to make app zoom out automatically, when all markers are loaded, to see the markers on the bounds entirely ?

**Comment by noveltys** [comment]
When i use moveCamera(), markers at the bounds are fully visible, but half visible using animateCamera(). Any comment ?

![movecamera](https://cloud.githubusercontent.com/assets/12413791/22931931/d1601242-f2c6-11e6-9567-52be28abe3a7.png)
![animatecamera](https://cloud.githubusercontent.com/assets/12413791/22931974/fa88c042-f2c6-11e6-8fee-debcfe14af6d.png)

**Comment by wf9a5m75** [comment]
When you have a technical question and the source code is fully open, **please try to check the code at first before asking easily**.

The `moveCamera()` and the `animateCamera()` methods use both the `updateCameraPosition()` internal method.

[PluginMap.java#L257-L271](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/ecdccaf5ad5e2b52a34fe15a83ac92f0a6efab01/src/android/plugin/google/maps/PluginMap.java#L257-L271)

When you pass an array of LatLng pairs, the plugin calculates the new camera target with enough margin at `(int)(20 * this.density)`

[PluginMap.java#L305-L308](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/ecdccaf5ad5e2b52a34fe15a83ac92f0a6efab01/src/android/plugin/google/maps/PluginMap.java#L305-L308)

The `moveCamera()` method case,  execute the native method `map.moveCamera(cameraUpdate);`, then returns to the JavaScript side. That's all.

However, the `animateCamera()` method case, are calculates the camera target again, because when you specify another attributes, such as `tilt` or `bearing`, the native camera does not contains the bounds that you specified fully.

But Google does not provide option to specify margin when the code uses `CameraPosition.builder();`. That's why.
[PluginMap.java#L329-L346](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/ecdccaf5ad5e2b52a34fe15a83ac92f0a6efab01/src/android/plugin/google/maps/PluginMap.java#L329-L346)

**Comment by wf9a5m75** [comment]
If you use the plugin v2, you can specify the `padding` option.
https://github.com/mapsplugin/v2.0-demo/blob/15be5b34f87b465f6b4420c7eb18d49d370dcee5/www/Map/animateCamera.html#L42

**Comment by Anopetia** [comment]
Here is a solution for your problem : 
```

      map.moveCamera({
                               target: [currentLocation, latLng]
                           }, function () {

                               map.getCameraPosition(function (camera) {
 
                                   map.setZoom(camera.zoom - 0.5);

                               });

                           });
```

**Comment by noveltys** [comment]
Thank you @Anopetia @wf9a5m75
