### ISSUE TITLE
Kml read properties

### ISSUE THREAD

**Issue by sudhirbitsgoa** [mapsplugin/cordova-plugin-googlemaps#1327]
Hi I'm plotting this kml on the map
https://raw.githubusercontent.com/sudhirbitsgoa/imagepart/master/app/test.kml
``` 
<name>Area Features</name>
    <description>Area Features</description>
    <Placemark>
      <description> DIV1 </description>
      <styleUrl>#area0</styleUrl>
      <Polygon>
```

Not able to read description using kmllayer.
Please help me with small code snippet.

kmllayer.get('name')
kmllayer.get('description')
did not help 
Thanks

**Comment by wf9a5m75** [comment]
I designed the KML Layer similar with the KML layer of Google Maps API JavaScript v3.
The plugin supported tags are here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/530#issuecomment-107611703

In order to read particular element, you need to click it on the map.

The below code should work (but not checked).

```js
  map.addKmlOverlay({
    url: url,
    preserveViewport: false,
    animation: true
  }, function(kmlLayer) {
    kmlLayer.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay, latLng) {
      if (overlay.type == "Marker") {
          alert(overlay.get("name"));
          alert(overlay.get("title"));  // Description converts to title.
      }
    });
  });
```

**Comment by sudhirbitsgoa** [comment]
Thanks for the quick answer. I used the same code. But still overlay.get('title')
does not give the description or even the name. Can you please test at your end. Thanks.

**Comment by sudhirbitsgoa** [comment]
Hi What i observed is 
if overlay.type === marker ) overlay.get('title') // works fine

but for overlay.type === LineString || overlay.type === Polygon the get method does not work. Can you please verify

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v1.2.1/example/DemoApp/www/pages/kmlOverlay.html#L219-L244

**Comment by sudhirbitsgoa** [comment]
Thanks for the example. But the example does not have layer.get('title'); or layer.get('description') for Polyline and Polygon. I did try it. But they are pinting null

**Comment by sudhirbitsgoa** [comment]
Can you please help me in this.

**Comment by wf9a5m75** [comment]
Since this plugin source code is full open, please try to read the code before asking easily.

For example, `<Point>` tag is parsed as Marker at here.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/eee3cc817cc9771192d21019a05f5c5202c8f27a/src/android/plugin/google/maps/AsyncKmlParser.java#L204-L242

Regarding of this code, only parse `coordinates`, `name`, `description`, `styleurl`, and `icon`.
Other tags are ignored.

**Comment by sudhirbitsgoa** [comment]
I have a situation where i need to show on which kml polygon feature the click happened. How can i achieve that. Not by changing color rather a info window.

**Comment by wf9a5m75** [comment]
Not supported that feature.

**Comment by sudhirbitsgoa** [comment]
I have raised PR for this https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1351

**Comment by wf9a5m75** [comment]
Since the v1.4 development has been finished, no more improve for the v1.4.
But in v2, I will consider your request. Thank you for sending a pull request.
