### ISSUE TITLE
Map position is not sync with scrolling of page

### ISSUE THREAD

**Issue by goutamsinghase** [mapsplugin/cordova-plugin-googlemaps#1365]
This is seriously nightmare. I have an app which has a page containing some information and near footer I have integrated the map with height 400px and width 100%. Map is loaded, but when I scroll up or down the page map is also going to up and down where the map is needed to be fixed on that div. 

I have inspect (chrome://inspect/#devices), but seen no map element. actually it is native map. 

I have searched for trick to solve that, found one guy have faced the same problem - 

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/199#issuecomment-72644131

So, I request you to tell the any solution for fixing this issue?

**Comment by wf9a5m75** [comment]
You can choose to use the plugin v2 (multiple_maps branch) or use another maps plugin :)

**Comment by goutamsinghase** [comment]
But Ionic recommend your plugin as it is in Ionic V2 [Documentation.](https://ionicframework.com/docs/v2/native/google-maps/)

 I am in stuck in this view flickering issue,

**Comment by wf9a5m75** [comment]
The wrapper is not developed by me. Someone created it.

**Comment by nimosza** [comment]
I'm using jquery mobile and phonegap and since I've started trying to use phonegap build to create a release version of my app, I've been having the same problem. 
When I scroll up and down on the page, the map remains in a static position behind  the content.
It's been working perfectly using the phonegap cli.
It's worth noting that I had to use version 1.3.9 of the plugin rather than version 1.4 to get it working with phonegap build.
I'm pretty much at my wits end and have started looking at alternatives to this plugin which is a path I really don't want to have to go down, as this plugin has worked perfectly up until now.
