### ISSUE TITLE
Map init results in screen flicker

### ISSUE THREAD

**Issue by philib** [mapsplugin/cordova-plugin-googlemaps#1368]
Hey everyone,

everytime i initialize the map there is a little flicker in my ionic2 application (lookslike the view rerenders). Thats really annyoing and doesnt result in a good user experience.  Am i missing something or is there a possiblity to get rid of this quirk?

Thanks in advance.

**Comment by wf9a5m75** [comment]
First of all, you need to understand how this plugin works.
The map view is placed under browser, it means the map view is not HTML element.
Since the browser has to be transparent.
But I guess the ionic or your code try to set background color.

For the first try, just wrap the map initialize code with setTimeout();

```js
setTimeout(function() {
  map = plugin.google.maps.Map.getMap(....);
}, 1000);
```

**Comment by philib** [comment]
Hey,

thanks for your response. I tried wrapping getMap(...) step with setTimeout() but it just delays the flicker for the given time :(

**Comment by philib** [comment]
Hey,

i dont think it's the background color. Even if i set backgroundColor = 'none' there is a flicker.
The flicker appears only at the very first map init. Even if i call the initMap function for a different div again (on a other page) there is no flicker at all.

Could it be something else?

Thanks in advance

**Comment by wf9a5m75** [comment]
Since this plugin uses Google Maps native APIs, the google map is not a HTML element.
Because of this, the map view is placed **under the browser**, and the browser **must be transparent.**

You can set background color as map option.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.setBackgroundColor()

**Comment by philib** [comment]
Hi,

i do understand how it works. I analyzed the source code. It seems that the cordova.exec() call causes the app to flicker: 
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/0c6cae90e500fdb65d5ed880a5fdc3ca7d83e80f/www/googlemaps-cdv-plugin.js#L389-L395

Therefore background color is not a problem

BTW: 
`setTimeout(function() {
            self.refreshLayout();
            self.trigger(plugin.google.maps.event.MAP_READY, self);
}, 100);`

does not affect the flicker

**Comment by philib** [comment]
does someone have an idea?

**Comment by wf9a5m75** [comment]
Please share your project (all files) on github or bitbucket.

**Comment by btdevn** [comment]
I am facing this same issue, is there any solution to this?

**Comment by z1ad** [comment]
Ive come across the same issue and found a fix. Basically the flicker is due to updating multiple elements and causing a reflow. The solution is to group all the updates into a single batch. There is a great library that explains and deals with this concept: [fastdom](https://github.com/wilsonpage/fastdom)

If you prefer to do it manually, you can wrap the call to getMap() inside a requestAnimationFrame.

```
window.requestAnimationFrame(function() {
    map = plugin.google.maps.Map.getMap(....);
});
```
