### ISSUE TITLE
KML file not able to display multiple colors

### ISSUE THREAD

**Issue by Julieng50** [mapsplugin/cordova-plugin-googlemaps#1379]
Hello !
Importing KML file, I'm not able to apply different colors to different lines.
Check the following file :
[example.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/887987/example.txt)
Try it using http://www.gpsvisualizer.com/map_input?form=google 
You will see 2 different lines color. But when using google maps cordova plugin, you will only see 1 color.

Is this a bug ? Can someone help me ?
Thanks.

**Comment by wf9a5m75** [comment]
Since KML format has lots of freedom, this plugin does not support all features.
Even for me, it's too difficult for programming.

This is the example that contains different color polylines.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v1.2.5/example/DemoApp2/www/kml/polyline.kml

Maybe you need to modify your KML file for this plugin by your hand.

**Comment by Julieng50** [comment]
Thanks, it works ! :)
Is there any document showing what we can do with kml in this cordova plugin ?
