### ISSUE TITLE
HTML MARKER İNFO

### ISSUE THREAD

**Issue by tolgatasci** [mapsplugin/cordova-plugin-googlemaps#1387]
My project HTML infobox
`title: '<h1>LOCA</h1>' == priew <h1>loca</h1> String`

```
@SuppressWarnings("unused")
  private void showInfoWindow(final JSONArray args, final CallbackContext callbackContext) throws JSONException {
    String id = args.getString(1);
    Marker marker = this.getMarker(id);
    marker.showInfoWindow();
    this.sendNoResult(callbackContext);
  }
```

i need html content `<div><h1><img>`

**Comment by wf9a5m75** [comment]
Use the plugin v2

**Comment by tolgatasci** [comment]
I would like to thank you.

**Comment by tolgatasci** [comment]
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="<YOUR KEY>" --variable API_KEY_FOR_IOS="<YOUR KEY>"

ERROR NOT DOWNLOAD 

Calling plugman.fetch on plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps"
Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone
Running command: "C:\Program Files\Git\cmd\git.exe" clone https://github.com/mapsplugin/cordova-plugin-googlemaps 

drunk

**Comment by wf9a5m75** [comment]
>You may use --force to add the plugin and overwrite the conflicting attributes.

**Comment by wf9a5m75** [comment]
You can install with --force option.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1296#issuecomment-278446860

**Comment by tolgatasci** [comment]
:( force stop apps not running...
`<engine name="android" spec="latest" />
  <plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps">
    <variable name="API_KEY_FOR_ANDROID" value="xxxx" />
    <variable name="API_KEY_FOR_IOS" value="xxxx" />
    <variable name="NSLOCATIONWHENINUSEUSAGEDESCRIPTION" value="Show your location on the map" />
    <variable name="NSLOCATIONALWAYSUSAGEDESCRIPTION" value="Trace your location on the map" />
  </plugin>`
--force install

**Comment by tolgatasci** [comment]
@wf9a5m75 help me pls

**Comment by wf9a5m75** [comment]
The error message means another plugin (or your app) already specifies the `android:largeHeap` property, but the google maps plugin also tried to modified this attribute.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/457f5ee1cfde575f7e360aa27d1bedaa5761d066/plugin.xml#L181-L183

This plugin v2 uses memory cache internally, that's why I specified this attribute.

You can do two options:

(1) git clone https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps, then modify the plugin.xml , then install to your app

(2) find the plugin that specify the `android:largeHeap` attribute in your app, and remove it.

**Comment by tolgatasci** [comment]
Thank you <3
