### ISSUE TITLE
Paid Work Request to Help Debug App

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1432]
Sometimes the marker isn't clickable for infoWindow, refresh same marker is clickable for infoWindow, refresh (top right refresh icon) same marker doesn't appear, refresh same marker shows up and is clickable for infoWindow.  There are no xcode nor js errors when this happens.  The MARKER objects that work and don't work look identical.

I am still having frequent app crashes also.

Still seeing the Image Overlay getting left on the map after remove call is made on pan and zoom.

**Comment by wf9a5m75** [comment]
>I am still having frequent app crashes also.

I need more information about this. When crash the app?
Panning or zooming?

>Still seeing the Image Overlay getting left on the map after remove call is made on pan and zoom.

And could you take a screen capture about this?

**Comment by KimberleeDArmstrong** [comment]
![image1](https://cloud.githubusercontent.com/assets/9216004/25728053/55e135fa-30f2-11e7-9b8f-c1f9f278c597.PNG)
Image Layer getting left on the map 

The crash happens when panning and zooming.  It will get slow then freeze and then crash.

I also noticed something that I think is new.  I have a listener that listens for cordova CONNECTION changes.  The online event seems to be getting fired on every pan and zoom.  I will look closer.  i just noticed it in the logs and thought I would mention it.

**Comment by wf9a5m75** [comment]
I'm not checked your code deeply, but you added lots of GroundOverlay.
It is not better way. I think TileLayer is more smart way.
I'm not sure I advised GroundOverlay or TileOverlay, but I did that to someone, because the person asked without enough information.

But in your case, TileLayer is more better and simple.
Check out here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/TileOverlay/addTileOverlay/README.md

**Comment by KimberleeDArmstrong** [comment]
Ok thank you I will try that.

**Comment by wf9a5m75** [comment]
I committed some code to prevent crash for iOS.
Please reinstall the plugin.

**Comment by KimberleeDArmstrong** [comment]
The online listener issue was my issue.  I fixed that, Please ignore.  I haven't added any ground layers.  I have always had a weather and a lines one and that is all.  You never mentioned the tile layer before to me, so I will try that but getting that data from our map server as tiles will take some development time.

I am still getting crashes with the latest plugin.  Its weird because there is never a crash log for the app when it crashes.  I tried to video it but when the app crashes, the camtasia recorder crashes too.

I have some videos with the marker problems.  But I couldn't upload them.  I will try emailing them. I feel like there is a timing issue when loading markers maybe?  If all the markers load properly and info windows open correctly app doesn't seem to crash.

**Comment by wf9a5m75** [comment]
Regarding of the clicking on marker problem, this is a problem of the Google Maps SDK for iOS.
Actually I thought marker does not open infoWindow sometimes, but it's finger size is bigger than mouse pointer problem.

This is the evidence.
In order to evaluate the clicking position accuracy, I tested on the iOS simulator.

The test code is very simple.

```js
document.addEventListener("deviceready", function() {
  var mapDiv = document.getElementById("map_canvas");
  var options = {
    'camera': {
      'zoom': 13,
      'target': {"lat": 37.4419, "lng": -122.1419}
    }//,
    //'mapType': plugin.google.maps.MapTypeId.NONE
  };
  var map = plugin.google.maps.Map.getMap(mapDiv, options);
  map.on(plugin.google.maps.event.MAP_READY, onMapReady);
});

function onMapReady() {
  var map = this;

  map.on(plugin.google.maps.event.MAP_CLICK, function(latLng) {
    map.addMarker({
      position: latLng,
      title: latLng.toUrlValue()
    }, function(marker) {
      marker.showInfoWindow();
    });
  });
});
```

When I clicked on the map, the plugin created a marker on the position that I clicked actually.
It means the plugin calculates correct touch position.
![img1](https://cloud.githubusercontent.com/assets/167831/25778648/46fbb98e-32b9-11e7-9402-e563bc87c82e.gif)

Another test. If I clicked on the very close position to a marker, the plugin should add another marker.
The very close position usually is covered by finger.
(Because human finger is bigger than mouse pointer). 

![img2](https://cloud.githubusercontent.com/assets/167831/25778662/c649dfa4-32b9-11e7-9512-41c9a019f61c.gif)

As the result, the plugin works correctly.

------------

Thus, the Google Maps SDK for iOS does not set any click bounds(margin) on marker.

That's why you (andI also) feel that marker does not response on click (tap).
So this is not plugin's problem.


![click_test](https://cloud.githubusercontent.com/assets/167831/25778636/d30dd44e-32b8-11e7-8d4b-54c1d4956a8e.gif)

--------------

I hope Google will solve this issue.
But the current solution is that make icon image with bigger size.

**Comment by KimberleeDArmstrong** [comment]
http://www.youtube.com/watch?v=De6pHezpyVE

**Comment by wf9a5m75** [comment]
Um, thank you for inspecting. It is interesting.

**Comment by wf9a5m75** [comment]
By the way, could you reinstall the plugin with `--nofetch` option?
The npm command caches the files in local.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1435#issuecomment-299580754

**Comment by KimberleeDArmstrong** [comment]
I installed the plugin with nofetch.  Thank you that makes sense as to why I kept installing the plugin and not seeing your fixes.  Regarding infoWindow not opening.  I still think this is a timing issue on marker creation.  After the marker is created if it is clicked and the infoWindow does not pop up, it doesn't matter how many time you click all around and on it, it won't ever open the infoWindow.  I refresh, which does a googlemap.clear() and recreates the markers.  The same marker that would not open the infoWindow before will now  open the infoWindow on every click.  I also noticed that if the infoWindow won't open on a marker then the setVisible function also won't work.   
Notice in the video all markers with a hat behind them are a group of markers called "My Items".  The markers with an "F" won't openInfoWindow on click.  The same 2 markers do not respond the setVisible(false) when it is called.  

http://www.youtube.com/watch?v=R6OkDZmsfjM

**Comment by wf9a5m75** [comment]
I (probably) figured out the problem, and fix it.
The reason is in the plugin initialization process.

Please reinstall the plugin with `--nofetch` option.

**Comment by KimberleeDArmstrong** [comment]
OH WOW!!!!  That is awesome!  That fixed it! :-D  I was really thinking it was in my code because between 3 different apps I have 8 different marker types and the problem only ever happened on 1 subtype of 1 marker type.  I thought it had to be in my code.  I have been looking at it all day today, but nothing I changed was fixing it.  But the plugin update did the trick!!!  I think I am currently bug free.  I will talk to my boss when he gets back in the offfice later this week about a thank you present.  Thanks!

**Comment by wf9a5m75** [comment]
Sounds good:)
