### ISSUE TITLE
How to enable mapTypeControl

### ISSUE THREAD

**Issue by shairyar** [mapsplugin/cordova-plugin-googlemaps#1439]
I am trying to enable the mapTypeControl so that the user can select the type of map they want to look at `HYBRID`, `SATELLITE` or `TERRAIN`

```
map.setOptions({
    'controls': {
        'compass': true,
        'myLocationButton': true,
        'zoom': true
    },
    'camera': {
        'target': ionic,
        'zoom': 18,
    },
    'styles':{
        'mapTypeControl': true,
        'MapStyleOptions': {
            'style': 'DROPDOWN_MENU'
        }
    },
    'mapTypeIds': ['MAP_TYPE_TERRAIN', 'MAP_TYPE_HYBRID']
});
```

The map appears but there are no controls, what am i doing wrong here?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setMapTypeId/README.md

**Comment by wf9a5m75** [comment]
This plugin is not equal with Google Maps JavaScript API v3.

Since this plugin does not give any UI components, so there is no option like this:
```

    'styles':{
        'mapTypeControl': true,
        'MapStyleOptions': {
            'style': 'DROPDOWN_MENU'
        }
    },
    'mapTypeIds': ['MAP_TYPE_TERRAIN', 'MAP_TYPE_HYBRID']
```

Thus you need to create a UI component by yourself.
This is example code.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setMapTypeId/README.md
