### ISSUE TITLE
Native LatLngBounds ContainsLocation?

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#1441]
Is there any chance to implement GMSGeometryContainsLocation() (iOS) and LatLngBounds.contains() (Android) methods?

Already implemented LatLngBouns.contains() works only for regular shapes like rectangles and squares. If the bounds is circle, trapezoid etc., the methods fails (returns true even the given point is not in bounds).

I guess the native methods will solve it properly.

**Comment by wf9a5m75** [comment]
I see. But I'd like to above executing the native method as much as possible.
Because it takes a callback.
I will try to implement JS code.

**Comment by vosecek** [comment]
Any update of this please?

**Comment by wf9a5m75** [comment]
Sorry, I'm so busy.
But you can try this by yourself. The source code is fully open.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/bf6156189d28ec838bddf36517a5c661305e3a54/src/android/plugin/google/maps/PluginMap.java#L2293-L2330

**Comment by wf9a5m75** [comment]
Thank you for waiting long time. I implement two methods in JavaScript.
In order to use these methods, please reinstall the plugin from the multiple_maps branch (not the master branch).

---

[poly.containsLocation()](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/poly/containsLocation/README.md)

![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v2.0.0/class/utilities/geometry/poly/containsLocation/image.gif)

----

[poly.isLocationOnEdge()](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/poly/isLocationOnEdge/README.md)

![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v2.0.0/class/utilities/geometry/poly/isLocationOnEdge/image.gif)

**Comment by wf9a5m75** [comment]
By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some tip because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
When you donate some amount to the project, please include your issue number in your name.

**Comment by vosecek** [comment]
Thanks, it works.

There seems to be bug in multiple_maps branch in Polygon section.

While remove() method called on created polygon, I got error: TypeError: undefined is not an object (evaluating 'self._isRemoved') — Polygon.js:131

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I fixed it. Please try again.

By the way, I really appreciate for your donation!!
