### ISSUE TITLE
google map scroll issue

### ISSUE THREAD

**Issue by joesleiman** [mapsplugin/cordova-plugin-googlemaps#1452]
Ionic version: 3.2.0

I'm submitting a bug report

Current behavior:
the map scroll when scroll the page with delaying . i scroll down after while the map scroll to his position .
Expected behavior:

it should the map still fix at his position
Steps to reproduce:
<div #map id="map"></div>

same" loadmap()" function as in the documentation.
i'm using it inside
Other information:

when i scroll the app where the map exist. the map scroll too , and there is a delay when it scrolled.

another issue : if i have a select tag like (ion-select) above the map directly , then i click on the drop down to open a modal that have options, the modal open in the center of the page above the map , i can't choose any of the options . when i click on the option it look like i click on the map, it doing zoom .
same if i scroll and stop scrolling when the map appear under the header of the page , the back button can't clicked.

another issue: i used it inside <ion-slide>because i'm using wizard form so when i click on next button to go to next slide, a part of the map appear on the second slide. i can decrease the width but it have to not appear. because on first slide appear 100% without touching the border-right of the app .

**Comment by wf9a5m75** [comment]
This plugin uses native google maps view, not JavaScript Google maps API. That's why the scrolling the page causes the map view delay. This is not a bug. 
If you don't like it, you should use the Google maps JavaScript API instead of this plugin.


And I think you use the ionic wrapper version which is based on the v1.4

If you use it, you MUST put HTML elements UNDER the map div.

**Comment by joesleiman** [comment]
Yes u r right im using the plugin from ionic native . But now im using google maps  api  javascript . But i post this may i find solution for another time . What you mean by put html elements under the map div : like another empty div <div></div>

**Comment by wf9a5m75** [comment]
The plugin v1.4 monitors only the child elements under the map div.

```html
<div id="map_canvas">
<button>test</button>
</div>
```

Something like that.

------

If you use the plugin v2 without the ionic wrapper, you don't need to do that, because the plugin monitors all HTML elements.

If you are interested in, check out here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md

**Comment by joesleiman** [comment]
Iam using ionic v3.2.0 plugin ionic wrapper. 
I will test it later

**Comment by wf9a5m75** [comment]
ping

**Comment by kozuch** [comment]
I am not able to make an onclick work on an overlapping element on plugin v1.4. It does not matter whether I put my element INSIDE the map DIV or just after it. :( Tried both static HTML onclick definition and dynamic attachment via jQuery attr. Can someone fix this?
