### ISSUE TITLE
Performance and battery usage

### ISSUE THREAD

**Issue by stalniy** [mapsplugin/cordova-plugin-googlemaps#1559]
Before asking your question, problem or request , please read this page
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/articles/before_post_your_issue/README.md

- What is your question, problem or request?
Currently my Android shows me a screen where it says that my app abnormally uses battery. Application is built on top of google maps cordova plugin and I think this is due to `setTimeout` synchronisations of native maps with DOM elements.
So, I have 2 suggestions to improve performance of this:
1. Use `MutationObserver` instead of `setTimeout` (and use polyfill for older devices). Currently support is pretty good - http://caniuse.com/mutationobserver/embed . 
2. Provide an option to disable synchronisation (in most cases you want to display map once and in rare cases manually control visibility or sizing)
3. There are some non-optimized  (e.g., `delete cacheDepth`) JavaScript code which I'd like to optimize

If you are agree with my suggestions, I will start working on 3 different PRs (1 for each suggestion)

- What version of this plugin do you use? Please including miner version ($> cordova plugin list)
2.0.0-beta2-20170709-1518

- Screen capture or video record?
![image-1](https://user-images.githubusercontent.com/1159966/28249140-e42f4d52-6a58-11e7-8249-0e640b610c0a.jpg)

**Comment by wf9a5m75** [comment]
Thank you for suggestions.

#1. The reason of setTimeout is Android 4.3 does not support 'MutationObserver'

#2. the plugin you use version is old. It's already changed.

#3. Send me a pull request. After reviewing, accept or not.

**Comment by stalniy** [comment]
1. For android 4.3 we could use polyfills or disable sync (based on setTimeout)
2. How can I disable setTimeout sync?

**Comment by wf9a5m75** [comment]
Since I don't want to give access to the dom tree parse. Because the most of developers use these options without deep understanding the code. (Did you also read all code of this plugin?)

**Comment by stalniy** [comment]
Sorry I missed the point. 
1. So, are you agree to use mutation observer + polyfills for android lower 4.3?
2. You said that I use old version of the plugin but I can't see any option to prevent recursive setTimeout calls in the last version, that's why I asked whether there is an existing option. 

To answer your question:
As I understood there is a method `refreshLayout` which refreshes position and depth of native map. I looked through all JavaScript code

I created this issue because in my ionic application because of map sync animation during page transitions (from map page to another) slow and buggy 

So the only my goal is to find and provide a better way to sync map because eventually users of my app won't be happy :)

**Comment by wf9a5m75** [comment]
>So, are you agree to use mutation observer + polyfills for android lower 4.3?

Please send a pull request. I will review the pull request is good or not. If I test your pull request, and  it improves performance (and no affect other parts), I will happy to merge it.
I can not guarantee to accept your pull request for just idea.

----

> I can't see any option to prevent recursive setTimeout calls in the last version

Yes, I don't create it. But I changed the plugin code a lot in a few days. I just said `2.0.0-beta2-20170709-1518` is old.

The reason of recursive parsing is to detect new HTML elements (such as Dialog box) and changing the size or position (such as side menu).
Also, detect size and position of HTMLInfoWindow.

The plugin stops the checking if you don't touch or any HTML elements are changed in 1.6 sec (50ms*4 + 200ms*6) from the first check.

----

The `refreshLayout()` method is just set `needUpdatePosition = true`. `putHtmlElements()`  is more important method.

Do you understand how to control the v2 manage HTML elements? The mechanism is different from v1.

----

>  in my ionic application because of map sync animation during page transitions (from map page to another) slow and buggy

Please share your project files. I don't understand what you are talking about. (I'm not ionic user)

**Comment by stalniy** [comment]
Could you please describe the logic inside `putHtmlElements`? why do you need to watch all nodes and only that one which is assigned to the map? maybe some non-obvious details of implementation, etc

**Comment by wf9a5m75** [comment]
I will describe the reason with drawing later.

**Comment by wf9a5m75** [comment]
Thank you for waiting.

Let's explain from this question. 

## why do you need to watch all nodes and only that one which is assigned to the map?

This is an example app. You can see the code at https://github.com/mapsplugin/simple_example_app

![screen shot 2017-07-17 at 3 04 13 pm](https://user-images.githubusercontent.com/167831/28292327-642d58a0-6b03-11e7-8a3c-81e72213c525.png)

At this time, hierarchy is like this.
Header is `position: fixed; z-index: 2;`. And map view is under the browser (as you may know).

![hierarchy](https://user-images.githubusercontent.com/167831/28292982-910af668-6b06-11e7-933e-42311a58e64e.png)

--------

When you scroll up the page, if the map moves to the position under the header, what happens?

![screen shot 2017-07-17 at 3 40 30 pm](https://user-images.githubusercontent.com/167831/28293006-bae14fe6-6b06-11e7-9505-d2c2caf46748.png)

You will expect:
- if you click on the header, you want to catch the click event on header,
- and if you click on the map, you want to catch the click event on map.

Assume if the plugin does not watch the depth(z-index + order of child elements), and if you click on the header, how to detect the click is on the map or the browser?

![screen shot 2017-07-17 at 3 40 30 pm](https://user-images.githubusercontent.com/167831/28293819-fa689ee0-6b0a-11e7-9eab-6b981a7084e6.png)

`<div id="page">` covers `<body>`, `<div id="header">` covers `<div id="map">`....

It's not possible if the plugin considers just size and position of the map div.

** The fixed header is not possible with v1.4, because it's not under the map div.**

---

Another case is, **a dialog box which is created with HTML**.

![screen shot 2017-07-17 at 4 18 25 pm](https://user-images.githubusercontent.com/167831/28293926-ad1c852e-6b0b-11e7-8fa1-247e61b6be8e.png)

In this case, the HTML dialog box covers all area. But how to detect it if the plugin considers only size and position of HTML elements?

![screen shot 2017-07-17 at 4 25 31 pm](https://user-images.githubusercontent.com/167831/28294176-2c8ddf8c-6b0d-11e7-9925-877b20fa9a61.png)

**The plugin v1.4 can not detect this case, because it's not under the map div.**

---

Actually I tried to monitor the position and size of all HTML elements. But after soon, I noticed the relationship(z-index, and order of child elements) of all HTML elements are really important.

Until the last week, the plugin uses `querySelectorAll("*")`.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/f0a12dd150f762af987c629e4bebb1b728722656/www/Common.js#L216-L275

But I figured out this method does not keep the relationship of HTML element all the time (https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1541)

That's why I changed the code to the recursive parsing.

I know there are some possibility to improve the performance (like `MutationObserver` you suggested). That's why I said `please send me a pull request`.

**Comment by wf9a5m75** [comment]
##  the logic inside putHtmlElements

The benefit of v2.0 is the plugin recognizes all HTML elements correctly.
That's why the developer does not need to control such as `map.setClickable(true / false)` by themselves.

But the recursive DOM tree process uses the battery power than just monitoring the map div.
(In other words, v2 uses the battery power than v1, if just compare the mechanism)

----
### JS side

As you may know, the JS side executes the DOM tree parse 11 times (first time + 50ms * 4 + 200ms * 6) at least.
![screen shot 2017-07-17 at 4 49 28 pm](https://user-images.githubusercontent.com/167831/28294594-f6c49852-6b0f-11e7-82a7-8a1b1208ec42.png)


The reason of `50ms * 4times` assumes `HTML element is moving`, such as side menu.

In order for the map view follows the map div faster as much as possible, check the DOM tree in short period.

If no changes are occurred in last 200ms, the plugin assumes no HTML elements are moved.
But there are possibility to change HTML elements (such as dialog box are popped up later).
That's why check the DOM tree with 200ms * 6times.

JS side executes `putHtmlElements` of the native side.
----

Let's check out the native side. I wrote both Android and iOS are the same as much as possible.
Variable names, function names are almost the same (not everything).

At this time, I will explain with Android code, but you can follow the code on iOS if you prefer.
 
### native side

The `putHtmlElements` method stores the position, size and depth of all HTML elements into `MyPluginLayout. HTMLNodes` and `MyPluginLayout. HTMLNodeRectFs` variables.
[MyPluginLayout.java / putHtmlElements](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/fd465ffc61c25dfcdc15c574d3f572a11d597f06/src/android/plugin/google/maps/MyPluginLayout.java#L242-L288)

The important thing is 
the `putHtmlElements` method just store the information to variables **ON BACKGROUND THREAD**.

#### UI thread and background thread

In Android and iOS programming, manipulating view must be in **UI(main) thread**, which is the most high priority thread, and there is only one thread in system.

So running code long time  on the UI thread blocks other programs.
When that time, you feel `application is stacked`.

Background thread is not the UI thread, it's just a thread, but the priority is low than UI thread.
The benefit of this is you can run your code longer, and it does not block other code.

The code of v2 uses the background thread as much as possible except small code.

#### positioning of the map view

**Changing map view position must execute the code on the UI thread.**

Since of this, I don't want to execute the code of positioning map views as much as possible.
Running on the UI thread spends lots of battery.

For the reason, the plugin code executes the positioning process as timer (like setInterval).

[MyPluginLayout.java / ResizeTask ](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/fd465ffc61c25dfcdc15c574d3f572a11d597f06/src/android/plugin/google/maps/MyPluginLayout.java#L71-L161)

If I set the timer interval is short value at [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/fd465ffc61c25dfcdc15c574d3f572a11d597f06/src/android/plugin/google/maps/MyPluginLayout.java#L223), the map view moves faster. But that causes lots of battery.

And I tested if I set `10ms` instead of `25ms`, it's not improve significantly.

I tested lots of interval time, and `25ms` is the best. (This is related with `20ms`).

So that's why even if you execute the DOM tree process in short period, the map view does not move smoothly.

#### Inspecting the touch action.

The most difficult part was the touch inspection.

The `onInterceptTouchEvent` method run on the UI thread, but as I described, the execute time of the UI thread must be in short time.

In order to archive that, `the depth` is important again.

Because of [this calculation](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/fd465ffc61c25dfcdc15c574d3f572a11d597f06/www/Common.js#L299-L315), the DOM elements above on the map div(such as header, dialog box ...etc) are going to be higher value than the map div.

So the plugin can omit checking the HTML elements that are DOM depth are lower than map div.
[code](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/MyPluginLayout.java#L541-L543)
```java
if (domInfo.getInt("depth") <= mapDivDepth) {
  continue;
}
```

And if the click position matches any HTML elements, the click action is for HTML. Otherwise, it is for map view.

```java
if (clickPoint.x >= htmlElementRect.left &&
  clickPoint.x <= (htmlElementRect.right) &&
  clickPoint.y >= htmlElementRect.top &&
  clickPoint.y <= htmlElementRect.bottom) {
    isMapAction = false;
    break;
}
```


This is the logic of the v2.

**Comment by wf9a5m75** [comment]
@Hirbod FYI: this is the logic of the plugin v2.

**Comment by stalniy** [comment]
Excellent! Thanks for such informative explanation!

**Comment by wf9a5m75** [comment]
I agree the DOM tree parse process spends battery power, even if I take care as much as possible.

I considered `MutationObserver` couple of times, but I have been really busy, so I haven't tested it deeply yet. If you improve the DOM tree parse performance significantly, I really appreciate for your work, and I will pay some amount for your work.

Please try it, and send a pull request.

-----

I close this issue at this time, because there is no solution at this time.
But you can still reply for this thread anytime.

**Comment by stalniy** [comment]
@wf9a5m75 could you please also explain why do you need a queue for calling native methods? this line of code https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/googlemaps-cdv-plugin.js#L407

**Comment by wf9a5m75** [comment]
Did you check the release notes?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta3/README.md

**Comment by stalniy** [comment]
> This mechanism runs the map.clear() and some other methods as synchronously.

why do you need to run `map.clear()` synchronously?

**Comment by wf9a5m75** [comment]
The most of user (maybe including you) do not know the inside the map.clear().

map.clear() removes the internal caches.
Not only pure map.clear()
It means it takea kind of longer time.

But many people write the code map.addMarker() or map.remove() after very soon of map.clear()

This causes the null pointer error.

The command queue prevent these errors.

**Comment by stalniy** [comment]
Thanks! it makes sense

**Comment by wf9a5m75** [comment]
And control thread numbers prevent the thread execute refuse error especially on Android.

Probably you don't know about that, the thread queue of Java refuses if the thread requests are too much.

So command queue prevents this error also.
