### ISSUE TITLE
When header bar override the map then header click events not working

### ISSUE THREAD

**Issue by ypkkhatri** [mapsplugin/cordova-plugin-googlemaps#1590]
Hi,

Please check the 1st image, when I click on `Next ->` button it's not working, it actually triggers map click event, and (in 2nd image) if I scroll up and map is not overridden then click is working fine

![1](https://user-images.githubusercontent.com/16644003/28614820-8243de4a-7210-11e7-9a86-39a8ac76b1b2.png)
![2](https://user-images.githubusercontent.com/16644003/28614733-44a15a40-7210-11e7-8621-be05a7e1e8a0.png)

Please help me in that

Thank you

**Comment by wf9a5m75** [comment]
What version do you use?

**Comment by wf9a5m75** [comment]
I guess you use old version.

**Comment by ypkkhatri** [comment]
yes I'm using old version because new version is beta and its crashing my app

**Comment by wf9a5m75** [comment]
I don't support old version.

**Comment by wf9a5m75** [comment]
You need to choose stick on the older version or use the latest version and report the crash report.
If you report the crash report with the latest version, I will support it.
If you choose stick on the old version, please close this issue.

Because the latest version already solve the click issues.

**Comment by wf9a5m75** [comment]
ping

**Comment by ypkkhatri** [comment]
Thanks for ping

The way of your support is not good, your new version is not published yet, it's a beta version, and you saying you do not support old version, actually you have to support old one till your new version gets to published, this is the actual way of support. We can't use the beta version on our production release, your plugin is very good that's why everyone is using.

Thank you

**Comment by wf9a5m75** [comment]
Since the plugin version is still in beta, you need to take a risk to follow up the latest version, or choose the one version you feel it is stable.
I offered `If you report the crash report with the latest version, I will support it.`.
But you don't want to. So I can not help you.

Beta version is beta. It means it has some unstable things. Not stable.
The developer for this plugin is currently only I am. But users are a lot.
It is impossible to make stable code for everyone.
That's why I open full source code, and I don't charge any amount.
(Although I asked to donation).

**Your click issue is already fixed**.
But you don't want to use it. Okay, it's your choice. I don't block your choice. But I can not support it.

----

I close this issue. Because it is not issue anymore.

If you change your mind, report the crash information and provide the way to replication, I'm welcome to help you.

**Comment by ypkkhatri** [comment]
I'm sorry but still, I would say your support like this is not good, without releasing the new version you can stop support old this is the standard behavior. 

Anyway, it's your plugin.

Thank you :)

Cheers
