### ISSUE TITLE
How can I hide the Google logo in the map footer?

### ISSUE THREAD

**Issue by alanbasilio** [mapsplugin/cordova-plugin-googlemaps#1596]
**I'm submitting a ...**  (check one with "x")
[x] question
[ ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[x] **1.4.x**
[ ] **2.0.0-beta2**

**Comment by wf9a5m75** [comment]
There is no way to do that, and that is against the Google Maps API Terms of Services.

**Comment by Bengejd** [comment]
While it's against the Google Maps API Terms of Services, it's quite annoying to accidentally tap this logo, and have it pop up saying that 

> "YOUR_APP_NAME" wants to open Google Maps

So to solve this issue, I just added a div that overlaps the logo and makes it so that you can't click it.

The template should look like this:
```
  <div id="map_canvas">
    <div class="over-logo"></div>
</div>
```

Then in your `.scss` file, you should just add something like this:
```
  .over-logo {
    background-color: transparent;
    height: 3.69vh;
    width: 16vw;
    bottom: 0;
    position: absolute;
  }
```

**Comment by kozuch** [comment]
What about when I do not show the Google map but another custom map with TileOverlay? Is this also against the API terms?

**Comment by wf9a5m75** [comment]
Yes, you still against the API terms, because you use Google Maps API throw this plugin.
I recommend you use another plugin or API, such as open street map, if you don't use Google Maps  tile.
