### ISSUE TITLE
How To Trace a Route? Or what's the alternative?

### ISSUE THREAD

**Issue by franzisk** [mapsplugin/cordova-plugin-googlemaps#1602]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ ] any problem or bug report
[x] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170725-1201 "cordova-plugin-googlemaps"
cordova-plugin-nativegeocoder 2.0.2 "NativeGeocoder"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
There is no way to trace a route

**Expected behavior:**
To use somehow the Maps Directions Service

**Steps to reproduce:**
Not available

I am not sure if I am asking this on the wrong place, if so my advanced apologies.

**Comment by wf9a5m75** [comment]
Currently no way is provided. People who wants to use the directions services, use the Google Maps JavaScript API v3 with this plugin.

**Comment by wf9a5m75** [comment]
@franzisk If you help me a lot, I will create the directions services for this plugin.

I have been fixing the ionic wrapper plugin for this plugin (aka, @ionic-native/Google Maps plugin).
Since the wrapper plugin developer is not familiar with this plugin, some code are incorrect.
I would like to fix it.

I checked many times, and I fixed many points.
https://github.com/ionic-team/ionic-native/pull/1834

But it seems there are more incorrect points.
In order to fix all incorrect code, I decided to create a demo application that uses all methods.
https://github.com/mapsplugin/ionic-googlemaps-demo

I just started it today. But because of I'm not familiar with ionic, I spend so much time for just four pages.

So, could you help me to create this project?

------

Since this plugin is open source. Open source should contribute each others.
If you help me, I will help you.

**Comment by franzisk** [comment]
Ok Masashi,

You can count on me to help you, but I might not be able to help all the time because I have work work here and sometimes I am busy.

I will take a look at the project ASAP.

**Comment by wf9a5m75** [comment]
Thanks. Helping each other little by little. (Even me, I have real job though)

**Comment by wf9a5m75** [comment]
Hi @franzisk 
Could you tell me your e-mail address to invite you to slack channel?
(If you don't want to past your e-mail address here, please let me know by e-mail)

**Comment by franzisk** [comment]
Hi @wf9a5m75 

My email: francisco.vieira.souza@gmail.com

**Comment by wf9a5m75** [comment]
Thanks.
