### ISSUE TITLE
Clicks on HTML elements overlaid on map do not work with CSS zoom

### ISSUE THREAD

**Issue by kozuch** [mapsplugin/cordova-plugin-googlemaps#1628]
I need to scale up my mobile application with css zoom (so that the UI is bigger on tablet compared to mobile phone) but I realized when applying CSS "zoom" property to elements that are over my map (inside my map canvas element - like this: `<div id="map_cavas"><my-element></el></div>`) then the onclick on these elements stops working. My guess is that the "native" map window can not handle the zoom proprety. I also get clicks randomly at about half of element surface etc.

Using plugin version 1.4 on Android 5.1 with Apache Cordova.

**Comment by wf9a5m75** [comment]
Did you try the v2?

Basically the plugin does not take care of zoom property

**Comment by kozuch** [comment]
@wf9a5m75 Have not tried v2 yet. Does v2 handle css zoom properly?

**Comment by kozuch** [comment]
@wf9a5m75 How does the plugin detect the overlaid HTML elements? Very strange ONE property type of css does not work while other do...

**Comment by wf9a5m75** [comment]
>  Does v2 handle css zoom properly?

No. But better than v1 for lots of things.

Please(x3) recognizes how this plugin work with browser view at first.
The map view is **NOT** html element.
Completely different view.
In order to display the map view, it is placed **UNDER** the browser view.
![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

So the native side must recognize the position and dimension of the map div correctly.
The zoom property blocks this. Because all dimensions are changed.

That's why the plugin does not allow to use the zoom property (actually changes the viewport settings automatically).
The v1 does not block but it causes lots of error.

If the zoom property is high priority than using this plugin, please stop using this plugin, and use the Google Maps JavaScript API v3.

**Comment by kozuch** [comment]
@wf9a5m75 

Thanks for your reply. I know how the plugin works (native element is placed UNDER HTML canvas). I am not zooming the canvas itself, but only the elements INSIDE the canvas - I simply need to make my buttons for map control bigger. I also apply the zoom BEFORE I initialize the plugin. Also tried to zoom both statically (static css) and dynamically (css applied with JS) but there is no difference.

I am just curious about the way the plugin detects the elements INSIDE the map canvas... The map canvas fills the whole screen for me which is ok (css width/height = 100%), the markers etc. are smaller on tablet than smartphone but I dont mind that for now.

I can work around the zoom issue by scaling my elements manually (custom width/height) but I wanted to avoid this at first by trying zoom.

**Comment by wf9a5m75** [comment]
The v1 checks only the HTML elements that are child element of the map div.
If you change size of the map div, you need to execute `map.refreshLayout()` by yourself.

The v2 recognizes around that automatically.
