### ISSUE TITLE
Map flashes when navigating between pages

### ISSUE THREAD

**Issue by tennist** [mapsplugin/cordova-plugin-googlemaps#1642]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[X] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta2-20170718-1602 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**

> When I navigate away from the map page the next page loads fine.  However, all subsequent page changes result in the map showing up then the page loading on top of it.  I am thinking this is just a css issue.

**Expected behavior:**

> The map should only show when navigating to the page that the map is on.

**Steps to reproduce:**

> My app files are located on git at the following location.  Once you build the app you can use the menu icon in the upper left hand corner to navigate pages.  Navigate to the map page then to the users page, then to the content page.  You will see the map flash when you navigate from the users page to the content page.

https://github.com/tennist/drupalgap-test-map

**Comment by wf9a5m75** [comment]
Please take a screen video.

And you should try the latest version at least before asking.

**Comment by tennist** [comment]
I appologize I had just removed and reinstalled the plugin, but for some reason node.js didn't grab the latest version.  I got the latest version installed and still have the same issue.  A screen video is attached.
[device-2017-08-15-081005.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1225480/device-2017-08-15-081005.zip)

**Comment by wf9a5m75** [comment]
Ah, this is your JS framework problem.

First of all, the map view is not a HTML element. This is a view, and it is placed under the browser (out side of browser).
In order to display the map view, the plugin changes the background of html elements of the map view parents as `transparent`.

![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

It seems the DrupalGap fades out the page div, then fades in to another page div.
But the body element is transparent. That's why the map view is displayed. 
In this case, you need to manage the map view by yourself.

When the enter to the map page, create a map.
And when leave the map page, remove the map.
This is the simple solution.

Otherwise, `map.setDiv(mapDiv/undefined)` is also available.

**Comment by tennist** [comment]
Thank you for all your help on this.  I ended up removing the map when changing page and then adding it back when returning to the page.
