### ISSUE TITLE
Use Semver for releases and bug fixes

### ISSUE THREAD

**Issue by cwoolum** [mapsplugin/cordova-plugin-googlemaps#1654]
Hey Guys,

I was wondering if you guys would be willing to switch to using Semver for versioning? As a consumer of any of the NPM versions, I would not expect them to break after being published. It would be better if any bug fixes also increment the patch version.

**Comment by qasimsoomro** [comment]
+1

**Comment by skyserpent** [comment]
+1

**Comment by wf9a5m75** [comment]
I appreciate you send me the solution not just claiming.

**Comment by wf9a5m75** [comment]
I'm terribly busy. And the v1.4 is dead code for me.

**Comment by cwoolum** [comment]
Sorry, I'm not claiming anything. I'm just asking that if you do push any updates to the 1.4 branch, please rev the patch version so existing consumers are not broken. 

i.e., if another patch is released, it should be 1.4.6 instead of republishing 1.4.5.

**Comment by wf9a5m75** [comment]
I apologize the v1.4.5 was delayed to the npm.
But please move to the v2.0-beta3.

I reviewed your previous issue (#1521).
The problem is you can not catch the map view, correct?

You can attach/detach the map view from the map div.
```
// attach
map.setDiv(element);

// detach
map.setDiv()
```

Detach the map view from the map div keeps the map view. 

I haven't maintenance the master branch code for a while at all (even though it is master).
I really want to replace the code, but I have been tackling with marker cluster. That's why I still keep the two versions.
But almost done. Please move to the v2.

----

You said you can not share your project files. But you can create a dummy project and share it.
I'm not interested in your project at all, but there is a problem in the plugin, I would like to resolve the issue (except the compatibility with other plugins).

**Comment by cwoolum** [comment]
I'll have a short break after this sprint and will try to reintegrate 2.0
again
