### ISSUE TITLE
Error: Failed to fetch plugin

### ISSUE THREAD

**Issue by EvPut** [mapsplugin/cordova-plugin-googlemaps#1657]
**I'm submitting a ...**
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:** (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3**

**Current behavior:**
Today, when I try to add a plugin, I get:
```
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```
In Ionic Package Cloud build application(where the plugin is installed) success, but in .ipa and .apk www/plugins/cordova-plugin-googlemaps not added and application does not work.

**Comment by wf9a5m75** [comment]
Please ask at the ionic forum. This is ionic crould build
 problem.

**Comment by EvPut** [comment]
Local on computer run:
`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="my_key" --variable API_KEY_FOR_IOS="my_key"`
return this error.

**Comment by wf9a5m75** [comment]
please search the past issues... 

https://github.com/mapsplugin/cordova-plugin-googlemaps/search?q=Error%3A+Failed+to+fetch+plugin&type=Issues&utf8=✓

**Comment by wf9a5m75** [comment]
https://forum.ionicframework.com/t/cordova-is-not-a-valid-task-googlemap-native/102693/4

**Comment by leo4444** [comment]
I had the same problem ...
I already had a project on Android developed on Windows 10 and I was now working on Mac for iOS. When I wanted to add the platform (sudo ionic cordova platform add ios) I had this problem ... I tried many things but the problem was that I added "sudo" in the command line. Removing "sudo" gave me permission errors in the platforms / ios directory, so I gave it read / write permissions and ran the command again ...
This was what worked for me, I hope it serves the one who has this problem
