### ISSUE TITLE
Display tiles as base64Strings (allow for offline storage)

### ISSUE THREAD

**Issue by nicholasgcoles** [mapsplugin/cordova-plugin-googlemaps#1670]
**I'm submitting a ...**  (check one with "x")
[x] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[x] **iOS**

**Introduction to issue**
I am trying to dynamically download tiles which are stored on a server, convert them to base64Strings and then store these tiles in my local storage (as base64Strings) so that they can be displayed when offline (phone not connected to wifi or cellphone network).

**Current behavior:**

I am trying to overlay base64Strings as my google maps tiles, however when I try do this then nothing happens. Here is an example of my code:
```
this.map.addTileOverlay({
   getTile: function(x, y, zoom) {
     // some code to extract the base64String from local storage
     return "data:image/png;base64,iVBORw0KG......."
  }, function(tileOverlay){
});
```

**Expected behavior:**

When I return a normal tile url then the map displays the tiles correctly. For example:
```
this.map.addTileOverlay({
   getTile: function(x, y, zoom) {
     // My normal tiles
     return "https://s3.amazonaws.com/bucket/zoom/x/y.png"
  }, function(tileOverlay){
});
```

I tested adding a google maps marker with the base64String as the icon's url and this worked perfectly. For example:
```
this.map.addMarker({
   position: {
     lat: -25,
     lng: 30,
  },
  icon: "data:image/png;base64,iVBORw0KG......."
});
```

**Steps to reproduce:**
To reproduce you can insert any base64String (converter available [here](http://jsfiddle.net/handtrix/YvQ5y/)) to return as a tileUrl instead of the tile url. The reason I have not included any base64Strings is that they are very long in character length.

Is this kind of functionality possible? I know it is possible with the google maps javascript API so perhaps there is something small that I am missing?

I realise that I could temporarily hack this by adding markers as my tiles and working out their exact center positioning to suit the tile etc, but that would not be a good way of going about it I don't think.

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
This plugin can load tile files from local path. Base64 encoded images are not supported.

**Comment by wf9a5m75** [comment]
Store the data to a file, then specify it with `file://` protocol.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/TileOverlay/addTileOverlay.html#L50

**Comment by DanielKemedia** [comment]
Hi, sorry to open this discussion again, but I am doing exactly this (storing images to a file), but it does not work with IOS.

In Android it works fine
In IOS if I read the tiles directly from a http protocol it works fine

Should this work both in IOS and Android?

I really hope you can help because I have being trying for days to get it to work on IOS, while it works perfectly on Android

Thank you in advance

**Comment by wf9a5m75** [comment]
@DanielKemedia Please share your project files (or the project files that reproduce your issue 100%) on github, then share it.

**Comment by DanielKemedia** [comment]
Good morning

Here you can find the file: https://gist.github.com/DanielKemedia/bd8b02a87ba2ed0451e56eca96a07144 <https://gist.github.com/DanielKemedia/bd8b02a87ba2ed0451e56eca96a07144>

Tell me if I must share it somewhere else (it’s my first time using GitHub)

On Android everything works perfectly

On IOS the mostraMappa and mostraPercorso methods work fine (the addTileOverlay method is adding tiles directly from openstreetmaps), but the mostraPercorsoOffline, which is adding tiles from the cache  (cordova.file.cacheDirectory + zoom + "/" + x + "/" + y + ".png”) does not work.

Thank you for your time

Regards



Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by wf9a5m75** [comment]
I said `your project files`, not only the map page code.

Please create a git repository, and put all files to it.

**Comment by wf9a5m75** [comment]
Thank you for sharing your code. Could you also indicate where should I check in your code?

**Comment by DanielKemedia** [comment]
In the folder www/js, the file territorio.js

The method which does not work on IOS is the mostraPercorsoOffline(). It does not show the tiles saved on cache

Thank you again



Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by wf9a5m75** [comment]
Let me clarify the point. Do you mean this code does not work on iOS?
https://github.com/DanielKemedia/app-with-map/blob/master/www/js/territorio.js#L219

**Comment by DanielKemedia** [comment]
Yes, that is correct


Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by wf9a5m75** [comment]
Hi, sorry for delay. But I can't follow the code flow. And also I can't read Italian(?)

Could you take a video, how to reproduce your issue, and put it to Youtube?

**Comment by DanielKemedia** [comment]
Dear Masashi

Sorry for the delay in answering. I am working on other projects at the same time, and I have also being testing on Android.

However I have encountered an other issue, connected to the presence of the google maps plugin: when I try loading the APK to the google play store I get an error message saying that the app is asking for a READ_PHONE_STATE authorization. After several testings I have discovered that it is the google maps plugin that is sending this request. Is there a way to avoid this?! Does the plugin really need this permission?

Once I get the app working and loaded on google play I will then see to the IOS version

Thank you again for your time



Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by battika** [comment]
Hello, it is not the Google Maps plugin itself but Google Play Services.

Here is the bug submitted to Google:
https://issuetracker.google.com/issues/76024034

Fixed in version 12.0.1:
https://developers.google.com/android/guides/releases

> 
Adds missing minSdkVersion in -license artifacts to prevent automatic inclusion of READ_PHONE_STATE and READ_EXTERNAL_STORAGE permission

**Comment by DanielKemedia** [comment]
Hello, thank you for the quick answer

What I do not understand is: if the issue has been fixed why do I keep getting the error? Or is there something I have to update manually?

Sorry for all these questions


Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by wf9a5m75** [comment]
Reinstall the plugin with specify the PLAY_SERVICES_VERSION="12.0.1"

**Comment by DanielKemedia** [comment]
I did this by modifying the code in the plugin.xml file

I change the code from PLAY_SERVICES_VERSION=“12.0.0” to PLAY_SERVICES_VERSION=“12.0.1"

However after I install the plugin, and rebuild the app I continue getting the same message saying that READ_PHONE_STATE permission is required.

Is anything else I must do?


Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by wf9a5m75** [comment]
Even you reinstall the plugin with specified v12.0.1, your app still requested, that is not this plugin.
Because this plugin does not request the permission at all.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2176#issuecomment-375911920

**Comment by DanielKemedia** [comment]
This is very strange.

I tried to build the app without the plugin, and load the APK, and I get no error message, therefore the message must be coming from the plugin somehow. I will continue trying to find a solution…



Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by MikeWoots** [comment]
Hi Guys

I am also having the same issue with storing files on IOS. The addTileOverlay works fine with on Android with local files but not on IOS.

**Comment by DanielKemedia** [comment]
Hello Masashi

I tried several times to rebuild, but I keep getting the same problem

I have updated the play service version as indicated.

You can see the code here: https://github.com/DanielKemedia/cordova-plugin-googlemaps <https://github.com/DanielKemedia/cordova-plugin-googlemaps>

Am I missing out on something?

As mentioned in my previous email I only get the error when I install the google maps plugin. If I remove the plugin I do not get the READ_PHONE_STATE request, so it must be coming from there

I really do hope we find a solution

Regards


Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by DanielKemedia** [comment]
Hello Masashi

By reading on the internet it looks like the problem may be in the AndroidManiest.xml file, in the line 

<uses-sdk android:minSdkVersion="1” />

I tried modifying this file myself, changing it to:
<uses-sdk android:minSdkVersion="19” />

But if I change it myself it I then get an error when I build in monaca, saying that "package za.co.twyst.tbxml does not exist”

Do you think we can resolve this issue?

Regards



Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************

**Comment by DanielKemedia** [comment]
Good news

I was able to modify the AndroidManiest.xml. That was the problem.

I have built the app, and loaded it successfully on Google play console.

You may want to modify it yourself in the plugin, in order to avoid this happening again

The file I modified was in src/android/frameworks/tbxml.android.aar/AndroidManifest.xml

Now I will load the app on IOS, hoping everything works fine

I will let you know if I encounter other issues

Have a nice day


Daniel Wilson

Via Ottava Strada Zona Industriale, 7
95121 Catania (CT)

Tel: +39 095 8362956
Email: daniel.wilson@kemedia.it
Web Site: www.kemedia.it <http://www.kemedia.it/>
Please consider your environmental responsibility before printing this email

***************************************************************************
***************************************************************************
The information contained in this communication is confidential, may be
privileged and is intended for the exclusive use of the above named
addressee(s). If you are not the intended recipient(s), you are expressly
prohibited from copying, distributing, disseminating, or in any other way
using any information contained within this communication. We have taken
precautions to minimise the risk of transmitting software viruses, but we
advise you to carry out your own virus checks on any attachment to this
message. We cannot accept liability for any loss or damage caused by
software viruses. If you have received this communication in error please
contact the sender by telephone or by response via mail.

***************************************************************************
***************************************************************************
