### ISSUE TITLE
Map does not show when navigating inside ionic modal

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1678]
When I open a page from an ionic modal, the map does not show.
The map is created, but it seems like their are some conflicts between the modal and the map CSS.

You can reproduce the issue using the repo: https://github.com/antoine92190/ionic-map

- The app will open on the "About" tab.
- Click on "Open Modal"
- Then click on "Go To Map"
=> The map is not displayed

**Comment by wf9a5m75** [comment]
Do you mean you want to display a map in dialog box?

It's impossible.

**Comment by antoine92190** [comment]
I'm not sure the ionic modal is quiet considered as a dialog box.
I found a workaround to make it work on my main project, but it's really hacky.
I will update the ionic-map project and give you more info about it.

I know it is really specific, so it is really not a big deal if not fixed.
Just though you should know about it.

**Comment by antoine92190** [comment]
I updated the ionic-map repo.
You can try to "Show Map" and "Hide Map" after opening the modal from the "About" tab.

As I said, it works but it is really hacky.
The idea is to hide the ".ion-page" and ".modal-wrapper" classes created by ionic which seems to block the map from being seen.

Let me know if it is something you can support, otherwise I will keep using this hack.

**Comment by wf9a5m75** [comment]
I checked your code, and this is not plugin's bug.
First of all, you need to remember how this plugin works.

The map view, which is a native view, not a HTML element, is placed under the browser view of app.
That's why the plugin need to change the background color of parents of the map div element as transparent.
![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

Your app is constituted like this:

```html
<html>
  <body>
    <ion-app>
       <ion-modal>
            ...
       </ion-modal>
       <page-home>
             <ion-content>
                   <div id="map">
             </ion-content>
        </page-home>
     </ion-app>
  </body>
</html>
```

As you can see, the `<ion-modal>` is not parent element of the `<div id="map">`.
That's why the plugin can not change the background-color as transparent.
(There is no way to detect the purpose of the element)

In that case, the developer needs to manage it even it is `hacky way`.

**Comment by antoine92190** [comment]
I understand, thanks for the clarification!

**Comment by degroundshaker** [comment]
I solved this issue with a css hack

```
openModal(sid){
		let modal = this.modalCtrl.create(MapModal, {id: sid});
		modal.onDidDismiss(() => {
			// Call the method to do whatever in your home.ts
			console.log('Modal closedd');
			this.Opacity = 1;
		});
		modal.present();
		this.Opacity = 0;
  }
```

and in .ts file, declared:

`Opacity: any = 1;`

finally, used it on my <ion-content> like this:

`<ion-content [ngStyle]="{'opacity': Opacity}">`

After, my Map was correctly being displayed in my Modal. 

Let me know if it helps.

**Comment by setu1421** [comment]
@degroundshaker , I tried with your answer but could not load the map in the modal. Can you please check my question [here](https://stackoverflow.com/questions/50016208/how-to-show-native-google-maps-inside-a-modal)

**Comment by setu1421** [comment]
@antoine92190, I checked your repo but could not find your solution. Can you please share with us?
