### ISSUE TITLE
Buttons are not clickable when placed over the map

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1773]
**I'm submitting a ...**  (check one with "x")
[ X ] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ X ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X ] **iOS**

I have set a button over the map; however, it seems that it's not clickable, the button shows over the map but it does not fire. I tried to do `setClickable()` to `false` it worked, but I was not able to move the map, neither zoom-in,etc.....

Is there a way to make it work ?

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by HamzaLJ** [comment]
@wf9a5m75 I can't share the whole project file, however, I can share with you the part where I have the buttons and the map, is that fine ?

**Comment by wf9a5m75** [comment]
I am not interested in your project code at all.
But in order to help you, I need to reproduce your issue at my side.

Your options are: 
1. create a demo project that reproduce your issue 100%, then share it on github, or
2. share your project files on github (or bitbucket ,etc).
3. otherwise, give up to use this plugin.

**Comment by HamzaLJ** [comment]
I'll create a demo that reproduces the issue 100%

**Comment by HamzaLJ** [comment]
I had the button inside a `div` which surprisingly stopped it to make it work ! Anyway, thanks !

**Comment by wf9a5m75** [comment]
This plugin considers the hierarchy of HTML elements.
In order to put HTML elements on the map,
you need to do either:

1. specifying higher z-index than map div
2. or put the html element under the map div.

If you did `1. specifying higher z-index than map div`, but even though it does not work,
you need to share the project files with me.
Because there is a possibility of a bug, or your CSS is wrong.

But you did `2. put the html element under the map div`, it works.
