### ISSUE TITLE
Bug - Black screen showing instead of map (Repo provided)

### ISSUE THREAD

**Issue by HamzaLJ** [mapsplugin/cordova-plugin-googlemaps#1780]
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ X ] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ X ] **iOS**

**Current behavior:**
I have 2 maps in my ionic app, the first one shows when you open the app (which works fine), you click on the button, it will open a modal and it will drive you to `Contact Page` from that page when you click on `Go to About Page` you'll see a black screen where it is supposed to see the map !

**Expected behavior:**
The map should show instead of the black screen.

**Steps to reproduce:**
Please refer to the following : https://Mzzika@bitbucket.org/Mzzika/testmap.git

**Comment by wf9a5m75** [comment]
This is not a bug.  I'm sure you don't understand `How does this plugin work?` section.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work

And did you search the past issues?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1678

------

The first of all, the map view is **NOT** html element. It means the map view is not DOM element.
So the map view is located under the browser, **NOT** in the browser view.

That's why the map view is under the browser, and the browser background color **MUST BE TRANSPARENT**

![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

------

The `<ion-modal>` is a popup window, which means the `<ion-modal>` is located upon the other elements.

This is the structure what happens in your app.
![ion-modal](https://user-images.githubusercontent.com/167831/30930916-048cf2fe-a378-11e7-9c4f-0d9ca1072e93.png)

The reason of the black map is `<div class="fixed-content"/>`.
This element is the background for the modal dialog.
However this element is not parent element of the map div, the plugin does not change the background of this element.
That's why the page is black.

For the evidence, if I change the background as `red`, the app displays `red`.
![screen shot 2017-09-27 at 10 19 39 am](https://user-images.githubusercontent.com/167831/30931040-5d1964c0-a378-11e7-9669-99d3cb8abbc6.png)
![screen shot 2017-09-27 at 10 20 01 am](https://user-images.githubusercontent.com/167831/30931054-62673b96-a378-11e7-8421-b669b75cbd5e.png)

-----

Even if you set `background-color:transparent` for the `<div class="fixed-content"/>` element,
you can not use the map.
Because the `<ion-modal>` is displayed over the `<page-home>`.

The `<page-home>` element keeps the background as `white`, you only see the white page (like regular page).

If you change the background of the `<page-home>`, you will see the two maps you generated.

But, you don't remove the map1, the map2 is displayed upon the map1.
![screen shot 2017-09-27 at 10 23 38 am](https://user-images.githubusercontent.com/167831/30931225-e3af4284-a378-11e7-82a6-b88cf4dcca3b.png)

------

If you handle these `background-color`, `display:none` for the other pages, and remove the previous map, you can use a map in `<ion-modal>`.
Otherwise, you can not use the map.

**Comment by wf9a5m75** [comment]
Since you are CTO, and consultant for several startups, please debug, study as much as possible before reporting as `bug`.

**Comment by HamzaLJ** [comment]
Basically, I guess that's Ionic Team work ! They need to add a fix for it.
Anyways, thanks for the clarifications.
