### ISSUE TITLE
App Crash on iOS 11 while adding a Polyline.

### ISSUE THREAD

**Issue by Farhan7786** [mapsplugin/cordova-plugin-googlemaps#1810]
Hello,

i am using cordova google maps plugin version (plugin.google.maps 1.3.9) in my ionic v1 project.
Everything works perfect in iPhone. In iOS 11 while adding a polyline to the map. App crashes with an exception. 

-[Polyline initWithWebView:]: unrecognized selector sent to instance 0x1c012fe60
[3010:1433468] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Polyline initWithWebView:]: unrecognized selector sent to instance 0x1c012fe60'
*** First throw call stack:
(0x18520fd38 0x184724528 0x18521d1f8 0x1852156e4 0x1850fb0dc 0x1030bf0d0 0x10431149c 0x10431145c 0x10431d56c 0x104322b54 0x104322880 0x184e3b130 0x184e3ac30)
libc++abi.dylib: terminating with uncaught exception of type NSException

Cordova Version 6.5.0
Google Map Plugin version 1.3.9

the main problem with me is that i cannot update the plugin and platform.

**Comment by wf9a5m75** [comment]
No more support for v1.x

**Comment by Farhan7786** [comment]
No worries and thanks for the google maps plugin.
 Special thanks to @fogfish and @gitoplasm. 
[1766](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1766#issuecomment-333643556) this solved my problem.

**Comment by wf9a5m75** [comment]
You can stay at the v1.x, but the v1.x is similar like windows 95 for me (that means it is too old).

**Comment by gitoplasm** [comment]
Glad that got it fixed @Farhan7786. Just wanted to take this opportunity to request kml support in version 2 which I know other people have requested. This feature is a requirement for the app I was working on plus anyone else who had this polyline problem which arises in kml processing. My first attempt to fix this problem introduced by iOS 11 was to upgrade to version 2, but that broke the kml feature. I gather this poses a significant technical challenge or else it would be fixed by now in version 2 and people are volunteering their time for this, so I don't take that for granted. Thanks for your help.
