### ISSUE TITLE
Add multiple markers

### ISSUE THREAD

**Issue by Abdelazziz** [mapsplugin/cordova-plugin-googlemaps#1856]
Hi every one
I want to implement multiple marker on map , how i can do it, please any help or doc.

**Comment by wf9a5m75** [comment]
@TGMorais That's not perfect idea. Because `map.addMarker()` works asynchronously.

That's why the plugin provides this way.

```js
const locations = [
  {
    position: {lat: ..., lng: ..},
    myData: "hello"
  },

  {
    position: {lat: ..., lng: ..},
    myData: "world"
  }
];

var baseArray = new plugin.google.maps.BaseArrayClass(locations);
baseArray.map(function(locationData, callback) {
  map.addMarker(locationData,  callback);
}, function(markers) {
  // variable `markers` contains two marker instances
  console.log(markers[0].get("myData"));
});
```

--------

If @Abdelazziz uses `@ionic-native/google-maps` (you should indicate which one, JS or ionic),
you can do like this

```TypeScript
const locations: MarkerOptions[] = [
  {
    position: {lat: ..., lng: ..},
    title: "hello"
  },

  {
    position: {lat: ..., lng: ..},
    title: "world"
  }
];

let baseArray: BaseArrayClass<MarkerOptions> = new BaseArrayClass<MarkerOptions>(locations);
baseArray.mapAsync((mOption: MarkerOptions, callback: (marker: Marker) => void) => {
  this.map.addMarker(mOption).then(callback);
}).then((markers: Marker[]) => {
  console.log(markers);
});
``` 

Unfortunately, the `@ionic-native/google-maps` wrapper does not allow own option for `addMarker()` (you can do later using `set()` and `get()` methods)

**Comment by TGMorais** [comment]
@wf9a5m75 
Thanks for the tip!
I was looking around the documentation, but I only found examples of multiple markers being added in a loop.

I change my own code to use `BaseArrayClass` and it's works better indeed. Specially on `ios`.
👍
