### ISSUE TITLE
Feature Request : Marker Label & Map View bounds

### ISSUE THREAD

**Issue by mrezzaaa** [mapsplugin/cordova-plugin-googlemaps#1872]
Hi developer , 

- I think marker label isn't available in current plugin . can you add this feature . ? this feature will great when we load and render many marker on map

- Camera view based on circle or line or poly auto zoom level  , can you add this feature ? 

- And marker infowindow will be great if accepting html . When i use HtmlInfoWindow i think is not actually marker info window.just load info window at a same position with marker coordinate.
i've tried using canvas to adding image into markerOptions.title but image & text loaded on canvas is bad quality.Also when adding listener, some events not work.So i think when we using full html element will be more customizable and more functional.

Sorry for requesting using issue , i'm new on github . and i don't know how to feedback your great works :D

**Comment by wf9a5m75** [comment]
That's not feature request at all.

Regular infoWindoe accepts base64 encoded strings. You don't need to embed canvas at all.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#base64-encoded-icon

And HTMLInfoWindow displays just YOUR html.
But quality? It's YOUR problem.

If you have some problems with your code, please share YOUR project files on github. I can help you.

**Comment by wf9a5m75** [comment]
>Camera view based on circle or line or poly auto zoom level , can you add this feature ?

```js
map.animateCamera({
  target: [
    latLng1,
    latLng2,
    latLng3
  ]
});
```

**Comment by mrezzaaa** [comment]
@wf9a5m75 no, i don't have problem . Just giving suggestion to our source(gmaps-plugin) to more easier and more capability.
In my concept i just wanna show infowindow with thumbnail image and text inside ,  but when i try using canvas , image is ok, but text is not good . So i just using text , no thumbnails.

For camera view , i've tries your way. Just error i got. Just leaving zoom out feature based on circle radius. Let my user manually zoom using gesture/button .

**Comment by mrezzaaa** [comment]
@wf9a5m75 How about marker label ? So we have label on marker and details on infowindow ?

**Comment by wf9a5m75** [comment]
> Marker label

Use base64 encoded strings for icon property.

> Thumbnail and text

Use base64 encoded strings for title property.

> zoom out with circle radius

You need to calculate the positions of circle edges.
See this demo.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/utilities/geometry/spherical/computeDistanceBetween/README.md

> Just giving suggestions? 

Did you consider the idiom of  **time is money**?

I'm not sure your student or worker, but this idiom is important anytime for everyone.
You ask me to create the features to use this plugin easily (on your way).
It means you are trying to spend my private time to implement the features.
(Did you notice about this?)

I'm professional sofeware engineer. So who will pay money for my work in my private time?
Do you pay $1,000 USD? If so, I will implement the features you are requesting.

I ask everyone who ask new features.
For example, HTMLInfoWindow and MarkerCluster are sponsered features.
Will you pay the amount? That's different talk. Otherwise, you just request new features, that there are alternative ways.

This plugin is full open source code, so you can use the plugin as free.
But it is not equal with you have the rights to ask new features as free.

Did you consider to implement the features by yourself?
If you archive that, you can send your code as a full request. Then merge it.

Important thing is contribution with each other.
That's the calture of open source community.

**Comment by mrezzaaa** [comment]
Sorry sir , i'm not mean to bothering you .🙏
I'm just student who love learn new thing .
I know you are professionals. But i'm not yet .
 
I will contribute when i have a lot of experience.
But need a long time. I just learn by myself. No one teaching me . 

I will donate to your community if i have a job later. Your community is great. 

I'm sorry sir , please forgive me .
I'm just teenage and doesn't know about "how community work" because i'm not yet join to any community. Just using youtube and browse a tutorial .
Once again, I'm sorry sir 🙏.

**Comment by wf9a5m75** [comment]
So I have no plan to accept your feature request so far, but I will help you if you have problems with I suggested way (such as image is not clear in regular inforwindow).

In order to reproduce the issues, please share your project files on GitHub (or other git repository services).

If you don't have any problems, please close this thread.
Then you can create another issue if you have another problem in the future.
At least, I will help you if you ask me your problems with enough information.
