### ISSUE TITLE
Native Infowindow VS HTMLInfoWindow

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1899]
**I'm submitting a ...**  (check one with "x")
[ X] question
[ ] any problem or bug report
[X ] feature request

Currently for what i've seen the native infowindow offers very little ( althought i might have missed it) personalization.  In the meanwhile, the HTMLinfowindow seems to be built via html (is it a div?) and has some weird map pan issues ( doesn't follow the marker all the time).

could the infowindow via HTML render instead inside a HTML? or, could we provide in some way a layout XML + class definition (json? java? properties?) given a standard for the infowindow content?
if testing this stuff is too much burden,  and If i personally made some progress on making an infowindow render a Webview content on it, even if it had some size restrictions for content, could you consider a switch to it or adding it? for the ios side it seems it's easier, set up a transparent view and then adding a webview as subview (that's how most custom IOS infowindows are done), but i have no experience on that.

**Comment by wf9a5m75** [comment]
>could the infowindow via HTML render instead inside a HTML

no

**Comment by wf9a5m75** [comment]
First of all, you need to recognize the native Google Maps APIs use OpenGL.
OpenGL can handle only graphics. That's why all views are convert to bitmap Google Maps API internal.
That's why you can not display any HTMLs in the infoWindow.

If you want to just display images and text, you can pass base64 encoded string for the `title` and the `icon` properties.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Marker/README.md#base64-encoded-icon
