### ISSUE TITLE
Map HTML Element Moves on Scroll or When Navigating between pages

### ISSUE THREAD

**Issue by mino922** [mapsplugin/cordova-plugin-googlemaps#1901]
**I'm submitting a ...**  (check one with "x")
[] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
om.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.8.5 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 1.7.0 "Advanced HTTP plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.0-beta-20171027-0054 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When I scroll on my page that contains the map, the entire map div moves and pushes my other HTML elements out of the way. Also, when I change pages and then come back to the page containing the map the map delays and causes a drag effect.

**Expected behavior:**
The map should stay fixed when scrolling or changing pages and not push other elements out of position.

**Screen capture or video record:**
[Recording](https://github.com/svarughese91/GoogleMap/blob/master/mapMoving.mov)

[Git Rep](https://github.com/svarughese91/GoogleMap)

**This repo should be shared with you @wf9a5m75, please let me know if you have issues accessing it. **

**Comment by wf9a5m75** [comment]
I see. I will check this. Thank you for sharing your repo in advance.

By the way, `cordova-plugin-googlemaps 2.1.0-beta-20171027-0054` is kind of older code. Please try to reinstall the plugin from the multiple_maps branch.

**Comment by mino922** [comment]
Thank you @wf9a5m75!

**Comment by wf9a5m75** [comment]
I saw the video.
I guess adjust your css solve this problem.

```css
#map {
    width: 100%;
    position: fixed;
    left: 0;
    top: ...px;
    width: 100%;
    height: 200px;
}
```

Because the plugin follows the div position. The map div moves because of the page scrolling.

**Comment by mino922** [comment]
I'm having trouble getting this to work. When I set the position to fixed the other HTML elements on the page overlap the map. 

Any other ideas?

**Comment by wf9a5m75** [comment]
There is no solution.

Remember, the native map view is not HTML element. That's why the plugin sends the position and size information to native side periodically. That's why the map is delayed.

Currently there is no solution about this, and this is not bug.

I recommend you fix the map, and scroll the bottom parts only.

**Comment by wf9a5m75** [comment]
Another reason of this delay is the ionic framework uses `-webkit-overflow-scrolling: touch` style for the `scroll-content` css.

The browser scrolls the DOM element on GPU, it moves smoothly.
However `scroll` event is not fired during movement.
That's why the plugin can not get the div position.

You can disable the style with  `-webkit-overflow-scrolling: auto`

**Comment by wf9a5m75** [comment]
I maybe have new update for you in today. Hold on please

**Comment by mino922** [comment]
Great, thank you so much!

**Comment by wf9a5m75** [comment]
I had tackled to improve the DOM inspection last 3 weeks.
And I was able to archive to do that today.
(You are lucky, good timinig)

In order to use this dev version, you need to install the plugin from the multiple_maps branch.
I also fixed your code a lot. 
https://github.com/svarughese91/GoogleMap/compare/1901_fixed

I push the code to the `1901_fixed` branch.
Please follow the steps.

```
$> git clone https://github.com/svarughese91/GoogleMap

$> git checkout 1901_fixed

$> git pull

$> rm -rf node_modules

$> npm install

$> ionic cordova run ios
```


![1901](https://user-images.githubusercontent.com/167831/33041180-5326fc4e-cdf2-11e7-8a7d-2e3e1f99120d.gif)

**Comment by mino922** [comment]
Thank you!! I'll update you once we get these changes rolled into our app.

**Comment by labhollow** [comment]
Thank you! I was having the same issue.

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch

**Comment by wilfredonoyola** [comment]
I have tried install with this on ionic 
`ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps  --variable API_KEY_FOR_ANDROID="xx" --variable API_KEY_FOR_IOS="xx"`

 is it correct?

Thanks!

**Comment by davidgod93** [comment]
Is this branch merged?
Is estable?
I have the same behaviour that wf9a5m75 reports. My map is shaking every time I scroll.
Is there any solution?
Thanks!

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch

**Comment by davidgod93** [comment]
But, I intend to publish a production app and I don't think that using a develop branch will be the best option.
Do you have in mind merge this functionality to a stable branch?
How will be the behaviour of this branch with other functionalities?
What do you think?

**Comment by wf9a5m75** [comment]
Test the code, and decide which branch is the best for you by yourself. That's open source.

**Comment by davidgod93** [comment]
Ok. Thanks a lot!!

**Comment by mvvferrari** [comment]
I didn't see the recording because return error 404...but reading the description looks similar my problem...
I resolved inserting div with map between a ion-item tag

**Comment by rodrigosoareschaves** [comment]
I worked trying to solve this issue more time than I thought.
I'm not using ionic on this project, the solution for me was handle the setClickable function:
`map.setClickable(false);`
On my app, the page loaded is in front of the map, that I keep running. When the user tries to scroll down the page it was changing the map camera target instead of the scroll down.
It worked fine after I used the setClickable to false.

**Comment by MalikRizwanAwan** [comment]
> I had tackled to improve the DOM inspection last 3 weeks.
> And I was able to archive to do that today.
> (You are lucky, good timinig)
> 
> In order to use this dev version, you need to install the plugin from the multiple_maps branch.
> I also fixed your code a lot.
> https://github.com/svarughese91/GoogleMap/compare/1901_fixed
> 
> I push the code to the `1901_fixed` branch.
> Please follow the steps.
> 
> ```
> $> git clone https://github.com/svarughese91/GoogleMap
> 
> $> git checkout 1901_fixed
> 
> $> git pull
> 
> $> rm -rf node_modules
> 
> $> npm install
> 
> $> ionic cordova run ios
> ```
> 
> ![1901](https://user-images.githubusercontent.com/167831/33041180-5326fc4e-cdf2-11e7-8a7d-2e3e1f99120d.gif)

what is username and password of repo because i am not able to open it ask me user name and password
