### ISSUE TITLE
HTML Elements Become Not Clickable- Multiple Maps Branch

### ISSUE THREAD

**Issue by labhollow** [mapsplugin/cordova-plugin-googlemaps#1927]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[X ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20171122-2100 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

"@ionic-native/core": "^4.3.3",
"@ionic-native/google-maps": "^4.3.3",
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
In my app, I have an HTML card that slides up after clicking on a map marker. I have attached the swipe-up and swipe-down listener events to the card. When I swipe the html card up it works, but when I try and swipe it down, the html is not clickable and map below moves. I'm not sure if this is a bug or edge case with the way I am showing the div and how getBoundingClientRect() works.

**Expected behavior:**
HTML should be clickable.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
I have created a repo and have given you access. Let me know if you need anything else.

Repo: https://github.com/labhollow/claim-explorer

**Comment by wf9a5m75** [comment]
I run your project, but I can not see the HTML card

**Comment by wf9a5m75** [comment]
home.ts
```
        this.claimsProvider.getClaims(this.mapViewport).subscribe(
          data => {
            console.log(data);  <--- un-reached
```

**Comment by labhollow** [comment]
Sorry, if you long_click on the map once it's loaded, the markers will show.

**Comment by wf9a5m75** [comment]
Oops, I misunderstood your code. You are right.

**Comment by wf9a5m75** [comment]
Please reinstall the plugin from the multiple_maps branch.

**Comment by labhollow** [comment]
Work perfectly now. Thank you for such a quick response and resolution!

**Comment by aMUSiC** [comment]
I'm having the same issue, even after updating to the latest multiple_maps version.
If I have any dom elements that are outside the view (such as with translate3d(100%,0,0) ), and then I move them into view over the map (translate3d(0,0,0) ), then they do not receive any touch events, and the map receives them instead.

Same thing if I use ngIf in angular on the element without any transitions.

Is there any way to instruct the map to recalculate its visible area so I can do that after I move elements in and out of the view?

**Comment by aMUSiC** [comment]
I'm sorry that I keep posting on closed tickets, but while moving elements over the map now correctly get touch events, when I move them away from the map, the map no longer receives the touch events. Again this only happens on iOS. On Android it works fine.

The element that I moved over the map, covered the map entirely.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by aMUSiC** [comment]
I'm afraid that I cannot do that as the source code is protected under an NDA, however I found out why it's not working. I'll try to describe it as best as I can:

There is the map div at the bottom, absolutely positioned at left 0, top 84px. There is also another div, absolutely positioned at the same left/top as the map, with a higher z-index than the map, but it's height is 0. The map works fine and receives all of the touch events.

If I animate the height of the div on top of the map, so that it is equal to the map height using css transitions, the top div will cover the map and correctly receives the touches instead of the map.

Now if I hide the div by animating its height back to 0, then the map will not receive touches (except for a very small portion, about 84 pixels high at the bottom).

Now, if I show/hide the top div by animating its position using 3d translations (i.e. translate3d(0,100%,0) -> translate3d(0,0,0) and then again translate3d(0,100%,0) ) then both the map and the div touches work perfectly.

So I guess that once I change the height of the div element on top from 0 to calc(100%-84), in the dom it retains its placeholder height, even if I set its height to 0.

Not sure if there is anything that can be done on the map plugin to rectify that or if it's just how the dom works, but for the moment I've found a workaround by using a different type of transition.

**Comment by wf9a5m75** [comment]
Sorry, I don't play with quiz. No contribution, no help.

**Comment by aMUSiC** [comment]
I don't understand what you mean exactly by "play with quiz". I tried to describe my findings as best as I can, since I am legally not allowed to share the project's code.

As for contribution, I'm both trying to contribute in the project's well being by identifying issues to problems I've already found workarounds for, and by donating money to assist in the development of the plugin. (coming from Split Infinity Radio, but also included my github username in the message).

**Comment by wf9a5m75** [comment]
Since you don't provide any example project files, I can not reproduce your issue.

You can use this plugin as free because the code is full open, but support is not free. You spend my private time.

`Time is money`.

So, I don't try to reproduce your issue without any example project files, because it is difficult, and spend much time.
But you hide your code. This is quiz. 

You ask me "I hide my code, but I give you hints. Please solve this." 

I have no enough time.

**Comment by wf9a5m75** [comment]
So, if you create a demo project that reproduce your issue 100%, and share it on github, I will check it without any payment.

**Comment by wf9a5m75** [comment]
I updated the code for another issue, but it might help your problem. Please reinstall the plugin from the multiple_maps branch.
