### ISSUE TITLE
Interact with phonegap-plugin-push

### ISSUE THREAD

**Issue by macdonst** [mapsplugin/cordova-plugin-googlemaps#1937]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
phonegap-plugin-push 2.1.1 "PushPlugin"
```

**Current behavior:**
A problem occurred evaluating root project 'android'.

> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
> For input string: "+"

**Expected behavior:**
That the build does not fail

**Screen capture or video record:**
N/A

**Related code, data or error log (please format your code or data):**

Related issue on push plugin repo: https://github.com/phonegap/phonegap-plugin-push/issues/2086

**Comment by wf9a5m75** [comment]
I don't support the compatibility with other plugins.

**Comment by macdonst** [comment]
@wf9a5m75 so you are not interested in having two of the most popular Cordova plugins working together?

**Comment by wf9a5m75** [comment]
no.

**Comment by wf9a5m75** [comment]
For example, the current latest version of Google Play Services is `11.6.0`, but you still specify `<preference name="FCM_VERSION" default="11.0.1"/>`.

So, if I implement new feature `OnMyLocationClickListener` in `11.4.0`, but because of specifying the version number, the user get build errors, then they claim to me (because the most JS developer does not have knowledges of native side).

Also another plugin developers claim to me for version conflict.
It's really stressful. There was the same situation in the past. 

That's why I specify only `+`. If the people who want to specify the version number, they folk this repo or modify the plugin.xml in their local. That's enough.

**Comment by macdonst** [comment]
@wf9a5m75 yes and there is nothing that prevents you from bumping that version when you use a new feature that requires an updated version of Play Services.

With regards to other developers pointing to you as the problem I would be happy to send them PR's on their repos to fix those issues as well. 

Going forward as more and more plugins use Play Services and FCM we are going to run into version conflict problems and by giving the user the ability to have these versions match I'm hoping to head off the issue.

**Comment by wf9a5m75** [comment]
I think this problem should solve by Apache Cordova itself.

**Comment by macdonst** [comment]
@wf9a5m75 yes and this is how we solved it. The ability to specify variable in the framework tag is a recent addition to Cordova. I'm a long time maintainer of Apache Cordova.

**Comment by wf9a5m75** [comment]
>The ability to specify variable in the framework tag is a recent addition to Cordova

Please tell me the source of this information.

**Comment by macdonst** [comment]
@wf9a5m75 well there is the issue:

https://issues.apache.org/jira/browse/CB-13145

and the blog post:

http://cordova.apache.org/news/2017/09/05/cordova-common-2.1.0.html

So any lib using cordova-common 2.1.0 or greater has the ability, which includes cordova-android 6.3.0 and greater:

https://github.com/apache/cordova-android/blob/6.3.0/package.json

**Comment by wf9a5m75** [comment]
Thank you, I read it.
So here is the question, if the plugin A defines `<preference name="PLAY_SERVICES_VERSION" default="11.0.1"/>` in the plugin.xml, and the plugin B defines `<preference name="PLAY_SERVICES_VERSION" default="11.6.0"/>` , what would be occurred?

**Comment by wf9a5m75** [comment]
ping

**Comment by macdonst** [comment]
@wf9a5m75 yeah, even I sleep sometimes 😄 

To answer the question: 
> if the plugin A defines `<preference name="PLAY_SERVICES_VERSION" default="11.0.1"/>` in the plugin.xml, and the plugin B defines `<preference name="PLAY_SERVICES_VERSION" default="11.6.0"/>` , what would be occurred?

initially the build would fail. 

The fix however is to go into config.xml and over-ride the PLAY_SERVICES_VERSION so that the plugin's match. For instance:

```
    <plugin name="phonegap-plugin-push">
        <variable name="FCM_VERSION" value="11.6.0" />
    </plugin>
    <plugin name="cordova-admob-sdk">
        <variable name="PLAY_SERVICES_VERSION" value="11.6.0" />
    </plugin>
    <plugin name="cordova-plugin-googlemaps">
        <variable name="API_KEY_FOR_ANDROID" value="xxxxx" />
        <variable name="API_KEY_FOR_IOS" value="xxxxx" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Show your location on the map" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Trace your location on the map" />
        <variable name="PLAY_SERVICES_VERSION" value="11.6.0" />
    </plugin>
```

**Comment by wf9a5m75** [comment]
Do you believe all cordova users understand `PLAY_SERVICES_VERSION` is the same as `FCM_VERSION`?
And which version is correct?
They don't have knowledge about the native side.

If all plugin developers just specify `+` instead of particular version, or Apache Cordova build mechanism ignores the version numbers, there is no problem at all.

Or apache cordova itself provides the Google Play Services in the `cordova-android`.

I don't believe JS users can specify correct numbers.

**Comment by wf9a5m75** [comment]
If this plugin still specify `+`, but your plugin specify `11.4.0`, Gradle uses `11.4.0` to this plugin.
What is the problem?

**Comment by wf9a5m75** [comment]
I considered deeply about this, but I don't think that giving the ability to specify the version of the Google Play Services is a good thing for JS users. The most of all cordova users don't know the native side (at least very a few people that understand the native side of this plugin).
The people who understand the native side do not use the apache cordova in general.

And I also need to update npm everytime when I update the Google Play Services.
This is really stressful.

**Comment by macdonst** [comment]
@wf9a5m75 the problem is that any plugin that relies on the GoogleServicesPlugin gradle plugin to process the google-services.json file like my push plugin or any plugin that provides FCM capabilities will fail when it encounters the `+`. That is the reason why we want to give users the ability to specify what version of Google Services to use so their builds do not fail.

Not trying to change your mind, just wanted to answer your question. I took the weekend off.

**Comment by wf9a5m75** [comment]
I found a good solution for this. 

I **don't want to ** stick on a particular version, but the latest version is preferred. However I don't update frequently, and I don't want to specify the older version from user side or from other plugin.

What I need is **the way to specify the minimum version** for this plugin without hook scripts, or something like that (because some cloud build systems do not support it).

I found the answer in the `cordova-android` library. Actually they implemented in their library obscurely.
https://github.com/apache/cordova-android/blob/673a6773b2f78ba76d2144c66ab7a3add78648ae/bin/templates/cordova/lib/builders/StudioBuilder.js#L177-L201

This code allows us to specify the minimum version in this way.

```xml
<framework src="com.google.android.gms:play-services:+" versions=">=11.8.0" />
```

So the plugin A requires at least 11.6.0, the plugin B requires at least 11.8.0, then cordova installs the v11.8.0 when user build.
(I tested this)
