### ISSUE TITLE
Can not touch the map with the maps plugin v2.2.2

### ISSUE THREAD

**Issue by cklinx** [mapsplugin/cordova-plugin-googlemaps#2045]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
With 2.0.0 version everything works fine. Latest versions not working as well on phonegap build.
Map loads correctly but cant do anything with touch (rotate maps, touch on poi, ect)

**Expected behavior:**
Latest versions should work like the 2.0.0

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
ping

**Comment by cklinx** [comment]
I'm using Vuejs with Quasar Framework and phonegap build. 

Is enough that i change this line in my config.xml
`<plugin name="cordova-plugin-googlemaps" spec="2.0.0">`

with a bigger spec ex.
`<plugin name="cordova-plugin-googlemaps" spec="2.2.2">`

the map freezes and i cant do anything with touch.

I will try to share the code.

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files. Otherwise, please debug by yourself

**Comment by cklinx** [comment]
Here the code: [google maps project](https://github.com/cklinx/test)

the component that i use is "test/src/components/GeoGoogleMapsCordova.vue"

When i use this code with the version 2.0.0 in my config.xml everything works.

**Comment by wf9a5m75** [comment]
Thank you for sharing, but it seems you don't include the config.xml file

**Comment by cklinx** [comment]
Share the config.xml also!

**Comment by wf9a5m75** [comment]
Thank you for sharing. Could you tell me how to build and run your project? I'm not familiar with `Quasar Framework`

**Comment by cklinx** [comment]
Sure,
after install [quasar](http://quasar-framework.org/guide/) in the root project just give `quasar build` it will create a "dist" folder with compiled files inside. 
Those files must be included in 'www' phonegap folder with this structure:

- www (inside the compiled files)
- config.xml

zip everything and load on phonegap build site.

**Comment by wf9a5m75** [comment]
Ok, I finally figured out the reason.

First of all, the `v2.0.0` and `v2.2.2` are completely different softwares.
So comparing each others are non-sense.

In the `v2.2.2`, the touch recognition complies with the CSS rules perfectly(I believe so), such as `z-index` and  `overflow` rules.
In your app, the parent element of the map div has `overflow: hidden`, and the element height is `0`.

![screen shot 2018-02-05 at 6 01 33 pm](https://user-images.githubusercontent.com/167831/35838247-41c3824e-0a9f-11e8-91e7-253f63303d9a.png)

<img src="https://user-images.githubusercontent.com/167831/35838296-7a906be6-0a9f-11e8-932e-353dd2fb4788.png" width="250">
(you can click the images)

That's why the map div(`<div id="map_canvas">`) can not receive the touch event, thus, you can not touch the map.

**Comment by cklinx** [comment]
Thanks man! Was my code fault.

**Comment by wf9a5m75** [comment]
You are welcome.

By the way, I appreciate if you support for this project. 
**This is not mandatory asking**, but I appreciate if you donate some tip because I spend my private time.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
