### ISSUE TITLE
webview html dom parse - suggestion - feature request

### ISSUE THREAD

**Issue by fssrepository** [mapsplugin/cordova-plugin-googlemaps#2144]
Yesterday i was able to integrate the cordova google map plugin in my system and it is working on ios also.

I think there is some problem with a documentation, as google search throws me the older version of the documents, i think it needs to be updated also, whether something is deprecated or not.

There were some confusions around MarkerCluster, as the real google map is adding real marker objects, not loading from a json. However i think the main problem is the differences between this plugin and the google map javascript api.

I saw that you are doing some dom parse, i'm not critisizing the way how it's done, but i would like to make a suggestion. That's the only plugin which maintained very well, and i think you have made a very impressive job after all, however you can make some easy cleanup, like using interfaces ConcurrentMap, when you define a variable instead of ConcurrentHashMap - there was a bug reported about it some days before. (virtual method keySet does not exist or something similar)

## Ok, go back to my issue:
1, I think when you call the "putHtmlElements" it would be nicer if you call it just once instead for every nodes. I would like to mention react framework and the virtual dom.

Virtual dom is some sort of cache so you update the html tags and it will diff the virtual dom tree and just apply the diffs on the dom. I think you need to save all the html elements at once and pass further. (by call putHtmlElements once)

2, I have an additional problem:
I have made some sort of ui framework based on angular. I have used ionic, but i didn't like it because of the bugs never being fixed, too many tweakings, css bloatware etc.

This plugin is killing the purpose of angular. The main concept behind is that you don't really manipulate the dom, just once. Even you don't access to the dom, as it's a javascript binding call, and it cost a lot as an external call.

Switching between tabs in ionic on really heavy elements causing frustrating delays, so in my framework instead of using display none, i'm using z-index and the elements just simply hiding each other.

But, even if i set display none, this plugin is parsing the whole body, making unnecessary calculations on divs which hasn't been seen on the screen.

To set "_pgm" classes is a real dom manipulation, in my case you set it 100 times i think, and call the "putHtmlElements" 31 times, although on my screen you should parse only 2 divs.

My feature request would be, what if you specify something in the doc, so i explicitly define my 2 divs, which needs to be checked (i personally think that would be the right way to do this thing, and it would make both world easier - the developers job and your job and it would make far more efficient, as you at the moment makes 50 independent dom manipualtion at least on my side, so what is the catch after all to use angular using your plugin)? Other thing would be, if i can just define the container element size, and you wouldn't go to the child elements. Unluckily in my case it can happen that the child element is bigger than the parent element. I have my own implementation of virtual scroll, which contains translateX, so you wouldn't know that position on the screen.

It's just a proposal to make things more efficient:
I know why this plugin is so complicated because it would like to take over the responsibility of the browser. I would look at inferno library as a virtual dom library to help myself on efficiency. (it's a very lightweight library can be easily parsed on source code level and makes fast virtual dom diffs) So instead of making periodic calls, you might grab the virtual dom diff code and just apply/send changes on the android/ios backend when it's needed.

The Virtual Dom Technic would be very unefficient (O^3), if they didn't make any assumption. So they reduced the cost to (n log n).

**Comment by wf9a5m75** [comment]
You misunderstand couple of things.

First of all, this plugin does NOT use the google maps JavaScript api v3.

`putHtmlElements` creates internal cache, and reuse it as much as possible. 

I guess you use very older version.

**Comment by wf9a5m75** [comment]
As far as I read your comment, you don't misunderstand many things or you use very older version.

At the 2.2.7, this plugin DOES NOT parse whole html elements.

I didn't ask you to use this plugin. Do if you don't like this plugin, please use other alternatives, such as MapBox.

**Comment by wf9a5m75** [comment]
If your framework has problems with this plugin, please share your project files on GitHub. I will check it.

**Comment by fssrepository** [comment]
1, You misunderstood this one completely:
You misunderstand couple of things.
First of all, this plugin does NOT use the google maps JavaScript api v3.

I have told that when i have implemented the javascript version using JavaScript api v3 and i would have liked to port to ios and android with your plugin, and there are interface differences, which was a little bit confusing, but does not matter. (it's just mentioned)

2, i have debugged it and saw with my own eyes putting breakpoints to the right place, but please look at my html dom tree - everywhere you set pmg something - and you pass it to the underlying android separately:
![image](https://user-images.githubusercontent.com/33239584/37410094-11bad5ca-27a0-11e8-9623-0c98c2aa761c.png)

**Comment by wf9a5m75** [comment]
>You know that every project cannot be shared in the world

No contribution, no help. That's all.
Everyone share their project on public or private repository.

**Comment by wf9a5m75** [comment]
> but i thought that your classes will be similar to the Google one. It's matching partially but not totally. Because of this, i had to reimplement my integration code for javascript, and spent 10 hours to integrate and properly test my functionality, instead of 10-20 minutes.

I designed this plugin to similar with Google Maps JS API v3.
And there are tons of documentation at here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

You should read the documentation before using.

-----(from here)-------

> Dom parsing

What a small DOM tree. Ionic has terrible bigger than yours.

In order to detect touch position correctly, the plugin needs to check DOM position and size when the plugin needs to know them.

The below is explain I replied to another person before. 

------
This is the DOM tree of ionic project.

![screen shot 2018-02-23 at 11 24 30 am](https://user-images.githubusercontent.com/167831/36612884-b51ed0fe-188c-11e8-9fae-55df55126872.png)

From JS side to the native side, send these information (DOM position, size and some CSS properties, etc). `pgm994053879960` is `<page-home>` element.
![screen shot 2018-02-23 at 11 30 40 am](https://user-images.githubusercontent.com/167831/36613604-e2ef86ac-188e-11e8-9cea-343b692a93f7.png)


When you open the second page,
although the DOM elements in the first page keeps the `__plugindomid` attributes, these elements are not checked, because `<page-home>` is `display: none`.
![screen shot 2018-02-23 at 11 32 28 am](https://user-images.githubusercontent.com/167831/36613361-1cb3b5f8-188e-11e8-8bb6-f6a49eb7dfa3.png)

Thus, the plugin checks only under the elements of `<page-second>`.
![screen shot 2018-02-23 at 11 46 05 am](https://user-images.githubusercontent.com/167831/36613841-902c3acc-188f-11e8-9c35-733497c32541.png)


-----(end)-------


So, if DOM element has `__plugindomid` attribute, it does not mean the plugin checks all HTML elements everytime.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
There is some this like this case.

```html
<div style="position:absolute;width:0;height:0;visibility:hidden">
    <div style="position:absolute;left:30px;top:30px;width:300px;height:300px;background-color:red;z-index:100">
    </div>
</div>
```

**Comment by wf9a5m75** [comment]
1. As I said, this plugin does not check all HTML elements, only necessary elements.

2. The information is cached internally, and updated automatically.

3. Since the plugin uses cached information basically, the number of DOM parsing is very less.

4. If you are interested in to see what information is sent to native side, enable this line comment.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/4a654b9b328c29b29cf603a73b093db574a0ce05/www/googlemaps-cdv-plugin.js#L727

**Comment by wf9a5m75** [comment]
>I have shared a project based on Swift/Cordova, it's working inside XCode, but running cordova build killed me.
> https://github.com/fssrepository/cordova-plugin-fcm-modified

I'm not familiar with Swift.
