### ISSUE TITLE
phonegap google maps with framework7 v2

### ISSUE THREAD

**Issue by innoflash** [mapsplugin/cordova-plugin-googlemaps#2164]
Hi Framework7 developers.

i am having a serious problem working with [phonegap google maps](https://github.com/mapsplugin/cordova-plugin-googlemaps) with [Framework7 esp v2,](http://framework7.io/docs/)

I am required to select a div in my HTML to place a map here is what i did:

HTML Code:
```HTML
    <div class="page-content">
        <div id="map_canvas">
            the map canvas
        </div>
    </div>
```

CSS Code:
```css
#map_canvas, #journey_canvas, #routeMaps, #settingsmap{
    width: 100%;
    height: 100%;
    background-color: #0f0f0f;
    position: fixed;
   /* z-index: 5500;*/
}
```
JavaScript:
```javascript
var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div, {
            controls: {
                myLocationButton: true
            },
            gestures: {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            }
        });
```
There is more logic to the JS file but on my android device when i open this page i am getting the page overlapping the map.

**THE MAP IS RENDERED BUT IS NOT REPLACING THE ORIGINAL HTML**
![ygn4b 1](https://user-images.githubusercontent.com/12772919/37656529-f2dfca9c-2c50-11e8-9e12-b1f24ce6f6d5.jpg)

**And here how it looked in F7 v1** 
![bdsye 1](https://user-images.githubusercontent.com/12772919/37656555-0a8048ac-2c51-11e8-9722-77c0cc452287.jpg)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by innoflash** [comment]
https://github.com/innoflash/abiri-mobile.git


for login u can use the credentials
email: *all@gmail.com <all@gmail.com>*
password: *secret*

when you login then sliding menu and goto :"settings* i have placed a map
there

On Tue, Mar 20, 2018 at 4:13 PM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment]
Thank you for sharing. Excuse me, but could you tell me how to build your project?

**Comment by innoflash** [comment]
i was using phonegap build https://build.phonegap.com/

On Tue, Mar 20, 2018 at 6:18 PM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment]
I can't login to your app with your provided credential.
![capture](https://user-images.githubusercontent.com/167831/37668642-37291462-2c22-11e8-81f1-913eb6aaa983.png)

**Comment by wf9a5m75** [comment]
Thank you for quick helps through e-mails.
I figured out the reason. Because the `previous-page` covers the current page.

First of all, you need to understand how this plugin displays the map.
This plugin generates the native map view under the browser, and the browser is going to be `transparent`.

![](https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png)

When you open the setting page, the previous page is under the current page in HTML hierarchy.
![screen shot 2018-03-20 at 10 40 07 am](https://user-images.githubusercontent.com/167831/37672462-4275226c-2c2b-11e8-9f9c-2d45862b1175.png)


However, the map view is NOT html element, the map view is displayed under the previous page.
![capture](https://user-images.githubusercontent.com/167831/37672530-69cb9ecc-2c2b-11e8-9b84-03d89e9f448a.png)

**Comment by wf9a5m75** [comment]
Thus, solution is, you just add a CSS rule.

```css
.page-previous {
    display: none;
}
```

**Comment by wf9a5m75** [comment]
![capture2](https://user-images.githubusercontent.com/167831/37672661-b1a7199c-2c2b-11e8-956e-b663c12226de.png)

**Comment by innoflash** [comment]
very very solved here, thanks a lot@wf9a5m75, you are the best boss

On Tue, Mar 20, 2018 at 7:42 PM, Masashi Katsumata <notifications@github.com

**Comment by innoflash** [comment]
I look upto your level of understanding code, you are inspiration

On Tue, Mar 20, 2018 at 7:46 PM, Innocent Mazando <innocentmazando@gmail.com
> wrote:

> very very solved here, thanks a lot@wf9a5m75, you are the best boss
>
> On Tue, Mar 20, 2018 at 7:42 PM, Masashi Katsumata <

**Comment by innoflash** [comment]
very very solved here, thanks a lot@wf9a5m75, you are the best boss

**Comment by wf9a5m75** [comment]
You are welcome. 

By the way, I appreciate if you support for this project. 
**This is not mandatory asking**, but I appreciate if you donate some tip in order to continue active project working.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by innoflash** [comment]
i feel you very straight, i will see if i can set up a paypal account,
right now the card i am using is on VISA

On Tue, Mar 20, 2018 at 7:49 PM, Masashi Katsumata <notifications@github.com

**Comment by innoflash** [comment]
donation done, man you are worthy it

On Tue, Mar 20, 2018 at 7:52 PM, Innocent Mazando <innocentmazando@gmail.com
> wrote:

> i feel you very straight, i will see if i can set up a paypal account,
> right now the card i am using is on VISA
>
> On Tue, Mar 20, 2018 at 7:49 PM, Masashi Katsumata <

**Comment by innoflash** [comment]
u got it

**Comment by wf9a5m75** [comment]
Thank you for supporting the maps plugin project! Enjoy the maps plugin!
