### ISSUE TITLE
Reposition mylocation button

### ISSUE THREAD

**Issue by TimothyFehr** [mapsplugin/cordova-plugin-googlemaps#2185]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**  -> iPhone X only

**Current behavior:**
In my iPhone X the location button is just bearly not clickable (we have stretched the app over the full screen) and the button is rendered in the unclickable area of the iPhone screen.

Is there a way i can move the button to a better/different position?

thanks in advance

**Comment by makers-mark** [comment]
Hi @TimothyFehr, I use the padding option of the map to do this in Android. I do not know if this works in IOS. The map padding pushes in the Google logo at the bottom, the compass, and the myLocationButton. I use this to push the compass and button down from the top of the screen.
```
        map.setOptions({

              'padding':{
                'left':0,
                'top':25,
                'bottom':0,
                'right':0
              }
          });
```

**Comment by wf9a5m75** [comment]
The my location button comes from native side, not this plugin. Thus, we can't move it.

**Comment by makers-mark** [comment]
@TimothyFehr, I used an incorrect format for the options earlier. I changed it in the post up above. In Android at least, this is the difference between 25px top padding (first image), and a 75px top padding as well as a 200 px bottom padding (the bottom image, see the Google logo way up from the bottom).
I have never had any weird things happen either, like with a marker not showing up because it was in the padding or anything like that.

![screenshot_20180328-163935](https://user-images.githubusercontent.com/16088541/38055772-a8d18964-32a8-11e8-8252-44f409f04f20.png)
![screenshot_20180328-163158](https://user-images.githubusercontent.com/16088541/38055827-d009d568-32a8-11e8-8b89-578790503523.png)

**Comment by wf9a5m75** [comment]
Well, there is also `map.setPadding()` method.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/setPadding/README.md

**Comment by wf9a5m75** [comment]
I guess @TimothyFehr wants to just move the mylocation button to where he wants.
In that case, you need to create a button using html element.
This is the best way.

**Comment by wf9a5m75** [comment]
ping @TimothyFehr
