### ISSUE TITLE
Application stuck in splash screen after install google maps native	

### ISSUE THREAD

**Issue by YousefRabieKhalil** [mapsplugin/cordova-plugin-googlemaps#2191]
hello my ionic application was work well but after install google maps native plugin   , when trying run it in ios simulator it’s stuck in splash screen and dose not work but after remove the plugin it’s work well again

this is my ionic info

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v9.8.0
    npm        : 5.7.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b
```

my plugin list

```
call-number 0.0.2 "Cordova Call Number Plugin"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-clipboard 1.1.1 "Clipboard"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.1 "SocialSharing"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
onesignal-cordova-plugin 2.3.1 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.3 "Launch Navigator"
```

any help in this please , thanks in advance

**Comment by YousefRabieKhalil** [comment]
i'm also trying to downgrade version to 2.2.3 or 2.2.8 , the same problem appear

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by wf9a5m75** [comment]
Please create a project that **reproduce your issue 100%**, then share the files.

**Comment by YousefRabieKhalil** [comment]
i'm very sorry for late replay , I was trying reproduce the issue until that i discover tat i was including the google maps java script api to calculate routes , 
when i remove the this line 
` <script src="http://maps.google.com/maps/api/js?key=MY_KEY&libraries=places,geometry&language=ar"></script>`

from index.html the problem solved 
right now it work without this line but i need this script for doing some navigation stuff

**Comment by wf9a5m75** [comment]
Could you share the reproduce project on github tentatively?

**Comment by YousefRabieKhalil** [comment]
i'm sorry for late , this is the project https://github.com/YousefRabieKhalil/google-Map-testing

**Comment by wf9a5m75** [comment]
Thank you for sharing the reproduce project.

I figured out two reasons of the issue:

### reason 1: `<script>` tag

Since you define `<script>` tag in the `www/index.html` tag, the browser pauses the loading until completing the script src.
This causes super delay and, the ionic framework misses the `deviceready` event.
That's why `platform.ready().then(() => {});` does not work well.

![screen shot 2018-04-03 at 5 41 24 pm](https://user-images.githubusercontent.com/167831/38282671-43e89e94-3766-11e8-9eab-5d6a85f21188.png)

In order to prevent this, you need to specify the `defer` attribute.

![screen shot 2018-04-03 at 5 41 58 pm](https://user-images.githubusercontent.com/167831/38282683-54fe93dc-3766-11e8-8995-d2f7ff4dbbaf.png)

More details: check out https://stackoverflow.com/questions/10808109/script-tag-async-defer

By the way, Google counts the load usage (2,500times/day free usage) upon the number of times of `<script src>`.
I recommend you should define this tag only in the map page.

-------

###  reason 2:  the initialize process of this maps plugin

I adjusted the code of this plugin in order to resolve this issue.


-------

### Conclusion 

Please modify your `www/index.html`, then reinstall the maps plugin from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --variable ...
```
![2191](https://user-images.githubusercontent.com/167831/38282819-fef30ab2-3766-11e8-8f32-9ea596ff96c8.gif)

**Comment by YousefRabieKhalil** [comment]
thank you , i can confirm that the problem is solved even without using defer 👍

**Comment by CodeWithOz** [comment]
Came across this thread, @wf9a5m75 please is there a way you'd recommend to use the same `defer` attribute for the js script files that this plugin injects when it loads?
