### ISSUE TITLE
Ionic terribly slow after showing map

### ISSUE THREAD

**Issue by asedano** [mapsplugin/cordova-plugin-googlemaps#224]
I just show a map dialog when the user presses a button… I tried to remove it after closing but it doesn't improve :-/

I also tried to change Ionic scroll to normal overflow scrolling but it's the same…

I have this problem just in Android.

```
map.addEventListener(maps.event.MAP_READY, function() {
    map.setCenter(posicion);
    map.setZoom(17);
    map.showDialog();

    map.addEventListener(maps.event.MAP_CLOSE, function() {
        map.remove();
    });
});
```

**Comment by RichardGrant** [comment]
Any solutions for this i am having the same issue. -.- using Cordova android Samsung Galaxy s7.

**Comment by wf9a5m75** [comment]
@RichardGrant Please take a screen video, and share your project files on github or bitbucket. How and why? https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by RichardGrant** [comment]
its literally an empty codova project with a panel and loading the map in on device ready. nothing else. Looks exactly like the same issue on iconic that this user is experiencing.

**Comment by RichardGrant** [comment]
here is my memory usage:
Applications Memory Usage (kB):
Uptime: 46587015 Realtime: 49273606

** MEMINFO in pid 32622 [com.phonegap.spots] **
                   Pss  Private  Private  Swapped     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    22224    22164        4     3572    38656    35849     2806
  Dalvik Heap    22802    22464      316     1468    37877    21628    16249
 Dalvik Other     1761     1760        0        0                           
        Stack     1224     1224        0        0                           
       Ashmem      142       64        0        0                           
      Gfx dev    19462    19132        0        0                           
    Other dev        4        0        4        0                           
     .so mmap    48893      312    36684     5168                           
    .apk mmap     3232        0     2200        0                           
    .ttf mmap     3935        0     3804        0                           
    .dex mmap    26014       32    23584        0                           
    .oat mmap    10041        0     7008        0                           
    .art mmap     2967     1512     1040      204                           
   Other mmap     3340       12     2452        0                           
   EGL mtrack   123768   123768        0        0                           
    GL mtrack    59212    59212        0        0                           
      Unknown    12636    12628        0      112                           
        TOTAL   361657   264284    77096    10524    76533    57477    19055
 
 App Summary
                       Pss(KB)
                        ------
           Java Heap:    25016
         Native Heap:    22164
                Code:    73624
               Stack:     1224
            Graphics:   202112
       Private Other:    17240
              System:    20277
 
               TOTAL:   361657      TOTAL SWAP (KB):    10524
 
 Objects
               Views:       34         ViewRootImpl:        1
         AppContexts:        6           Activities:        1
              Assets:        7        AssetManagers:        5
       Local Binders:       33        Proxy Binders:       34
       Parcel memory:       16         Parcel count:       67
    Death Recipients:        1      OpenSSL Sockets:        2
 
 SQL
         MEMORY_USED:        0
  PAGECACHE_OVERFLOW:        0          MALLOC_SIZE:        0

**Comment by RichardGrant** [comment]
My Graphics Acceleration:
Applications Graphics Acceleration Info:
Uptime: 46648255 Realtime: 49334846

** Graphics info for pid 32622 [com.phonegap.spots] **

Stats since: 407652843956ns
Total frames rendered: 31985
Janky frames: 3711 (11.60%)
90th percentile: 18ms
95th percentile: 32ms
99th percentile: 97ms
Number Missed Vsync: 1104
Number High input latency: 12
Number Slow UI thread: 1825
Number Slow bitmap uploads: 167
Number Slow issue draw commands: 1385

Caches:
Current memory usage / total memory usage (bytes):
  TextureCache          9914880 / 92274688
  LayerCache                  0 / 60817408 (numLayers = 0)
    Layer size 1440x2288; isTextureLayer()=1; texid=5 fbo=0; refs=1
    Layer size 1472x2496; isTextureLayer()=0; texid=4 fbo=2; refs=1
  Layers total   27875328 (numLayers = 2)
  RenderBufferCache           0 /  8388608
  GradientCache               0 /  2097152
  PathCache                   0 / 16777216
  TessellationCache           0 /  1048576
  TextDropShadowCache         0 /  6291456
  PatchCache                  0 /   131072
  FontRenderer 0 A8           0 /        0
  FontRenderer 0 RGBA         0 /        0
  FontRenderer 0 total        0 /        0
Other:
  FboCache                    1 /       16
Total memory usage:
  37790208 bytes, 36.04 MB

Profile data in ms:

	com.phonegap.spots/com.phonegap.spots.MainActivity/android.view.ViewRootImpl@4c1eec8 (visibility=0)
Stats since: 407652843956ns
Total frames rendered: 31985
Janky frames: 3711 (11.60%)
90th percentile: 18ms
95th percentile: 32ms
99th percentile: 97ms
Number Missed Vsync: 1104
Number High input latency: 12
Number Slow UI thread: 1825
Number Slow bitmap uploads: 167
Number Slow issue draw commands: 1385

View hierarchy:

  com.phonegap.spots/com.phonegap.spots.MainActivity/android.view.ViewRootImpl@4c1eec8
  29 views, 32.77 kB of display lists


Total ViewRootImpl: 1
Total Views:        29
Total DisplayList:  32.77 kB

**Comment by wf9a5m75** [comment]
The original issue was not reproduced.

**Comment by wf9a5m75** [comment]
If you don't share your project files, I can't help you.

**Comment by wf9a5m75** [comment]
Many ionic developers use this plugin, and they are no problem. So it must be related with your project files.

**Comment by RichardGrant** [comment]
I am 100% certain it is not with my project files. One moment while i add a simplified example to github.

**Comment by RichardGrant** [comment]
@wf9a5m75 Finally was able to migrate my project out. https://github.com/RichardGrant/maps
Notice when you click the search icon the panel doesnt animate slide open or close.

**Comment by RichardGrant** [comment]
@wf9a5m75 did you find anything ? Iv'e been cracking away at this for a few days now and cant seem to find the issue.

**Comment by wf9a5m75** [comment]
I have lots of task. I don't work only for you. Please wait for a while.

**Comment by RichardGrant** [comment]
No problem :) just really hyped to get this plugin working.

**Comment by wf9a5m75** [comment]
@RichardGrant Ah, you use the plugin v1.4.3.
Please try to v2.0-beta, which is more faster and more functions.

**Comment by wf9a5m75** [comment]
@RichardGrant I just build and run your project, but is this terribly slow? I don't think so.

This screen record is taken on my  Moto G (Android 4.4.4), which is kind of old device.

![224](https://user-images.githubusercontent.com/167831/28228987-b6b05fd4-6895-11e7-8fc7-af45aee330d8.gif)

**Comment by RichardGrant** [comment]
@wf9a5m75 Yes, look at the panel, it is suppose to animate open and animate close by sliding left and right. the map causes it to instantly pop open and pop close.
comment out the plugging in the my-app.js file and you will see what i am talking about.

**Comment by wf9a5m75** [comment]
First of all, you need to understand how this plugin displays the map view.
The map is not HTML element, completely different view.
The map view is **UNDER the browser view**.

Because of this, the plugin checks the map div position periodically, and move the map view.
If I change the frequency to high (such as 5ms), animate might be smooth, bug high frequency wastes large battery usage.
Low frequency saves battery usage.
For the reason, this is not bug. This is specification.

If you don't like this, please use the Google Maps JavaScript API v3.

**Comment by RichardGrant** [comment]
Wow you went into great detail. Do you think you could write into the API to change the frequency manually or create an on and off solution?
I **REALLY** don't want to use the google maps javascript API because your plugin is much smoother.

**Comment by wf9a5m75** [comment]
I think looking for another solution is better answer.
For example, the menu overlays on the map.

**Comment by wf9a5m75** [comment]
v1.4 will be charged to v2.0 next month (in current plan).
I recommend you use the v2

**Comment by RichardGrant** [comment]
@wf9a5m75 idk if that is the issue iv'e been digging at the `plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js`  file code and in the i found:
```
while (div.parentNode) {
            div.style.backgroundColor = 'rgba(0,0,0,0)';
            className = div.className;

            // prevent multiple readding the class
            if (div.classList && !div.classList.contains('_gmaps_cdv_')) {
                div.classList.add('_gmaps_cdv_');
            } else if (div.className && !div.className.indexOf('_gmaps_cdv_') == -1) {
                div.className = div.className + ' _gmaps_cdv_';
            }

            div = div.parentNode;
        }
```
commenting this out stopped the lag.

**Comment by wf9a5m75** [comment]
You can folk the repository and create your version.

**Comment by RichardGrant** [comment]
sure, i cant figure out what the class _gmaps_cdv_ does? can you enlighten that for me?

**Comment by wf9a5m75** [comment]
Unfortunately I don't support v1.4 anymore.

**Comment by RichardGrant** [comment]
I will definitely be using v2.0. i'm relieved that the issue was on the Cordova side and not you rside. Thanks for the support!

**Comment by Textras** [comment]
> I will definitely be using v2.0. i'm relieved that the issue was on the Cordova side and not yourside. Thanks for the support!
@RichardGrant 
bit confused by your answers. You mention first changing the div.style.backgroundColor above to add 

            div = div.parentNode;
  if(!div.parentNode) {
    console.log("finish done");
    clearInterval(t_i);
  }
};

var t_i = setInterval(finish, 1000);

but then you say you found lag in Framework (which is not Cordova), but then that you were relieved it was Cordova. Did you also have a Cordova issue occurring not mentioned between your second to last comment and your last? We cured some of the lag in ours by almost immediately halting the z-index and html DOM pings to assess map positioning, on 'map view'. We do not destroy the map, there is one, and it persists, and we know exactly where we want it. When user leaves the map, we stop the interval pinging altogether and persist the tiles. This has drastically improved things. But still there is more optimization to be done as we still see some long scripts in timeline persist after leaving the map, hence a possible mem leak.
