### ISSUE TITLE
Question about multiple_maps branch

### ISSUE THREAD

**Issue by ebellempire** [mapsplugin/cordova-plugin-googlemaps#2298]
**I'm submitting a ...**  
- [x] question

Hi @wf9a5m75 and other contributors, I'm sorry to post here but figured it might be preferable to posting on the Ionic Forum (if not, please let me know). 

I was wondering where I can find more information about the multiple maps branch. What is the difference between that branch and master? Why do they remain separate? Is the multiple maps branch always up to date with master? Are there performance differences or other tradeoffs I should know about, other than making it easier to have multiple maps in a single app? 

I'm trying to decide if I should switch to the multiple maps branch for my project. I'm currently using the master branch and have put my code into a "provider," which works great for the recent updates (thank you for your ongoing work!). At one point, I had my app displaying a second map in a [modal](https://ionicframework.com/docs/api/components/modal/ModalController/) view (using the master branch), which worked well, but I've decided to move the second map to a [segmented](https://ionicframework.com/docs/api/components/segment/Segment/) view, and have not been able to display it using the master branch. So I'm probably going to switch to the multiple maps branch, but wanted to get some more information before I do so. 

Thanks! -- Erin

**Comment by jld3103** [comment]
The multiple_maps branch is the dev branch. This means there are the latest bug fixes and features.

**Comment by ebellempire** [comment]
Oh, ok, I'm glad I asked! I thought I had seen elsewhere (probably on the Ionic Forum) some reference to that being the solution for adding multiple maps. Maybe it was at some point?

**Comment by wf9a5m75** [comment]
I use branches for these purpose:

- master branch:
  providing stable version, as the same as NPM version.
- multiple_maps branch:
  providing beta version, which contains bug fixes or new features.
  It might be stable or unstable. Depends on the latest commit.
- other branches:
  I use for temporally saving, exploring, etc...

For example, someone reports me a problem, then I fix it, I commit to the multiple_maps branch.
If I decide the multiple_maps branch is stable, I release to npm, and master branch.

----------

So how you can check it?
You can check the network graph at here (or using git client softwares)
https://github.com/mapsplugin/cordova-plugin-googlemaps/network

The multiple_maps branch is the same as the master branch at this time, because I released v2.3.5 yesterday.
![screen shot 2018-05-30 at 2 13 47 pm](https://user-images.githubusercontent.com/167831/40747935-b6d3154a-6413-11e8-9608-fd8bc0addd1a.png)
