### ISSUE TITLE
Private support

### ISSUE THREAD

**Issue by dennis-wedevise** [mapsplugin/cordova-plugin-googlemaps#2330]
I have already explained my question here: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2320. Is it possible to get private support on my issue?

Thanks, Dennis

**Comment by wf9a5m75** [comment]
#--------------------
# public support
#--------------------
Since this plugin project is open source, I give you free public support.
I almost all cases ask you to share your project files on Github or other git repository services.
I don't matter if it is public or private repo.
However screen captures or screen records are posted in public issue thread.
(Code are not discovered as much as possible)

#--------------------
# private support
#--------------------
Even if you don't want to discover anything including screen captures or screen records,
please ask me to private support.
I ask you to donate $100 USD to the maps plugin project,
then I make a private space, then support it.

**Comment by dennis-wedevise** [comment]
I just made the donation.

**Comment by wf9a5m75** [comment]
@dennis-wedevise I sent you the invitation for private room, yesterday, but you haven't accepted it yet. Please double check your email inbox.
