### ISSUE TITLE
Map problem plugin

### ISSUE THREAD

**Issue by luisfernando-rf** [mapsplugin/cordova-plugin-googlemaps#2360]
Good morning, I have a problem with the google map plugin of an app I'm doing, the map opens below my Login screen which is index.html, but I need it to stay in home.html. I already tried some solutions, but without success. Can someone help me?

<img src="https://user-images.githubusercontent.com/41697952/43213744-c50cdb5c-900d-11e8-83d0-f9199fe8b1e5.jpg" width="250">

**Comment by wf9a5m75** [comment]
Well, please share your project files on github at least.

**Comment by luisfernando-rf** [comment]
Follows attachment below

[project.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2228712/project.zip)

**Comment by wf9a5m75** [comment]
I don't accept any zip file. It's kind of spamming for me.
Please create a git repository on Github, and put your code files on it.
https://guides.github.com/activities/hello-world/

**Comment by luisfernando-rf** [comment]
Follow:

https://github.com/luisfernando-rf/photoSelling/tree/readme-edits

**Comment by wf9a5m75** [comment]
Please include everything.

In order to reproduce your issue, I will do following commands:

```
$> git clone https://github.com/luisfernando-rf/
$> cd luisfernando-rf
$> cordova prepare
$> cordova run android
```

So, I need all `www` files and `config.xml` file at least.

**Comment by luisfernando-rf** [comment]
Ok, check again!

https://github.com/luisfernando-rf/photoSelling/tree/readme-edits

**Comment by wf9a5m75** [comment]
Thank you, but is it possible to create like this?
https://github.com/mapsplugin/HelloGoogleMap

```
.
├── LICENSE
├── config.xml
├── hooks
│   └── README.md
├── package.json
└── www
    └── index.html, home.html ...
```

**Comment by luisfernando-rf** [comment]
See if it got better!

https://github.com/luisfernando-rf/rfPhotoSellingMobile

**Comment by wf9a5m75** [comment]
Thanks, it's better now, but even now, you don't include everything, so I can not reproduce your issue exactly.
You missed `css/index.css`, `mobileui/mobileui.js` and `js/index.js`.

<img src="https://user-images.githubusercontent.com/167831/43219168-6c87d9e4-8ffb-11e8-8217-a5a18e7b696c.png" width="250">

------------------

I checked your code files briefly.
I guess the problem occurs after logging-in.

In order to use this plugin as intend, you need to understand this plugin displays the native map view under the browser.
![](https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-doc/master/v1.4.0/class/Map/mechanism.png)

Because of the map view is under the browser, the maps plugin changes all html elements of map div to transparent.
Since I can not enter to your app, I can't reproduce your issue exactly, but here is my guess.

JS frameworks often use `z-index` css rules for paging.
I guess login page is under the map page.

However, because of this plugin changes all html elements are transparent, you can see the login page over the map.

![2360](https://user-images.githubusercontent.com/167831/43219714-e98e2d20-8ffc-11e8-9352-754f96473eb8.png)

In order to avoid this, you need to move the login page to outside of the viewport by your code.

**Comment by luisfernando-rf** [comment]
Ok, I get it.

"In order to avoid this, you need to move the page to outside of the viewport by your code."

How can I do this?

**Comment by wf9a5m75** [comment]
I don't know, debug your code using chrome inspector.
