### ISSUE TITLE
HTMLinfowindow doesnt work

### ISSUE THREAD

**Issue by stefanwilliam96** [mapsplugin/cordova-plugin-googlemaps#2384]
how to use HTMLinfowindow ??? i run this function and the result is not showing the button, it just showing text from variable html. 

Is that any simply way to add html content to marker ?

function showNearby(){
        var div = document.getElementById("map_canvas");
        // Create a Google Maps native view under the map_canvas div.
        var map = plugin.google.maps.Map.getMap(div);
        
        var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

        var html = [
          'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
          '&lt;br&gt;',
          '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
        ].join("");
        htmlInfoWindow.setContent(html);

        marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
          htmlInfoWindow.open(marker);
        });
        marker.trigger(plugin.google.maps.event.MARKER_CLICK);
        
        var data = [
            {
                position: {lng: 112.752088, lat: -7.257472},
                title: "Pusat"
            },
            {
                position: {lng: 112.733089, lat: -7.302664},
                title: "Wonokromo"
            },
            {
                position: {lng: 112.688149, lat: -7.283382},
                title: "Pradahkali Kendal"
            }
        ];

        // Add markers
        var bounds = [];
        var markers = data.map(function(options) {
            bounds.push(options.position);
            return map.addMarker(options);
        });

        // Move to the position with animation
        map.animateCamera({
            target: bounds,
            zoom: 10,
            duration: 2000
        });

        // open the last marker.
        markers[markers.length-1].showInfoWindow();
    }

**Comment by wf9a5m75** [comment]
Ok, I tell you step by step.

### wrong point No.1

You escape HTML strings (i.e. `<br/>` to `&lt;br&gt;`), but HtmlnfoWindow displays string as strings.
So it becomes like this.
![screen shot 2018-08-08 at 3 27 19 pm](https://user-images.githubusercontent.com/167831/43867797-986a70f6-9b1f-11e8-80d6-4e71c371b4c9.png)

You need to write HTML strings as unescaped strings.
```js
var html = [
  'This is <b>Html</b> InfoWindow',
  '<br/>',
  '<button onclick="javascript:alert(\'clicked!\');"</b>click here</button>',
].join("");
htmlInfoWindow.setContent(html);
```
![screen shot 2018-08-08 at 3 29 09 pm](https://user-images.githubusercontent.com/167831/43867850-d117316e-9b1f-11e8-8475-66b83cacfeab.png)

### wrong point No.2

In your code, you create an instance of HTMLInfoWindow, then try to open it with undefined marker instance.

```js
var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

var html = [
  'This is &lt;b&gt;Html&lt;/b&gt; InfoWindow',
  '&lt;br&gt;',
  '&lt;button onclick="javascript:alert(\'clicked!\');"&gt;click here&lt;/button&gt;',
].join("");
htmlInfoWindow.setContent(html);

//
// [your mistake point]
// There is no definition `marker` variable at this time.
//
marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
  htmlInfoWindow.open(marker);
});
marker.trigger(plugin.google.maps.event.MARKER_CLICK);
```

So, it becomes `marker is undefined` error.


The solution is you need to change your code.
Since you want to open the HTMLInfoWindow when you click on marker, you need to write your code like this:

```js
var data = [
    {
        position: {lng: 112.752088, lat: -7.257472},
        myTitle: "Pusat"
    },
    {
        position: {lng: 112.733089, lat: -7.302664},
        myTitle: "Wonokromo"
    },
    {
        position: {lng: 112.688149, lat: -7.283382},
        myTitle: "Pradahkali Kendal"
    }
];

// Add markers
var bounds = [];
var markers = data.map(function(options) {
    bounds.push(options.position);
    var marker =  map.addMarker(options);
    marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
      var html = [
        'This is <b>Html</b> InfoWindow',
        '<br/>',
        '<button onclick="javascript:alert(\'clicked!\');"</b>click here</button>',
      ].join("");
      htmlInfoWindow.setContent(html);

      htmlInfoWindow.open(marker);
    });
    return marker;
});

// Move to the position with animation
map.animateCamera({
    target: bounds,
    zoom: 10,
    duration: 2000
});

// open the last marker.
markers[markers.length-1].showInfoWindow();
```

### wrong point No.4

Do not set `title` or `snippet` properties if you want to use HtmlInfoWindow.

**Comment by stefanwilliam96** [comment]
okay thanks a lot
