### ISSUE TITLE
Places Autocomplete - Anyone wants to donate together?

### ISSUE THREAD

**Issue by lolaswift** [mapsplugin/cordova-plugin-googlemaps#2418]
**Please tell us your new feature idea**
Basic google places autocomplete

**Why do you need it?**
1. Much improved user experience. 
2. Using the web API isn't a good option because it's almost not possible to restrict access to the API. Therefore, using it in production has security risks. 

**How helps other people?**
I guess most people who want to use places autocomplete either don't care about the security or not aware of the risks. Or they have to implement it on their back-end which needs a lots of work.

We need to reach the target $1000.  Anyone else wants to donate together to make it happen? Please comment.

**Comment by wf9a5m75** [comment]
**Why do I don't implement?**

1. `Google Places API` is expensive. See the price table of Google Maps API.
https://cloud.google.com/maps-platform/pricing/sheet/?hl=en
![screen shot 2018-09-11 at 4 22 44 pm](https://user-images.githubusercontent.com/167831/45393042-f609ba80-b5de-11e8-8527-2e6e91d03c91.png)

2. Implementing for all platforms is hard work.
Not only browser platform, but also Android, and iOS.
I need to implement different code for three platforms. It takes much time.

3. fundraising was not successful.
I made a fund raising in the past, but nobody had interested in.

Thus, I don't implement the places auto complete.

If you want to implement the places auto complete anyway, please use the Google Maps JavaScript v3 + places library with this plugin.
Someone do that.

**Comment by wf9a5m75** [comment]
Any opinions?

**Comment by lolaswift** [comment]
@wf9a5m75 Sorry for my late reply. I actually took some time looking into the pricing issue. Thank you so much for the pricing info.  I knew google had started a new pay-as-you-go model but I hadn't got time looked into it. Now I am scared because I am using it on my web app. Because as you said, yes, it can get very expensive. Especially if you want to get place details.

 On my mobile apps, in my  case, I don't need to call the getPlace api. I can call the native geocoding to find the lat &lng of the address, it's free, isn't it? so the cost will be:

Autocomplete - Per Request $2.83 per k requests
Native Geocoding: Free ( Am I correct? Can't find any info. Native maps are free on that list)

For implementing the most basic feature like this, is it feasible? I am not sure how many people will have such needs. So I can't speak for other people and I'm not sure if others will donate. I will email you personally. Is it possible for you to let me know your target of donation to make it happen? Maybe I can donate along when I can afford.

I dont' want to use the Google Maps JavaScript v3 + places library on mobile apps because it's not possible to limit the api key to the use of only my apps. I talked to the google support before but there is not good solution.

**Comment by wf9a5m75** [comment]
### Geocoding price

Regarding of the geocoding price, it is correct understanding (`browser`: pay-as-you-go, `android, ios`: free), as far as I know.
But I have been making sure to Google Maps team for just in case.
I will update about this.

--- 

### Auto complete

Well, some people requested me to implement it. 
Since implementing new feature, even it has basic functions only, I have to take time, and I need to keep up-to-date(work it always) forever.
Because of this, I always ask $1,000 USD donation.

For instance, `HTMLInfoWindow` and `MarkerCluster` are donated implementation.
Both works spent almost three months for each.
And I fixed bugs even after releasing.

Running code on variable devices cause unexpected things a lot.
So creating a new feature is not just implementation, but also including code maintenance.
That's why I always ask $1,000 USD donation.

Well, you may think it is too expensive. But let's think about this. If you ask to work for someone who are familiar with Android, iOS, and JavaScript, the cost might be more expensive, and probably no maintenance after the delivery.

In my case, I will provide private code sharing, private support, and implement three platforms on by one.
Note that private code sharing and support is end when the feature is releasing and extra one month.
And if I can't complete the work in three month, I return all amount to you.

I believe there is no good offer than mine.

If you agree with this, please donate from here.
https://github.com/mapsplugin/cordova-plugin-googlemaps#please-support-this-plugin-activity

**Comment by wf9a5m75** [comment]
### update : Geocoding price

I confirmed to Google. Our knowledge is correct. Thus, this plugin geocoder on Android and iOS are free.
(iOS geocoder is Apple's one)

**Comment by lolaswift** [comment]
@wf9a5m75 $1000 USD is a reasonable price. Not expensive at all in my opinion. I am fully aware how much work it takes to get some quality job done. You don't need to convince me at all. Can we keep this feature request for a while so that more people can see? If five person can donate $200 each, we will be able to easily reach the target. Since I just started developing my business, I can't donate the full amount alone at this stage. This will be the first feature I am going to invest once I start getting revenue if there is still not enough donation. 

btw, many thanks again for the confirmation about the cost of the Geocoding service. I didn't know this plugin also does geocoding & reverse geocoding as well.  If I understand it correctly, with the new google pricing model, google maps(dynamic maps) has also become free on mobile platforms when using cordova-plugin-googlemaps? I remember there was some limitation before.

I just donated a very small amount to buy you a coffee for thanking you for the great cordova-plugin-googlemaps. It's not the donation for the new feature yet:-).

**Comment by wf9a5m75** [comment]
### Auto complete donation

> Can we keep this feature request for a while so that more people can see?
> If five person can donate $200 each, we will be able to easily reach the target.

Yes, you can spread the amount. But if the number of people more than three people, I might be limit the number of people for private support.
Because private support during the development is kind of another hard work.
So I would spread donors to `primary` and `beta testers` depends on their donation amounts.

----------

### Maps price

> If I understand it correctly, with the new google pricing model, google maps(dynamic maps) has also become free on mobile platforms when using cordova-plugin-googlemaps? 

Yes, correct.
- `Android, iOS` -> still free
- `Browser` -> Free up to 28,000 loads, then $7.00/1,000 times

---------

### Your donation

Thank you for your donation. I really appreciate for your help ;)

**Comment by lolaswift** [comment]
@wf9a5m75 Thanks again!

**Comment by lolaswift** [comment]
@wf9a5m75 

I might be wrong about the cost calculation.
If we want to get a selected place from the drop down menu and do our own geocoding, it's not possible because place is an object and the autocomplete results we are seeing are derived from the properties of Place object. That means, we have to pay for the place details api call as well. That make it $17 per 1k requests:

 Autocomplete (included with Places Details) - Per Session
+ Places Details
+ Basic Data

Anyway, my feature request stays valid and  so does my calling for more people for sharing the amount.

**Comment by wf9a5m75** [comment]
It seems nobody is interested in this project.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread.

**Comment by kevinpocovi** [comment]
Hello guys, 

I'm interested in donating with @lolaswift the amount needed to develop this feature. Are you both still interested in carrying it on?

**Comment by vukdavid** [comment]
Looking forward to the feedback @lolaswift? :)

**Comment by orchoban** [comment]
I'm waiting for that too.

**Comment by spinninghamster** [comment]
I am still interested in this @lolaswift . Did this project ever take off? Or did you find an alternative?

**Comment by lolaswift** [comment]
hi, I do not use cordova anymore. switched to flutter.

**Comment by spinninghamster** [comment]
> hi, I do not use cordova anymore. switched to flutter.

That's what I was afraid of. :P
