### ISSUE TITLE
TileOverlay still downloading tiles even if not visible?

### ISSUE THREAD

**Issue by kozuch** [mapsplugin/cordova-plugin-googlemaps#2481]
I added a tile overlay with map.addTileOverlay. This works nicely. I can toggle the overlay visibility with tileOverlay.setVisible(). My question is - does the overlay fetch tiles from the source I defined even if the overlay is hidden (but not removed)? Or does it save "bandwidth" by not fetching the tiles when overlay not shown?

Btw. most your documentation on "var tileOverlay = map.addTileOverlay()" function is wrong since this seems to be asynchronous and so the tileOverlay variable remains empty :). I had to get the TileLayer object in addTileOverlay callback (second argument).

**Comment by wf9a5m75** [comment]
If you return `null` from `getTile()`, the maps plugin doesn't load map tile.

This plugin uses special mechanism, similar like `Promise`.
I'm not sure you use the latest version of this plugin, but this plugin since v2.3.0 returns `synchronized instance`.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/ReleaseNotes/v2.3.0/README.md#a-callback-is-no-longer-required-for-the-most-part
