### ISSUE TITLE
can't remove Marker cluster 

### ISSUE THREAD

**Issue by livedota** [mapsplugin/cordova-plugin-googlemaps#2504]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [X ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
insert the output from the command here

**Current behavior:**
Cluster are not removed, the cluster icon do not disappear and same behavior for marker inside the cluster

**Expected behavior:**
Cluster are removed

**Related code, data or error log (please format your code or data):**
No error inside console, I have used this project [https://github.com/mapsplugin/marker_cluster_demo](url)

**Comment by wf9a5m75** [comment]
Please share "**YOUR**" project files on GitHub.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/browser/PluginMarkerCluster.js#L424-L437

**Comment by livedota** [comment]
https://github.com/livedota/demo-Claster.git

**Comment by wf9a5m75** [comment]
You just copy the files... That doesn't make sense.

I need to confirm how reproduce the problem on your actual code.

Since you say 'remove method does not work on browser', please deploy the files on GitHub as GitHub page

Like this repo.
https://mapsplugin.github.io/HelloGoogleMap/

https://github.com/mapsplugin/HelloGoogleMap

https://github.com/mapsplugin/HelloGoogleMap/blob/master/package.json#L22


If you don't know how to host HTML files on GitHub, check out here. Super easy.

https://pages.github.com

**Comment by livedota** [comment]
https://livedota.github.io/demo-Claster/ just changed some line to make it work, i haven't used the script beacuse i'm not on linux

**Comment by wf9a5m75** [comment]
Sorry for late response. I was really busy.
I fixed this bug. Please reinstall the plugin from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```
