### ISSUE TITLE
ERROR: Plugin 'map_5_23451720258' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

### ISSUE THREAD

**Issue by busaku** [mapsplugin/cordova-plugin-googlemaps#2547]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.50 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
**Current behavior:**
```
2019-01-15 15:52:33.845750+0100 Dogs[14172:1304887] ERROR: Plugin 'map_5_23451720258' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-01-15 15:52:33.845889+0100 Dogs[14172:1304887] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","map_5_23451720258","detachFromWebView",[]]
2019-01-15 15:52:33.851039+0100 Dogs[14172:1304887] ERROR: Plugin 'map_5_23451720258' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-01-15 15:52:33.851143+0100 Dogs[14172:1304887] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","map_5_23451720258","attachToWebView",[]]
CoreData: annotation:  Failed to load optimized model at path '/Users/patrickpeters/Library/Developer/CoreSimulator/Devices/5FBE5537-7A4D-4DC1-AB30-7E75EC6EF069/data/Containers/Bundle/Application/B9CB30A8-A5E6-4382-A04B-4D073926404C/Dogs.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/Users/patrickpeters/Library/Developer/CoreSimulator/Devices/5FBE5537-7A4D-4DC1-AB30-7E75EC6EF069/data/Containers/Bundle/Application/B9CB30A8-A5E6-4382-A04B-4D073926404C/Dogs.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'
CoreData: annotation:  Failed to load optimized model at path '/Users/patrickpeters/Library/Developer/CoreSimulator/Devices/5FBE5537-7A4D-4DC1-AB30-7E75EC6EF069/data/Containers/Bundle/Application/B9CB30A8-A5E6-4382-A04B-4D073926404C/Dogs.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

```

Yes i saw the map and its worked fine. But it seems to be verrryyy slow until the error is posted.
In other issues, i read that the plugin will get an update (end 2017) or he copy the files from other Cordova project, but it didn't seems to work well.

Did anyone know why i got this message and how to fix them?

Thanks in advance
paD

**Comment by wf9a5m75** [comment]
You tried to use removed map.

**Comment by busaku** [comment]
Hm.. 
So i did not find any solution. 

If i try the app in browser (emulate browser) i got no errors, everything works fine.
On a second page i didn't the the map and i got the same errors..

**Comment by bennibeef** [comment]
I habe this problem too and am now out of options what to do.

Its the same issue this guy had:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2489

It probably isnt something with the plugin, maybe with our projects.

I tried everything. Removing, adding... First I had the problem this guy in the other issue had too:
It wont correctly install because of cocoapods, it runs only with pods update in platforms folder.

> I tried to re-create a new, simpler project to upload but ran in to new issues which is why I didn't provide any code. It seems, as a separate issue that ionic cordova plugin add cordova-plugin-googlemaps doesn't complete the process of adding cocoapods dependencies.

--> Happens to me too. But then the mapping error coccurs. Well I have removed and added this plugin and platforms like 100 times tried everything I could think of but now I'm out of options.


@wf9a5m75 this problem looks like its difficult to debug but I think its relevant. If needed I will pay the private support.

its the only plugin in my project and there is nothing fancy. It just cant map.

config.xml:

```   
 <plugin name="cordova-plugin-googlemaps" spec="^2.5.0">
        <variable name="API_KEY_FOR_ANDROID" value="keykeykey" />
        <variable name="API_KEY_FOR_IOS" value="keykeykey" />
    </plugin>```

**Comment by busaku** [comment]
Hey,

i worked with dynamic content (Ajax load my webpages).
If i don't do, the plugin works without errors.

But:
After do a lot of tests i found a solution to show the map correctly every time. 
I got the errors, but it will show on iOS and android everytime correctly.

My tipps:
Look that every div or item on the page got NO background. (!!!!)
Wait until every single Ajax file is loaded, your view/page is loaded and then activate the map.
Wait until the map is ready before u start camera animations e.g.
Be sure, the map-div got the correct high (if u has some dynamic high, wait until animations e.g. are ready).

**Comment by wf9a5m75** [comment]
@bennibeef Please share your project files on github repository.

**Comment by wf9a5m75** [comment]
Ping

**Comment by iconio** [comment]
Hey guys I am having the same issue. 
I have installed the CocoaPods and everything but once the page that has the map get called, this error shows up on XCode's console:

---

> 2019-02-14 09:11:20.958461-0500 Unbrwd[4960:157566] ERROR: Plugin 'map_0_55259594028' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2019-02-14 09:11:20.958787-0500 Unbrwd[4960:157566] FAILED pluginJSON = ["INVALID","map_0_55259594028","detachFromWebView",[]]
2019-02-14 09:11:21.111335-0500 Unbrwd[4960:157566] WARNING: Unable to find and load 'GoogleMaps.bundle' for Google Maps SDK for iOS. This may be a sign that you've forgotten to include a resources bundle in your 'Copy Bundle Resources' build phase. As this bundle contains important resources, you may encounter missing images, translations and other incorrect behavior.
2019-02-14 09:11:21.117032-0500 Unbrwd[4960:157566] *** Terminating app due to uncaught exception 'GMSServicesException', reason: 'Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources''
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001052131bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001047b9735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105213015 +[NSException raise:format:] + 197
	3   Unbrwd                              0x000000010026ff51 +[GMSServices mapsBundle] + 225
	4   Unbrwd                              0x000000010026c6f9 -[GMSAsyncInitServices sharedInitWithSync:] + 104
	5   Unbrwd                              0x000000010026c619 -[GMSAsyncInitServices initSync] + 71
	6   Unbrwd                              0x000000010026db9b +[GMSServices sharedServicesSync] + 183
	7   Unbrwd                              0x000000010025d5a9 -[GMSMapView sharedInitWithServices:camera:forPlaces:] + 156
	8   Unbrwd                              0x000000010025ca11 -[GMSMapView initWithFrame:camera:] + 123
	9   Unbrwd                              0x000000010025c835 +[GMSMapView mapWithFrame:camera:] + 104
	10  Unbrwd                              0x00000001001bc35d __28-[CordovaGoogleMaps getMap:]_block_invoke + 4445
	11  libdispatch.dylib                   0x000000010583f595 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000105840602 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010584d99a _dispatch_main_queue_callback_4CF + 1541
	14  CoreFoundation                      0x00000001051783e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x0000000105172a76 __CFRunLoopRun + 2342
	16  CoreFoundation                      0x0000000105171e11 CFRunLoopRunSpecific + 625
	17  GraphicsServices                    0x00000001095711dd GSEventRunModal + 62
	18  UIKitCore                           0x000000010d4d081d UIApplicationMain + 140
	19  Unbrwd                              0x00000001001a98d1 main + 65
	20  libdyld.dylib                       0x00000001058b6575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

---

### This is my system info:
## Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/Users/weltondemetrio/.nvm/versions/node/v8.14.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

## Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

## System:

   ios-deploy : 1.9.4
   NodeJS     : v8.14.0 (/Users/weltondemetrio/.nvm/versions/node/v8.14.0/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

---

I have deleted the project and re-added a bunch of times but nothing seems to work. What am I missing? 

Thank you!

**Comment by busaku** [comment]
Did you opened .xcworkspace or the .xcodeproj ?

**Comment by wf9a5m75** [comment]
@iconio 

```
cd platforms/ios

pod install
```

**Comment by iconio** [comment]
@wf9a5m75 That worked! Thank you very much! BTW, great job on this plugin! Your work is deeply appreciated :)

**Comment by Danbardo** [comment]
@wf9a5m75 thank you! I just rebuilt an old project and received the same error.

This resolved the issue.

I never previously had to use pod install and had no idea how to resolve the error.

Thanks again!

**Comment by Danbardo** [comment]
@wf9a5m75  thank you! I just rebuilt an old project and received the same error.

This looks like it will resolved the issue as I noticed the google maps plugin is missing.

I never previously had to use pod install and had no idea how to resolve the error.

However, now I am receiving:
library not found for -lPods-Appname
linker command failed with exit code 1.

Is there something I need to edit in my pods project?

I had a look around and couldn't see anything that seemed related to the error.

**Comment by wf9a5m75** [comment]
> library not found for -lPods-Appname

That's not related with this plugin. Please ask questions only related with this plugin. Other questions, please ask at StackOverflow/

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.

**Comment by loks15** [comment]
map shown only gray color
