### ISSUE TITLE
map is draggable from the HTML page, controls missing

### ISSUE THREAD

**Issue by ppetree** [mapsplugin/cordova-plugin-googlemaps#2569]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**Current behavior:**

Options are set as:
```
   {camera: {zoom: 19, target: {lat: latitude, lng: longitude}}, 
                    center: {lat: latitude, lng: longitude}, 
                    gestureHandling: 'none', 
                    zoomControl: true, 
                    scaleControl: true, 
                    mapTypeId: 'roadmap'};
```
**Expected behavior:**
There would be a zoomControl AND ... when the page is drawn, the map is displayed and I can scroll down to the text below the map and if I move my finger around on that text, the map image moves in the viewport.

**Screen capture or video record:**
I do have a video recording of this but I can't upload it to any public places. 

**Related code, data or error log (please format your code or data):**
There are no errors produced in the console.

**Comment by ppetree** [comment]
There's nothing to share...  this is easily duplicateable within your own code. I gave you the options.  If you create a div like this:
```
      <div id="map_canvas" style="height:300px; width:100%;"></div>
```

put some html text below that, draw the page, scroll down to below the map_canvas and move your finger around on the html you'll see the map move.  No way that should happen under any circumstance.

Also, the controls are missing as specified in the options.

**Comment by wf9a5m75** [comment]
`zoomControl` for iOS is not available, it's not a bug. It's specification.
Also I don't support without shared project files except super easy question.
This plugin project is not my job, it's hobby.
That's why I use my limited private time even replying your comment.

Even creating simple project, I have to spend time. Unfortunately I don't have enough time recently.

That's why I ask to share your project files for every one.

If you don't agree with this, please use Google Maps JavaScript API v3.
