### ISSUE TITLE
Map not showing on iOS if device if plugin initialized while device is offline

### ISSUE THREAD

**Issue by francoisduchemin** [mapsplugin/cordova-plugin-googlemaps#2624]
First thank you for this great plugin! It is working great for me.

If the device is online when I start the app, everything works correctly: the map is displayed as it should.

Now if the plugin is initialized (i.e. `this.map = GoogleMaps.create(element, googleMapOptions);`) while the device is **offline**, and then if I activate the wifi few seconds later the map is never displayed. It is always gray. In this case, I have to force stop the app and start it again to see the map.

Do you know if I'm doing something wrong? Should I initialize the plugin only if the device is online?

**Comment by wf9a5m75** [comment]
You must activate `online` first time.

**Comment by francoisduchemin** [comment]
Thanks for your answer. I'm not 100% sure what you mean. Do you mean I should call `GoogleMaps.create()` only if the device is online?

**Comment by wf9a5m75** [comment]
The Google Maps SDK for iOS communicates with Google server when the map view is created only first time. Because the SDK does not has tile data, also SDK has not initialized.

After the first initialization, you can open your app even with offline (but map tile is displayed only cached area).

This is the native SDK behavior. Not this plugin, no workaround.

**Comment by francoisduchemin** [comment]
Thanks again.
So if I understand correctly, I should initialize the map view only **once** and only if the device is **online**. Is this correct?

**Comment by wf9a5m75** [comment]
Yes. At least once.
