### ISSUE TITLE
What is the difference between the main branch and the `multiple-maps` branch?

### ISSUE THREAD

**Issue by spinninghamster** [mapsplugin/cordova-plugin-googlemaps#2687]
What is the difference of the `multiple-maps` branch? I looked for separate documentation but couldn't find any.

**Comment by wf9a5m75** [comment]
Stable or development

**Comment by spinninghamster** [comment]
And I always thought `multiple-maps` allows you to run multiple maps in the app, while the main branch allows you to run only 1 map...

**Comment by wf9a5m75** [comment]
Main branch is also able to create multiple map.

**Comment by Mapiac** [comment]
@spinninghamster its just not the best name IMHO as it's a confusing name when you use a single map, as a very many people do in order to avoid map transition flashes and other issues. But the plugin is meant primarily for multiple maps although that focus may have changed over the years I'll leave to @wf9a5m75 to speak on should he care too. So even if you are using 1 map, you are likely using the 'multiple map' branch if you're on latest.
