### ISSUE TITLE
[Request] MarkerClusters using a marker field, not number of markers

### ISSUE THREAD

**Issue by rcpinheiro** [mapsplugin/cordova-plugin-googlemaps#2700]
**Please tell us your new feature idea**
Instead of showing the number of markers in a cluster, having the option to show a number according to a marker field.

**Why do you need it?**
When you have markers with numbers, it's more useful for MarkerClusters to add the numbers instead of showing the number of markers -  which could be confusing.

**How helps other people?**
I think everyone that have markers with number will appreciate this :)

**How to do it**
I've done a quick (working) demo to show how it should work. Add a numeric field to a marker (in this case "number"):

In your script:
```
    var marker={
                position: { lat:___, lng:___ },
                map: map,
                number: some_number,
                [...]
    }
    cluster.push(marker);
```
 
 In MarkerClusters.js:962
```
        unionedMarkers.forEach(function (cluster) {
          var number=0;
          for (var f=0;f<cluster._markerArray.length;f++) {
              if (typeof cluster._markerArray.[f].get('number')!=undefined) {
                  number+=parseInt(cluster._markerArray[f].get('number'));
              }
          }

          if (!number) number=cluster.getItemLength(); // Revert to number of markers
          var icon = self.getClusterIcon(cluster),
            clusterOpts = {
              'count': number,
              'position': cluster.getBounds().getCenter(),
              '__pgmId': cluster.getId()
            };
```

Of course, the name of the parameter (in this case "number"), should be parametrized when creating a MarkerCluster and, again, the icons min/max parameters should use the addition of the fields and not the number of markers.

If there are more people interested, I may create a pull request for this feature, when time permits.

**Comment by wf9a5m75** [comment]
I think your idea causes me confusing.
As far as I know, all marker clusters shows the `number of clustered markers` on the marker cluster icon, which means there are the `number of markers` are existed in the clustered area.

And I've never seen using `number` field in any projects. Most projects uses `id` field, which is typically string.

Since this plugin provides under the `Apache license 2.0`, you can modify the code, using it in your personal/commercial product (but you must keep the original copyright name).
It means the license allows you to create original version.

So customization on forked repository is fine, but I'm (probably) not going to merge your pull request if you send it.

**Comment by rcpinheiro** [comment]
Consider this use case:
You have a map where the markers are cinemas. Each marker has a number corresponding to the number of screens. For instance, if there are 5 cinemas in a neighborhood with a total of 20 screens, you'll see just 5 markers instead of 20. 
The default behavior is for the MarkerCluster to show just the 5 markers ("cinemas") instead of 20 ("screens") which can be confusing. 

Of course you could add all the 20 markers to the MarkerCluster but it's resource-intensive when you have a large number of markers.

**Comment by wf9a5m75** [comment]
> You have a map where the markers are cinemas. Each marker has a number corresponding to the number of screens. For instance, if there are 5 cinemas in a neighborhood with a total of 20 screens, you'll see just 5 markers instead of 20.

In this case, I would like to know the number of cinemas `5` instead of `20`.

As I said, you can modify on your forked repo.

**Comment by rcpinheiro** [comment]
> In this case, I would like to know the number of cinemas `5` instead of `20`.

Sometimes, it's more useful to know the total number. In this example, if you like choice you'll prefer going to a place where are 40 screens and 3 cinemas than going to someplace with just 20 screens and 5 cinemas.

**Comment by wf9a5m75** [comment]
In the U.S., there are ton's of Starbucks.

Each Starbucks has different number of chair because store's dimensions are different.
Do you want to know the `number of chairs` in particular area instead of `number of Starbucks`?

---------

So I allowed you to modify on your repo, but I don't agree your idea is useful for all other people.
You don't need to send your code to this repo.
