### ISSUE TITLE
Both Android and IOS maps are crashing at initialization - is it a global Google issue?

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#2766]
**I'm submitting a ...**  (check one with "x")
- [X] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**
- [ ] **Browser**

Just asking the community if you are experiencing a global crash of your app using the Google Maps plugin on both Android and IOS. Crashlytics is full of Google Maps-related errors. No new software version was released, last one was released few weeks ago and no change was made. Are you guys experiencing the same?

**Comment by ndrake** [comment]
https://twitter.com/JStheoriginal/status/1253415465243697161

**Comment by umrysh** [comment]
I had my app installed on a few different devices and the device that started crashing has now started working after I uninstalled and reinstalled my app. The other installations (which were not opened during the outage) are working without issue. Just sharing in case this helps anyone

**Comment by wf9a5m75** [comment]
> I update http://com.google.android .gms:play-services-maps:16.0.0 to http://com.google.android .gms:play-services-maps:17.0.0 and works for me

<img width="554" alt="Screen Shot 2020-04-23 at 4 46 14 PM" src="https://user-images.githubusercontent.com/167831/80160245-fa9ba080-8581-11ea-9623-67d1255a07e3.png">

Try this, please.

**Comment by battika** [comment]
I'm already on Play Services 17..0.0. and it seems the outage is over.

Thanks for the discussion, closing issue.

**Comment by spacesuitdiver** [comment]
Interestingly, even though this is a global Google Maps issue on Android in order to fix the issue even though Google fixed it on their server side we have to tell all of our customers to clear their app storage for it to be fixed as of now. 

Depending on the direction decided on our team we are likely going to end up forking this plugin or making a new plugin to clear google map's storage as described in this thread:

https://issuetracker.google.com/issues/154855417#comment179
