### ISSUE TITLE
Possible issue with map hit testing

### ISSUE THREAD

**Issue by yiannis-spyridakis** [mapsplugin/cordova-plugin-googlemaps#2786]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-admob-sdk 0.24.1 "AdMob SDK"
cordova-admob-sdklibs 2.1.6 "Google Mobile Ads SDK for Cordova"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-admob-free 0.27.0 "Cordova AdMob Plugin"
cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 5.0.7
@ionic-native/google-maps : 5.5.0
```

**Current behavior:**
I observe intermittent crashes when clicking on polylines on the map when multiple polylines are displayed simultaneously.

**Expected behavior:**
No crash.

I have debugged the app with Android Studio and I get the following stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bmi.evaluway, PID: 8923
    java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
        at plugin.google.maps.PluginMap.onOverlayEvent(PluginMap.java:2444)
        at plugin.google.maps.PluginMap.onPolylineClick(PluginMap.java:2450)
        at plugin.google.maps.PluginMap$33$1.run(PluginMap.java:3158)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 8923 SIG: 9
```
The problem is that an invalid point is passed up the stack.
By looking at the code here https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/de0bee2d8bd2d3f6232741fbf84497a49435c408/src/android/plugin/google/maps/PluginMap.java#L3076
I believe that the problem is in the fact that when a polyline is matched with the point the loop continues:
```
                  if (touchPoint != null) {
                    hitOverlay = polyline;
                    maxZIndex = zIndex;
                    continue;
                  }
```
and `touchPoint` can become null while `hitOverlay` isn't. I think `continue` should be `break` in this case, can you have a look?

**Comment by wf9a5m75** [comment]
Please provide example code for test

**Comment by wf9a5m75** [comment]
ping

**Comment by yiannis-spyridakis** [comment]
I will try to provide an example within the next day - I didn't get the chance to do so yet.

**Comment by wf9a5m75** [comment]
Ok, thank you.

**Comment by yiannis-spyridakis** [comment]
Hi,
Here is a repro Ionic 5 project:
https://github.com/yiannis-spyridakis/google-maps-bug-repro

To run replace YOUR_GOOGLE_MAPS_API_KEY with a valid api key in both package.json and config.xml.

To replicate the issue just click back and forth between the two created polylines a couple of times and the app should crash with the error posted above.

**Comment by wf9a5m75** [comment]
Thank you for preparing the project. I will check it later

**Comment by yiannis-spyridakis** [comment]
Thanks

**Comment by yiannis-spyridakis** [comment]
The issue appears to exist in the polyline case only and is a result of the fact that the return value of `isPointOnTheGeodesicLine` and `isPointOnTheLine` is directly assigned to variable `touchPoint`, which means `touchPoint` can get out of sync with `hitOverlay` as the loop continues in the search for matches with greater z-index.
The modification below appears to fix the issue and should have no other side effects:

```
if (polyline.isGeodesic()) {
  hitArea.x = (int)(polyline.getWidth() * density);
  hitArea.y = hitArea.x;
  double threshold = calculateDistance(
    projection.fromScreenLocation(origin),
    projection.fromScreenLocation(hitArea));
  LatLng polyTouchPoint = isPointOnTheGeodesicLine(points, point, threshold);
  if (polyTouchPoint != null) {
    touchPoint = polyTouchPoint;
    hitOverlay = polyline;
    maxZIndex = zIndex;
    continue;
    }
  } else {
    LatLng polyTouchPoint = isPointOnTheLine(points, point);
    if (polyTouchPoint != null) {
       touchPoint = polyTouchPoint;
       hitOverlay = polyline;
       maxZIndex = zIndex;
       continue;
    }
  }
```

**Comment by wf9a5m75** [comment]
Sorry. I'm so busy recently. I haven't tested this yet

**Comment by yiannis-spyridakis** [comment]
OK, ping me if you need anything further on my end.

**Comment by wf9a5m75** [comment]
Thank you. I will work on this today

**Comment by 8bhsolutions** [comment]
@yiannis-spyridakis 
Thanks for producing the test project.

I believe you need also include additional code to keep track of the closest point to the user touch point.
https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2777#issuecomment-638558468

**Comment by tgleb** [comment]
After updating from the repo, markers are no longer displayed and map is missing all the usual details - street names, places names, etc.. getting error below on Android:

07-12 11:15:31.530 25683 26093 W Glide   : Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
07-12 11:15:31.553 25683 25683 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
07-12 11:15:31.553 25683 25683 I art     :   at int androidx.core.view.ViewCompat.getImportantForAccessibility(android.view.View) (ViewCompat.java:1064)
07-12 11:15:31.553 25683 25683 I art     :   at void androidx.customview.widget.ExploreByTouchHelper.<init>(android.view.View) (ExploreByTouchHelper.java:148)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.it.zzbd.<init>(android.view.View, com.google.android.libraries.maps.it.zzcs$zza) (GoogleMapTouchHelper.java:1)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzcm com.google.android.libraries.maps.gu.zzat.zza(java.lang.String, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf, android.view.View, com.google.android.libraries.maps.it.zzt, android.widget.TextView, com.google.android.libraries.maps.it.zzck, com.google.android.libraries.maps.it.zzaw, com.google.android.libraries.maps.it.zzej, boolean, com.google.android.libraries.maps.it.zzd, com.google.android.libraries.maps.it.zzu, boolean, com.google.android.libraries.maps.it.zzbk) (RendererFactoryImpl.java:271)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzav com.google.android.libraries.maps.it.zzav.zza(com.google.android.libraries.maps.GoogleMapOptions, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf) (GoogleMapImpl.java:59)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzbh com.google.android.libraries.maps.it.zzcp.zza(com.google.android.libraries.maps.GoogleMapOptions, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf) (MapViewDelegateImpl.java:3)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.it.zzcq.zza(android.os.Bundle) (MapViewDelegateImpl.java:11)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView$zza.onCreate(android.os.Bundle) (MapView.java:6)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.zad.zaa(com.google.android.gms.dynamic.LifecycleDelegate) (com.google.android.gms:play-services-base@@17.3.0:3)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.zab.onDelegateCreated(com.google.android.gms.dynamic.LifecycleDelegate) (com.google.android.gms:play-services-base@@17.3.0:4)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView$zzb.createDelegate(com.google.android.gms.dynamic.OnDelegateCreatedListener) (MapView.java:16)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(android.os.Bundle, com.google.android.gms.dynamic.DeferredLifecycleHelper$zaa) (com.google.android.gms:play-services-base@@17.3.0:18)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(android.os.Bundle) (com.google.android.gms:play-services-base@@17.3.0:22)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView.onCreate(android.os.Bundle) (MapView.java:26)
07-12 11:15:31.553 25683 25683 I art     :   at void plugin.google.maps.PluginMap$1.run() (PluginMap.java:285)
07-12 11:15:31.553 25683 25683 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
07-12 11:15:31.553 25683 25683 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
07-12 11:15:31.553 25683 25683 I art     :   at void android.os.Looper.loop() (Looper.java:154)
07-12 11:15:31.553 25683 25683 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
07-12 11:15:31.553 25683 25683 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-12 11:15:31.553 25683 25683 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
07-12 11:15:31.553 25683 25683 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
07-12 11:15:31.553 25683 25683 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.bmi.evaluway-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bmi.evaluway-1/lib/arm, /data/app/com.bmi.evaluway-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
07-12 11:15:31.553 25683 25683 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
07-12 11:15:31.553 25683 25683 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
07-12 11:15:31.553 25683 25683 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
07-12 11:15:31.553 25683 25683 I art     :   at int androidx.core.view.ViewCompat.getImportantForAccessibility(android.view.View) (ViewCompat.java:1064)
07-12 11:15:31.553 25683 25683 I art     :   at void androidx.customview.widget.ExploreByTouchHelper.<init>(android.view.View) (ExploreByTouchHelper.java:148)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.it.zzbd.<init>(android.view.View, com.google.android.libraries.maps.it.zzcs$zza) (GoogleMapTouchHelper.java:1)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzcm com.google.android.libraries.maps.gu.zzat.zza(java.lang.String, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf, android.view.View, com.google.android.libraries.maps.it.zzt, android.widget.TextView, com.google.android.libraries.maps.it.zzck, com.google.android.libraries.maps.it.zzaw, com.google.android.libraries.maps.it.zzej, boolean, com.google.android.libraries.maps.it.zzd, com.google.android.libraries.maps.it.zzu, boolean, com.google.android.libraries.maps.it.zzbk) (RendererFactoryImpl.java:271)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzav com.google.android.libraries.maps.it.zzav.zza(com.google.android.libraries.maps.GoogleMapOptions, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf) (GoogleMapImpl.java:59)
07-12 11:15:31.553 25683 25683 I art     :   at com.google.android.libraries.maps.it.zzbh com.google.android.libraries.maps.it.zzcp.zza(com.google.android.libraries.maps.GoogleMapOptions, com.google.android.libraries.maps.it.zzar, com.google.android.libraries.maps.it.zzf) (MapViewDelegateImpl.java:3)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.it.zzcq.zza(android.os.Bundle) (MapViewDelegateImpl.java:11)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView$zza.onCreate(android.os.Bundle) (MapView.java:6)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.zad.zaa(com.google.android.gms.dynamic.LifecycleDelegate) (com.google.android.gms:play-services-base@@17.3.0:3)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.gms.dynamic.zab.onDelegateCreated(com.google.android.gms.dynamic.LifecycleDelegate) (com.google.android.gms:play-services-base@@17.3.0:4)
07-12 11:15:31.553 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView$zzb.createDelegate(com.google.android.gms.dynamic.OnDelegateCreatedListener) (MapView.java:16)
07-12 11:15:31.554 25683 25683 I art     :   at void com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(android.os.Bundle, com.google.android.gms.dynamic.DeferredLifecycleHelper$zaa) (com.google.android.gms:play-services-base@@17.3.0:18)
07-12 11:15:31.554 25683 25683 I art     :   at void com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(android.os.Bundle) (com.google.android.gms:play-services-base@@17.3.0:22)
07-12 11:15:31.554 25683 25683 I art     :   at void com.google.android.libraries.maps.MapView.onCreate(android.os.Bundle) (MapView.java:26)
07-12 11:15:31.554 25683 25683 I art     :   at void plugin.google.maps.PluginMap$1.run() (PluginMap.java:285)
07-12 11:15:31.554 25683 25683 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
07-12 11:15:31.554 25683 25683 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
07-12 11:15:31.554 25683 25683 I art     :   at void android.os.Looper.loop() (Looper.java:154)
07-12 11:15:31.554 25683 25683 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
07-12 11:15:31.554 25683 25683 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-12 11:15:31.554 25683 25683 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
07-12 11:15:31.554 25683 25683 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
07-12 11:15:31.554 25683 25683 I art     :

**Comment by tgleb** [comment]
Here is output of **ionic info ** command
>ionic info

Ionic:

   Ionic CLI                     : 6.6.0 (C:\Users\tgleb\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (C:\Users\tgleb\AppData\Local\Android\sdk)
   NodeJS            : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.
And I think your problem is not related with this issue.
Don't jump on other person's issue.

**Comment by tgleb** [comment]
This is the same project and issue that @yiannis-spyridakis started as a bug since we had a problem with multiline directions in android. I downloaded the latest updates as per his advice on the project under discussion, and now there are no markers on Android, IOS is fine. There is no jumping here, just continuation of the same issue, same project.

**Comment by tgleb** [comment]
And I am using this inside my package.json "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",

**Comment by tgleb** [comment]
Is there a specific tag I should be using or as the development moves the head I might be getting the latest code that has the issues..I am not familiar with this style of using plugins.

**Comment by tgleb** [comment]
Hmm, I just reinstalled, tested on Android and it worked..I guess it did not have the fix when I downloaded it the first time around. 
Thank you very much guys. cheers :) 

ionic cordova plugin rm cordova-plugin-googlemaps
$> ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps

**Comment by wf9a5m75** [comment]
Your first error log says your app tried to involve the class of AndroidX but it is not included.

The original issue is null pointer error. It's completely different problem.
Error logs are completely different.

The code of the multiple_maps branch supports the AndroidX, that's why you can see the maps now.

**Comment by tgleb** [comment]
That is correct, the original issue was google-map NPE, and the subsequent problem occurred after I updated the code with the version that did not support AndroidX. Once I got the correct branch, it worked. It was a strange issue because I could see the map, only no details, such as street name and no marker...just map with the streets.

**Comment by tgleb** [comment]
After using the latest see below, there is similar issue on iOS, and the user can't switch between the routes. Android works.
You can use the same project as provided by Ioannis.
Thank you.

ionic cordova plugin rm cordova-plugin-googlemaps
$> ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
