### ISSUE TITLE
Read the latitude and longitude of a Base Array Class PolyLine

### ISSUE THREAD

**Issue by jomego** [mapsplugin/cordova-plugin-googlemaps#2787]
**I'm submitting a ...**  (check one with "x")
- [X ] question
- [ ] any problem or bug report

**Current behavior:**

I am trying to get the latitude and longitude of a Polyline to know its start and end point .. I create it with a BaseArray but I cannot retrieve that information to put it in two different variables.
I am doing this:

```js
linea1.setPoints(datos_linea_1);
var mvcArray8 = linea1.getPoints();
var point1 = mvcArray8.get(0); 
var point2 = mvcArray8.get(mvcArray8.getLength() - 1);
 alert(point1.lat + " "+ point1.lng);
 alert(point2.lat + " "+ point2.lng);
```
**

**Expected behavior:**

How can I retrieve those values to some variables

**Comment by wf9a5m75** [comment]
Use `getAt()` instead `get()`

Since the `BaseArray` class extends `BaseClass`, it has `set() / get()` methods.
To manipulate the values of array, you need to use `push(), insertAt(), setAt(), getAt()`

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/getAt/README.md

**Comment by jomego** [comment]
Thanks.
