### ISSUE TITLE
How to install this plugin for Meteor cordova project?

### ISSUE THREAD

**Issue by ghost** [mapsplugin/cordova-plugin-googlemaps#307]
Hello,

I need to add your plugin to a Meteor project, but "Meteor add cordova:..." doesn't accept a --variable parameter.
My idea was to manually add the ANDROID_API_KEY to the plugin.xml-file. But what do I need to change so the plugin doesn't expect a variable?

**Comment by twavis** [comment]
I wanted to post this for anybody looking to get this plugin working with meteor and crosswalk. 

Crosswalk merged the fix to allow 'xwalkZOrderOnTop' preference being set, with this commit https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/985d6f5518ca5223ad00fe1ad5da899c607b6105

So if you want to use cordova-plugin-googlemaps with meteor and crosswalk, you need to install crosswalk from at least that commit or newer.

Then add this to your mobile-config.js
App.setPreference('xwalkZOrderOnTop', true);

Also, I am using the latest commit of cordova-plugin-googlemaps.

Final thing is modifying the AndroidManifest.xml just as described in the crosswalk how to tutorial step #5..
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29

Meteor doesn't replace the AndroidManifest.xml if it already exists so you can edit it (change "Black" to "Translucent") and rebuild and you should now be able to see the map finally! If anybody knows of a better, less hackish way to do this, that works with clean build, let me know please.

Oh, and if using ionic/meteoric, note the ionic fixes/workarounds listed under troubleshooting and tips. Essentially the side menus aren't made transparent by the map because they aren't part of parent node, so you have to figure a method to handle side menu visibility when using the map.

Good luck! The speed difference is huge and having this work with crosswalk was a deal breaker... now back to the less frustrating stuff :)

**Comment by Hirbod** [comment]
Yeah, I was on that commit inside of the comments :)
Thanks for the howto!

```xml
        <preference name="xwalkZOrderOnTop" value="true" />
```

**Comment by twavis** [comment]
Yeah Hirbod. I wouldn't have figured it out without all of your hard work. Thanks :)
