### ISSUE TITLE
Use current camera values on Map.animateCamera() if properties are not defined

### ISSUE THREAD

**Issue by erasmo-marin** [mapsplugin/cordova-plugin-googlemaps#578]
When you use `Map.animateCamera()` with something like this, where some values like tilt and zoom are not defined, the camera uses default values instead current camera values. I think this behavior is not the expected behavior.
```javascript
var GOOGLE = new plugin.google.maps.LatLng(37.422858, -122.085065);
map.animateCamera({
  'target': GOOGLE,
  'bearing': 140,
  'duration': 5000 // = 5 sec.
}, function() {
  console.log("The animation is done");
});
```
The only way to workaround this getting camera position with `getCameraPosition()`, because there are no  `getZoom()` or  `getTilt()` functions available. I think the API can be improved a lot.

```javascript
map.getCameraPosition(function(camera) {
   map.animateCamera({
     'target':  GOOGLE,
     'duration': 5000,
     'zoom': camera.zoom,
     'bearing': 140,
      'tilt':camera.tilt
    });
});
```

**Comment by Hirbod** [comment]
Don't hesitate to provide a pull request.

**Comment by erasmo-marin** [comment]
I'm not going to make a pull request if it's not considered as a bug

**Comment by Hirbod** [comment]
IMHO it is not really a bug - but not user friendly.

**Comment by erasmo-marin** [comment]
We don't have the same idea of what a bug is but at least we agree this is a problem :)

**Comment by Hirbod** [comment]
@erasmo-marin would you like to submit a PR? Would love to merge it.

**Comment by erasmo-marin** [comment]
@Hirbod Yeahh, I want to, but I don't have any ios devices to test or a mac to emulate anymore... I only can test for android, what I do? It's something easy to do, at least, is what I think after reading the source code.. is frustrating...

**Comment by Hirbod** [comment]
@celron 

If you want to help, you could dig into this problem and submit a PR

**Comment by Hirbod** [comment]
This should be done in 5-10 minutes, just small changes in the JS-Call

**Comment by celron** [comment]
Sorry @Hirbod I didn't realize your comment to me until just now, github can send too many mails.  I will try to do better next time, since I would like to help

**Comment by Hirbod** [comment]
@celron actually, I did not start fixing this, give it a try if you can :)

**Comment by celron** [comment]
@Hirbod I took a look at the underlying code in android and ios and the google documentation.
In general, the plugin is a lightweight wrapper that is designed to normalize calls between ios and android.

The google maps api on Android, seems to use the parameters are used if given.  On iOS, the api assums that all the parameters are given due to the language requirements.  While not specified, I think the OP is seeing the problem on iOS.

To **fix** this would require that the plugin keeps track or query the camera position, the way @erasmo-marin mentions, which I'm not sure the plugin should do since it is state information, would not necessarily a lightweight solution for iOS.  It would have to do it every time the camera is animated or moved.

In my own app, I do this when I need to already, I'm not sure if I would want the plugin to do this all the time.

Alternatively a better solution would probably be to expose the individual camera parameters that the users can programmatically manipulate, which is a longer term solution.

**Comment by Hirbod** [comment]
I will only patch the JS.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L446-L475

I will just check if target.zoom and target.tilt is set, if not, I'll grab the current value using this.getCameraPosition() and push it into the object.

**Comment by Hirbod** [comment]
postpone v.1.3.4

**Comment by Hirbod** [comment]
In current master:
map.animateCamera() and map.moveCamera() will now use the current defaults, when not provided.

also added
```js
map.getZoom(function(zoom){
   console.log(zoom);
});
map.getTilt(function(tilt){
   console.log(tilt);
});
map.getBearing(function(bearing){
   console.log(bearing);
});
```
