### ISSUE TITLE
CrossWalk, Google Maps Plugin and SplashScreen results in a white screen overlay

### ISSUE THREAD

**Issue by pbrisson** [mapsplugin/cordova-plugin-googlemaps#638]
Hello,

First, I know this has been discussed previously in multiple issues; I dug all reported issues and unfortunately couldn't find a solution to what I'm experiencing.

I'm using Crosswalk on Android 4.1.1. Here's my list of installed plugins:

    cordova-plugin-console 1.0.1 "Console"
    cordova-plugin-crosswalk-webview 1.3.1 "Crosswalk WebView Engine"
    cordova-plugin-device 1.0.1 "Device"
    cordova-plugin-splashscreen 2.1.0 "Splashscreen"
    cordova-plugin-whitelist 1.0.0 "Whitelist"
    plugin.google.maps 1.3.1 "phonegap-googlemaps-plugin"

As you can see, I have both splashscreen and whitelist installed, so it's unrelated to previous issues.

In order to replicate, follow instructions here: https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29

Everything works fine after compiling project after these steps.

You can replicate the issue by commenting the line:

    map = plugin.google.maps.Map.getMap(div);

Doing so will result of a white screen staying over the webview after splashscreen is hidden. There's no way to hide it. My assumption was that it could be CrossWalk splashscreen not getting first paint event so that it's not getting hidden, but I'm not sure.

I tried a bunch of things to solve this, but has been unsuccessful so far.

My issue is that I'm having a home screen on my app that allows the user to select various options before the map is shown, so there's no need to initialize the map plugin until these options has been set. Doing so result is this white screen overlay; it seems the google maps plugin absolutely has to initialized on the first screen for this to be gone.

I'm callling it an overlay because the white screen is only hiding the webview; it's still getting clicks! So if I get the overlay, then clicks on the area where a button is supposed to be, it gets me to the second screen where the map is initialized and the white screen disappears.

Please note if I launch the app on my phone (Samsung Galaxy S5), and that the lock screen is still active when I'm launching the app, I'm not a able to replicate; I need to see the splashscreen of the app while it is being launched to be able to get this white screen.

Any ideas?

Thanks for your time!

**Comment by Hirbod** [comment]
Just as a quick workaround: initialize it first and hide / remove the map afterwards. Not really nice, but would this fix you problem?

I'm on OnsenUI + Splashscreen, Crosswalk and you're right, my map is on the first screen, maybe that's the reason I do not have any problems.

**Comment by pbrisson** [comment]
Thanks for your suggestion!

Unfortunately I already tried it; the overlay is gone, but the text inputs that are visible on the first screen are not clickable if I do this. That's why I was looking for another solution.

**Comment by Hirbod** [comment]
Just call map.setClickable(false) and, when you're ready for map-input, map.setClickable(true) (after form subit e.g)

**Comment by pbrisson** [comment]
Setting map.setClickable(false); did not work, but a simple "display: none;" on the map DIV worked!

Thanks for your time @Hirbod I really appreciate! Has been struggling with this issue for the weekend...

**Comment by Hirbod** [comment]
You're welcome.

**Comment by ma-pe** [comment]
This behavior is new. I can confirm this. In previous Versions (when this tutorial was created https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-(Android)#5-change-the-androidmanifestxml-mainactivityjava-and-xwalkwebviewenginejava) - there was no white overlay. But when I do all the steps as described in the tutorial with a more current version of this plugin, I also get a white screen.

**Comment by jheissat** [comment]
Hello. Thanks a lot for taking the time to contribute to this plugin.

I am facing the same issue as @pbrisson was. I have fixed it the same way.

However, there is still a white overlay  in the first 3/4 seconds when my application is launched. It seems directly to this issue. Are you encountering the same problem ? Would you know the reason for this white overlay ?

**Comment by Hirbod** [comment]
Could you provide a video for me?

**Comment by jheissat** [comment]
Thanks @Hirbod. Here is a quick video: https://youtu.be/-cQIY6MQjuA

The application is starting ok but at second 3 there is a white screen that popups during half a second which was not appearing before updating this plugin.

Would it be necessary to keep the splashscreen until the map has been initialized ? Would you know the reason for this white screen ?

**Comment by Hirbod** [comment]
It looks like the splashscreen has the Autohide-value set in config.xml (or by default) and you called show() on deviceready? And again .hide() on map-init?

I'm also on CrossWalk, newest plugin version + newest CLI+Cordova-Android version. I don't have any kind of that issues.

cordova-plugin-splashscreen version is 2.1.0

I've disabled autohide inside of the config.xml and I do hide the Splashscreen manually as soon as my map is ready. I guess you should do the same.


```xml

    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="FadeSplashScreenDuration" value="0.3" />
    <platform name="android">
        <preference name="KeyboardDisplayRequiresUserAction" value="false" />
        <preference name="SplashScreenDelay" value="10000" /> <!-- this is max time, my .hide() method should call before -->
        <preference name="SplashMaintainAspectRatio" value="true" />
        ...
     </platform>

**Comment by lionel-bijaoui** [comment]
Hello, after a lot of test I can finally give a working solution for the white screen after splash screen.
I have tested this with the default cordova project created with `cordova create` command.
I have tested adding plugin after plugin, with `cordova clean` between each build for extra paranoia.

Latest Crosswalk and cordova-plugin-splashscreen don't cause any trouble. I get a splash screen after proper configuration of config.xml.

Then I added the modification from [this tutorial](https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29) one at the time to make sure that messing with java file wasn't the problem. They were not, everything was still fine.

Then I added your plugin, and I immediately got the blank everything after splash screen effect.

Then I added the last step of your tutorial, modifying the html (and code) of the template Cordova project.
And this completely worked. No more blank screen after the splash screen.

So I get curious and tried some stuff:
1. not adding `plugin.google.maps.Map.getMap()` -> blank screen
2. `map = plugin.google.maps.Map.getMap(/*nothing*/)` -> blank screen
3. `map = plugin.google.maps.Map.getMap({.. initialize options [from this](https://github.com/phonegap-googlemaps-plugin/phonegap-googlemaps-plugin/wiki/Map.getMap%28%29#create-a-map-with-initialize-options)... })` -> blank screen
3. `map = plugin.google.maps.Map.getMap(div, {.. initialize options... })` -> work fine, no blank screen
4. Since in my app, I can't initialize in an existing div, I tried with `var tempDiv = document.createElement("div")` and then `map = plugin.google.maps.Map.getMap(tempDiv , {.. initialize options... })` -> work fine, no blank screen, I can just use `setDiv()` when I want to add the map to the dom.

This was exhausting to find the source of this blank screen (I tried a lot of other possibilities before that), so please, could you do what `Map.getMap` do when initialized that remove that blank screen and put it to start by default on app launch ?
Thank you.

**Comment by Hirbod** [comment]
I'll try to dig into this

**Comment by lionel-bijaoui** [comment]
Thank you very much, I love your plugin ! Way better than using the js map api.

**Comment by jheissat** [comment]
@Hirbod Thanks a lot for taking the time to help me on this issue. Your changes indeed helped me to completely disable the white screen. 

FYI, I actually hide the splashscreen on app start and then I use a GIF to display a splashscreen inside my html.

**Comment by canadaka** [comment]
When our app first opens we don't load the map, so we are having the same white screen problem.
There is no other solution currently than loading the map then hiding it?

**Comment by Hirbod** [comment]
I don't have these problems, I don't know what you guys are doing. My first screen is the login screen..

**Comment by canadaka** [comment]
As @lionel-bijaoui mentions you can reproduce with a blank project after adding Crosswalk. Without Crosswalk everything is fine. I tried with many variations of the config.xml preference's none had any effect. Only way i've been able to fix is @lionel-bijaoui fix, which is not ideal.

**Comment by ffabreti** [comment]
I am running on Android + cordova 5 + XWalk 14 + splashscreen + this wonderful plugin.

I had the white screen showing and staying on my App second run. First run was ok. And I don't have map on my first screen. After the first run, always got white screen (even if I did not initialized the map at all). 

I have code which makes my app exit when pressing back-button on android (ionic.Platform.exitApp()).

I have noticed my app got cached by android and after that, I always get a white screen. But, if I go to Android App Manager and remove app from cache, it inits ok (no white screen). But only for the first run, as said before.

What solved the problem was upgrading the splashscreen plugin (which I did not after upgrading to cordova 5.0) from version 1.0.0 to version 2.1.0

Now the second run of my app don't shows the splashscreen, but the white screen goes away after a moment.

**Comment by roberthovhannisyan** [comment]
Hi !
Probably, you should use splashscreen version 2.0.0 instead of latest 2.1.0.
Please see this post:
http://forum.ionicframework.com/t/white-screen-on-splashscreen-after-close-app-by-back/27721

**Comment by ffabreti** [comment]
@roberthovhannisyan
    Oh...Thanks, although I'm not hitting the issue.

**Comment by lionel-bijaoui** [comment]
I can confirm that it fix all problems. Tested on my test project and real project.
But i still think that it need to be fixed, since all future version of the splashscreen plugin will cause problems.
Where is the problem, what cause it ?

**Comment by Hirbod** [comment]
This need a fix, by Apache, not us.
https://issues.apache.org/jira/plugins/servlet/mobile#issue/CB-9374

**Comment by lionel-bijaoui** [comment]
Well, the problem I got were from using function from your plugin, not from using the back button.
For example, the `map.setVisible()` or `map.destroy()` were triggering the white screen.
I'm not blaming your work, I just think that we should help each other on this issue.
Maybe by finding what cause the white screen on your plugin, we can pinpoint what function or event cause the problem ?
At least, we should warn about this bug in the documentation, no ?
Anyway, I respect your choice.

**Comment by Hirbod** [comment]
I've fixed the problem in current master 1.3.5 - grab it, it should not make any problems anymore.

**Comment by Hirbod** [comment]
I've reverted my quick and dirty patch.

**Comment by Hirbod** [comment]
@ everybody - could you try #778 PR / Fork and confirm, that the bugs are fixed for you? If yes, I will merge it.

**Comment by Lomejook** [comment]
##### Results for Fork #778 

I added nothing special to the code, just created a blank ionic project. I tried with crosswalk and a **black screen overlay** appear just after the SplashScreen. I put a button inside and even with the black overlay I can clicked. If I tried without crosswalk the overlay is gone, and everything looks fine.

Tested on:
>Cordova CLI: 5.1.1
Cordova Android: 4.0.2 and 4.1.1
Android: 5.1.0

Installed Plugins:
>com.googlemaps.ios 1.11.1 "Google Map iOS SDK for Cordova"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"
plugin.google.maps 1.3.8 "phonegap-googlemaps-plugin"

**Comment by FmeuMan** [comment]
Black overlay ? Havo you followed these steps ? [Tutorial for CrossWalk Webview Plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29#5-change-the-androidmanifestxml-mainactivityjava-and-xwalkwebviewenginejava)

**Comment by Hirbod** [comment]
It's done! Version 1.3.9 is pushed to master and will be pushed to npm in few minuntes. It finally fixed all WHITE/BLACK/INIT Problems on Android with Crosswalk. Update Plugin to 1.3.9, set Crosswalk settings to 15+ and give it a try. Check out the new tutorial [Tutorial for CrossWalk Webview Plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-CrossWalk-Webview-Plugin-%28Android%29#5-change-the-androidmanifestxml-mainactivityjava-and-xwalkwebviewenginejava)

Actually, in all my testcases, just install the crosswalk-plungin and run it. It should work out of the box. Many thanks @FmeuMan

**Comment by lionel-bijaoui** [comment]
thank you very much, I will try it now !
