### ISSUE TITLE
I can't use `marker.setIcon` to change the color of HTML Colored default marker

### ISSUE THREAD

**Issue by ericprieto** [mapsplugin/cordova-plugin-googlemaps#692]
Hey guys,

I can't use `marker.setIcon` to change the color of HTML Colored default marker, although I can use it to set a image url.

**Comment by arilsonkarmo** [comment]
Can you post your stacktrace? or the javascript code on marker.setIcon?

**Comment by ericprieto** [comment]
There was no error, I just created a marker using `map.addMarker({ icon: 'red' })` and when I use `marker.setIcon('blue')`, nothing happens, but if I use `marker.setIcon('img/marker.png')` it works.

**Comment by arilsonkarmo** [comment]
OK. Did you test in android and iOS? Both have a same problem? I'll try to fix it.

**Comment by ericprieto** [comment]
Ow, I forgot to say that I was using iOS... But no, I haven't tested it on Android, I don't have one :(

**Comment by arilsonkarmo** [comment]
Ok! Get it. just a sec.

**Comment by arilsonkarmo** [comment]
The correct way to pass color is using property iconColor, you are using this marker.setIcon('blue') the correct way to use it is marker.setIcon({iconColor: '#0011ff'}) in the property the correct way is: map.addMarker( 
{
   icon: { 
             iconColor: '#0011ff' 
           }
});

So.. but we have an error on code too. unfortunately this feature not working.
I'm fixing it and I'll push soon as possible

//the wrong code
UIColor *iconColor = [iconProperty valueForKey:@"iconColor"]; //this is a error.. I think it never work before because this code trying to convert string ('blue') to UIColor. lol.
 marker.icon = [GMSMarker markerImageWithColor:iconColor]; //applying color on icon.

You can make a temporary fix replacing your marker.m content with http://pastebin.com/2tGfHD1E

however, I'll push this solution soon as possible.

Thank you for this report. :)

**Comment by ericprieto** [comment]
Thank you for the temporary fix! In my project I'm using canvas renderered markers, but I reported this anyway :P

I wish I knew Obj-C, I would like help with this, but the language looks like chinese for me =\

**Comment by arilsonkarmo** [comment]
@Hirbod can you put some label here? This is a bug on iOS.
