### ISSUE TITLE
OnMapInit is called several times

### ISSUE THREAD

**Issue by Richacinas** [mapsplugin/cordova-plugin-googlemaps#716]
Hello there,

First of all, thanks so much for the amazing work. I came kicked out of the javascript API experience on Cordova as it was eating up memory on my app like crazy.

Basically, I opened this issue to report that the event MAP_READY is being called more and more times as I come back to visit my view. Here is a basic example.
```html
    <div id="map_canvas" styles="width:100%; height: 580px"></div>
    <script>
    // Define a div tag with id="map_canvas"
      var mapDiv = document.getElementById("map_canvas");

      // Initialize the map plugin
      var map = plugin.google.maps.Map.getMap(mapDiv);

      // You have to wait the MAP_READY event.
      map.on(plugin.google.maps.event.MAP_READY, onMapInit);

      function onMapInit() {
        alert("onMapInit");
      }
    </script>
```

**Comment by Hirbod** [comment]
The event wont overwrite, so you will register multiple events. Just use .one() instead of .on()

This should fix your problem.

**Comment by Richacinas** [comment]
You are totally right!

Maybe the documentation on 

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map

should be updated so it doesn't happen to more people when trying to test the plugin. 

Thanks a lot!

**Comment by Hirbod** [comment]
:+1:

**Comment by apptum** [comment]
I had the same problem and switching to '.one()' solved it.
But airplane mode seems to interfere:
Last night I kept the app running (already in background for several hours (see below)) and this morning the event has fired at least 3 times (I use a custom myLocation marker that gets build after onMapReady() and there were four of them).
From my logs I can tell that the onMapReady callback got called:
- (in the night) after I turned on airplane mode
- (this morning) when my alarm rang (bevor I turned airplane mode off)
- (later this morning) after I turned off airplane mode.
The strange thing is that I can't reproduce by switching airplane mode on and off. I think it might have something to do with doze mode?
For background location I use this plugin [cordova-plugin-background-geolocation](https://github.com/mauron85/cordova-plugin-background-geolocation) and it works quite well and does not seem to be the problem, because only this plugins 'MAP_READY' fires, nothing bevor. Any Ideas? I'm on a Nexus 5x with Android 7.0.
