### ISSUE TITLE
Getting the map to work in a modal

### ISSUE THREAD

**Issue by joggino** [mapsplugin/cordova-plugin-googlemaps#727]
Would the map work in a modal if the view behind it was also transparent (and the content was non-visible)?

I need to place it in a modal for design reasons, therefore I'm planning on making a transparent plugin if this would work, as to make the view behind transparent when the modal is open.

**Comment by Hirbod** [comment]
You won't be able to use it inside of a modal.

**Comment by joggino** [comment]
Is this due to the page behind it being opaque? or the functionality?

**Comment by Hirbod** [comment]
The native map-view is placed behind the native webview (since version 1.2.0+)
So technically, it's not possbile to show it in a modal (only when you visually fake it, but you would have to make sure, that there will be no elements before of it.)

You should consider using Google Maps JS V3 instead.

**Comment by herve1976** [comment]
any change on this matter?

**Comment by wf9a5m75** [comment]
Additional explain. In order to display modal map, I still remain `map.showDialog()`. Please use this one.
