### ISSUE TITLE
How to resize canvas?

### ISSUE THREAD

**Issue by olaferlandsen** [mapsplugin/cordova-plugin-googlemaps#736]
I try edit the height of canvas like to `$('#canvas').css('height', '200px')`, but this dont work.
And try with `document.getElementById('canvas').style.height='200px'` but dont work.

I learn about `map.refreshLayout()`, but this dont have effect.

Example:
```javascript
$('a#resize-map').click(function(){
    map.setVisible(false); // I don't think it necessary to use this function.
    $('#canvas').css('height', '200px');
    map.refreshLayout();
    map.setVisible(true);// I don't think it necessary to use this function.
    return false;
});
```
```html
<html>
    <head>
        ...
    </head>
        <body>
        <div id="canvas"></div>
        <a href="#" id="resize-map">Resize canvas</a>
    </body>
</html>
```

I use jQuery.
Thanks a lot!

**Comment by Hirbod** [comment]
Please use Google or stackoverflow when you have non plugin related questions.

http://lmgtfy.com/?q=Change+canvas+size+jquery

**Comment by olaferlandsen** [comment]
No, you dont understand me: when i try change the div-canvas height,  it change(the div), but the native map(layer) dont apply change. So, do you have a method for this?
I found on Map class the method private "resizeMap".

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L781

**Comment by sam-lex** [comment]
Hi @olaferlandsen , were you able to resize it?
I'm trying to resize the map using ng-class, based on the given condition the map would take 100% heigh etc. It was working with the JavaScript Web GMap.

I am changing to this plugin due to the performance in mobile devices...

I've tried making the map not visible and visible again in an attempt to re-draw it. the .refreshLayout() method didn't changed anything.

Is there a proper (cheaper) way to re-draw the map? what I think the current available solution would be destroying the map and re-creating it again.

**Comment by itanhduy** [comment]
Call `cordova.fireDocumentEvent('plugin_touch', {});`

**Comment by Hirbod** [comment]
The question was version 1.4 related, fireDocumentEvent is only for the new version

**Comment by amirul1000** [comment]
itanhduy commented on Oct 18, 2017
Call cordova.fireDocumentEvent('plugin_touch', {});

that work for me after long suffer
