### ISSUE TITLE
Blank (transparent) map

### ISSUE THREAD

**Issue by lionel-bijaoui** [mapsplugin/cordova-plugin-googlemaps#760]
I made the terrible mistake of updating cordova, and now, after updating every single plugin, I get no map.
I'm able to get `MAP_READY` event, everything is transparent, and the map itself is transparent.
I feel bad right now... :disappointed: 
What version of cordova/plugins should I use for everything to work again ?

**Comment by Hirbod** [comment]
Newest cordova works well with this Plugin.

**Comment by lionel-bijaoui** [comment]
Please tell me if something is wrong here (any incompatibility ?) :

cordova@5.4.1
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-storage 1.0.4 "Chrome Apps Storage API"
cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-device-motion 1.1.1 "Device Motion"
cordova-plugin-geolocation 2.0.0 "Geolocation"
cordova-plugin-shake 0.5.3 "Shake Gesture Detection"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-vibration 2.0.0 "Vibration"
cordova-plugin-whitelist 1.2.0 "Whitelist"
plugin.google.maps 1.3.6 "phonegap-googlemaps-plugin"

**Comment by Hirbod** [comment]
I guess you made something wrong on the Crosswalk Tutorial.

Try

```xml
        <preference name="xwalkZOrderOnTop" value="true" />
```

inside your config.xml

**Comment by lionel-bijaoui** [comment]
I have reinstalled and can confirm that everything (step 5) still need to be done for the plugin to work. The message in the beginning of the tutorial is misleading a bit.
Sorry for the false alarm, I was tired yesterday.
Thank you for your help.

**Comment by Hirbod** [comment]
Thanks. Weird, cause genymotion it works just by installing

**Comment by Hirbod** [comment]
I will change the text

**Comment by heddi** [comment]
Hello there,

i'm also having trouble with blank map.
using : 
- genymotion with android 4.3 - API 18
- crosswalk 15+
the maps got blank 
(black background when using android:theme="@android:style/Theme.Black.NoTitleBar")
(transparent background when using android:theme="@android:style/Theme.Translucent.NoTitleBar")

but its works fine on android 4.4.4 and android 5.1.0
i dont know what was wrong.. since i did not have experience in java

i attach the screenshot

![screenshoot-11-12-2015-21-20](https://cloud.githubusercontent.com/assets/1647055/11745837/6ee59fe6-a04d-11e5-922f-41dab199aade.png)

sorry for bad english..

**Comment by Hirbod** [comment]
should be fixed in master
