### ISSUE TITLE
Map drag events

### ISSUE THREAD

**Issue by denkomanceski** [mapsplugin/cordova-plugin-googlemaps#844]
Is there any other way how to track "dragstart" and "dragend" event on the map ?
I can see the CAMERA_CHANGE event but I cannot find a way how to manipulate this one to understand when someone started/stopped dragging the map. 

I need this so when the user stops the dragging I check for the center coordinate and query the server.

Thanks

**Comment by celron** [comment]
I would implement a timer with a timeout of half a second or so which will get reset otherwise if the user keeps dragging, something like
````
map.on(plugin.google.maps.event.CAMERA_CHANGE, checkMapIdle);

.
.
.

function checkMapIdle(){
    clearTimeout(searchBoundsTimer);
    searchBoundsTimer = setTimeout(function(){
            mapStopDragging();
    },500);//half a second or 1 second?
}

**Comment by denkomanceski** [comment]
celron i thought about that as well, but the problem is that the user can "drag and not move". 
Example: He started dragging and he got into the place that he wanted to be BUT he did not let his finger off the screen yet which means he can continue dragging. I guess this solution is good for now, thanks.

Also i saw that its hard to implement this in other issues, I run into this post, it seems useful

http://dimitar.me/how-to-detect-a-user-pantouchdrag-on-android-map-v2/

**Comment by celron** [comment]
I believe CAMERA_CHANGE is called even if the user does not lift their finger, some simple tests that I did shows that it seems to work as a crude IDLE state detector, which exists in the javascript libraries but not the native libraries, or are you stating that you want to detect the camera change only if the user lifts their finger?

**Comment by denkomanceski** [comment]
I mean: he can stop changing the camera and still have his finger on the touchscreen (which he stopped moving after he was dragging before). 

Its like: you swipe images left in some photo app and just before the image is gone, you stop swiping, and you stay like that but the image is still waiting because you are stiill basically dragging it even if you dont move

**Comment by denkomanceski** [comment]
We cannot be sure that he stopped interacting with the map just because he stopped moving the camera.. He might be "in the middle of something" and thats why he stopped. I can send a gif later of what i mean

**Comment by thelightbird** [comment]
After performing a few tests, I realized that the CAMERA_CHANGE event is fired on android when the map is idle, whereas on iOS, it's continuously fired while map dragging.
Is it the expected behavior ? If so a documentation update would be appreciated.
Is there a way to detect drag start on both platforms ?

**Comment by wf9a5m75** [comment]
@thelightbird Could you give me an example project?

**Comment by thelightbird** [comment]
I have modified the ionic blank starter to add the googlemaps plugin and to display when CAMERA_CHANGE event is fired. To test, you just have to add your own gmap API key and change bundle id.
[Ionic starter gmap camera_change event.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/184399/Ionic.starter.gmap.camera_change.event.zip)

**Comment by wf9a5m75** [comment]
Thank you. I will check your test project.

**Comment by wf9a5m75** [comment]
**Simple answer**
This is technically impossible except Google provides `drag` events from SDK (Android is possible).

**Detailed answer**
This is related thing that how Android and iOS process the `touch` events.

This plugin consists the blow layers.
All touch events are received by a touchable layer of this plugin at first (`MyPluginLayout` in Android, `MyPluginLayer` in iOS).
![68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f304231454366715443634c45385230683654336449645746424f484d2f6d656368616e69736d2e706e67](https://cloud.githubusercontent.com/assets/167831/13993165/6b6fbf06-f0dc-11e5-96ab-1fd9fa97e97a.png)

## Android case

If you touch any point on the screen (it means touch on the touchable layer), the `dispatchTouchEvent()` method is executed, then the `onInterceptTouchEvent ` method is executed.

The `onInterceptTouchEvent` method tells to the OS where this touch event should go?


In the `onInterceptTouchEvent` method, Android allows to inspect the touch event, so I can catch all  mouse events.
This flow works all touch(mouse) events.
The below is explain how to passes touch(mouse) events when you drag the map.
![android](https://cloud.githubusercontent.com/assets/167831/13994507/5e768e96-f0e2-11e5-83c0-70c8e7f5b060.png)

In this case, I can implement `touchstart`, `touchend`, `touchmove`, `touchcancel` and `touchleave` events. Thus, the drag events are also possible.

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/fcefff62b16a052b5fb94d3e9625ee565d8883c9#diff-dfacd3a00b9c3c948ea05afbde781710R348

## iOS Case

However iOS uses different flow, called `Responder Chain`.
When you touch on the screen (it means touch on the touchable layer), the `hitTest()` method is executed at first.

As well as `onInterceptTouchEvent()` in Android, the `hitTest()` method tells to the OS where this touch event should go?

But,  **`hitTest()` method is called only at once when you touch down on the screen at first.**


It means **the touchable layer (= this plugin) does not catch the mouse events after the `hitTest()`.**
![ios](https://cloud.githubusercontent.com/assets/167831/13995066/d6bbe516-f0e4-11e5-9b6e-761b339fc59a.png)

That's why I can **NOT** implement  `touchstart`, `touchend`, `touchmove`, `touchcancel` and `touchleave` events. Thus, the drag events are also impossible.

## Extra: If the touchableLayer catches all touch events, how about this?

Yes, I tired.
If the `hitTest()` method returns the touchableLayer itself, this plugin catches all touch events.
However there is no way to pass the event on the map or the browser.
![ios](https://cloud.githubusercontent.com/assets/167831/13995367/1e5c53aa-f0e6-11e5-8c29-225601b3a5ca.png)

## Conclusion

There is no way to implement `touchXXX` events, and `dragXXX` events also.

**Comment by wf9a5m75** [comment]
@thelightbird Regarding of the `CAMERA_CHANGE` events, it comes from the native maps. This plugin does not control anything. It is not a bug. It's just differences of Android and iOS.

**Comment by thelightbird** [comment]
@wf9a5m75 Thank you very much for a such detailed explanation.

**Comment by joneldiablo** [comment]
so what can I do if I need to know when user touch_up / mouse_up?

**Comment by wf9a5m75** [comment]
not possible with this plugin.

**Comment by simetin** [comment]
Would it be possible to use the CAMERA_CHANGE with a debounce function to "simulate" the drag end function ? If so, does anybody ever tried ?
