### ISSUE TITLE
Handle a big number of markers

### ISSUE THREAD

**Issue by alexislg2** [mapsplugin/cordova-plugin-googlemaps#854]
Hey,
I made an app that displays the local POI on the map. List of POIS (1 milllion) is handled by the server. The server only send the 50 nearest pois from the map center.

So each time the user change map center, the phone requests 50 nearest pois from the server and has to display them. To avoid doing `marker.remove()` and `new Marker(...)` I made a Marker pool of 50 elements and I change their location or visibility each time the list of pois to display changes.

This works perfectly well on Android. But on iOS when I want the user switches from a zone where there are no POI to a zone where there are 50 pois to display, the map is completely locked. We cannot click anywhere. ** This happens only with the iPhone 6 with iOS 9.2.1**

How are we supposed to do this kind of things?

**Comment by jaredgreener** [comment]
I am having the same issue. The map locks silently and cannot be moved. I think the issue is related to actually placing the markers and if I limit it to only placing a few at a time it seems to work. This only started happening with new devices on ios 9. It could possibly be a race condition due to asynchronous loading of pins (maybe newer devices process faster and introduce this bug).

**Comment by Hirbod** [comment]
Could you try my attemps from here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/790

Maybe this could fix your problems?

**Comment by Hirbod** [comment]
ah.. no.. wrong topic. I need to check the addMarker function

**Comment by puropen88** [comment]
We are making an app like alexislg2's and faced with the same problem on iPhone6+(9.2.1) and iPad 4th gen(9.2.1).
An old device(iPhone5(8.4.1)) works fine.

**Comment by puropen88** [comment]
I resolved my problem.
My app map has some toggle buttons which show or hide markers.

I tried to use "$scope.$watch" instead of the "addEventListener" method and then the problem is gone.

**Comment by alexislg2** [comment]
Hey,
why did you close the issue? My iOS app is still crashing :(

**Comment by jaredgreener** [comment]
I solved an issue where adding too many markers at once caused the app to completely freeze with no errors. I did this by adding a 10 milisecond delay between adding markers so that it wouldn't do so many at once. This seemed to fix the issue:

var markerQueue = [], markerDelay = 10;

function processMarkerQueue(){
	
	if(markerQueue.length <= 0){
		return false;
	}
	
	var currentMarker = markerQueue.shift(); // removes the first item from the array and returns
	
	try{
				
		nativeMap.addMarker({
				position: currentMarker.position,
				disableAutoPan: true,
				title: "title here",
				snippet: "snippet here"
			}, 
			function(marker) {				
				setTimeout(processMarkerQueue, markerDelay);
		    }
		);
		
	}catch(err){
		console.log("ERROR PLACING MARKER!!!");
		console.log(err);
		setTimeout(processMarkerQueue, markerDelay);
	}
	
}

function placeMarker(data){
	
	var initiateQueue = (markerQueue.length == 0 || !markerQueue); // if this is the first item in the list, we need to initiate the processing (after we add this item) because the queue isnt currently in process
	
	markerQueue.push({
		position: new plugin.google.maps.LatLng(data.get("lat"),data.get("lng")),
		disableAutoPan: true
		// etc...etc... etc..
	});
	  
	initiateQueue && setTimeout(processMarkerQueue, markerDelay); // This adds a slight delay between placing markers to help avoid app crashing	
}
