### ISSUE TITLE
Plugin to show any native view

### ISSUE THREAD

**Issue by vlaraort** [mapsplugin/cordova-plugin-googlemaps#897]
Hi!

Congratulations for this great plugin! Its awesome and have a really good job!

I have a problem. I have to develop a plugin, and I have to show a native view inside a div. This have nothing of google maps, but the idea its the same that hte one that you have.

I have based myself in your previous plugin
https://github.com/imhotep/MapKit/blob/master/src/android/MapKit.java

and I have make it work, cheers! but it shows the view overlapping all the html views, and it doesn't have the desired behaviour.

Now I am trying to understand this code, starting from android, but its difficult to me, as I am not a hardcore android programmer.

My question is if you have a simple code of the part of showing a native view inside a div.

Of course, I am going to donate to this great project, so you can take some beers ;)

Thanks!

**Comment by wf9a5m75** [comment]
I explain how execute the native methods from JS.

For example, when you execute `map.setMapTypeId()`, the JS code executes here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L456

It executes `Execute()` method of the GoogleMaps.java.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L219

However, there is no declared `Map.setMapTypeId`  method in GoogleMaps.java.
If the passed method contains `. (dot)`, then the code assumes that is declared in another class.
So the code gets `PluginMap` class, then execute the `setMapTypeId()` method using reflection technique.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginMap.java#L352

The most methods are executed this follow.

---

I know your `MapKit` project from old. Instead of donation, learn this plugin a lot, and contribute to this plugin please ;)
