### ISSUE TITLE
demo app not loading map when phone has no data connection: offline support available?

### ISSUE THREAD

**Issue by Plex768** [mapsplugin/cordova-plugin-googlemaps#903]
Is offline loading of google maps in android apps supported with the cordova-plugin-googlemaps plugin? When the demo app was trying to load the google maps it say the app is trying to turn on GPS.  I know you can load google maps in native android apps offline when the phone has no data connection. Looking forward to hearing back from you guys. thanks.

**Comment by wf9a5m75** [comment]
That is question for native Google Maps. Not related to this plugin.
The demo app (maybe 1.2.5.apk) requires to obtain the user location for demo of `map.getMyLocation()`.
But this plugin works if the device is offline.
Please ask questions at [the official community]( https://plus.google.com/u/0/communities/117427728522929652853), and report issues here (because issues list).
At the official community, many people notice your question.
