### ISSUE TITLE
Marker Icon Color Inconsistency across iOS and Android

### ISSUE THREAD

**Issue by jworm7** [mapsplugin/cordova-plugin-googlemaps#904]
There is a large amount of variability when it comes to setting icon colors. iOS renders colors appropriately but Android doesn't. 

A basic example is `icon = "rgba(0,0,0,1)"` 
iOS:
<img width="350" alt="ios" src="https://cloud.githubusercontent.com/assets/12396777/14051467/81a116ee-f299-11e5-938e-fc08a66f209e.png">

Android:
![screenshot_2016-03-25-14-57-45](https://cloud.githubusercontent.com/assets/12396777/14051533/23df1e9c-f29a-11e5-8aa8-31973ab8fb68.png)

Is there something that I'm doing wrong? Thank you

**Comment by wf9a5m75** [comment]
How about `rgb(0, 0, 0)`?
The alpha value is ignored.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#color-icon

**Comment by jworm7** [comment]
Unfortunately, that has the same affect: works on iOS and not on Android. Oddly when I use a hex (#6E244C), the color changes on both but the Android color is wildly off (is renders as a hot pink instead of a deep purple).

**Comment by wf9a5m75** [comment]
Ok, this is not a bug, but Google Maps Android API v2 does not accept the `black` color.
Because the api accepts the color of HUE, not RGB.
It means color the api does not accept "black", because **black is not hue, brightness**.
The same thing for `white`.

More detail, please read here.
http://stackoverflow.com/a/28503769/697856

In order to create black marker, you need to prepare your icon image.
