### ISSUE TITLE
using it with Admob plugin

### ISSUE THREAD

**Issue by AndroConsis** [mapsplugin/cordova-plugin-googlemaps#938]
Well it's not exactly issue, I'm building it with OnsenUI. When I used Admob plugin, map is disappearing.
As soon as banner is loaded map goes white. While map is still there in $rootScope. I think this is problem of background-color. I went through all the pages created by Admob plugin( chrome debugging) and set background-color to transparent but nothings helping. Any body has been through same issue. Is there any solution for this.

**Comment by wf9a5m75** [comment]
I'm not familiar with Admob and OnsenUI, but it seems like the Admob changes the background color.
For using this plugin, you MUST be set the background as transparent.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

Please inspect this issue, and tell me the solution.

**Comment by wf9a5m75** [comment]
Please reopen with new information. I don't check the compatibility with other plugins. Until then I close this issue.

**Comment by BeDave** [comment]
Hi, i'm running into the same issue. I have some more information about that.
I'm using cordova 4.0.0, cordova android 5.1.1, latest crosswalk version.

It happens when calling showBanner function of Admob plugin which is actually resizing the webview. This is not happening when setting the banner properties to overlap the webview neither when showing another view (as an interstitial ad) which is not resizing the webview.
This should mean something is happening to the map when the view is resized.

I also set the backgrond of all android activities to Theme.Translucent.NoTitleBar, but this is not removing the issue: what i'm facing to is a transparent view where it should be the map (i can see device home throght it) as soon as i call showBanner function. This meaning it should not be a problem of transparent background.

Are you able to reproduce a situation in which the webview is resized and see what's going on?

Let me know if i can provide other info which are useful to reproduce this.

**Comment by wasa4587** [comment]
It's weird i didn't see any changes on styles/css, background color stills being 0,0,0
i tried with admob overlap option, and it only works the first time,
what i did is load the map after the ad is displayed, it shows the ad bar on top and the map works.
