### ISSUE TITLE
Disable Scroll Gestures During Zoom

### ISSUE THREAD

**Issue by LouisMazel** [mapsplugin/cordova-plugin-googlemaps#940]
Hello,

I wish I could zoom in and out while keeping the center of the map, move the camera is impossible while zooming.
In the Native SDK that option: mapView.settings.allowScrollGesturesDuringRotateOrZoom = false | true
Do you know if that's possible here?

Thank you in advance for your answers

**Comment by wf9a5m75** [comment]
This plugin does not provide `allowScrollGesturesDuringRotateOrZoom` feature currently.

If you need, please implement it by yourself, and we appreciate if you send a pull request.

In iOS, it's easy. You can just pass the boolean value to allowScrollGesturesDuringRotateOrZoom.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/GoogleMapsViewController.m#L177-L200

In Android, it seems you can do with this:
http://stackoverflow.com/a/32734436/697856

into here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/GoogleMaps.java#L320

Since this is full open source code library, I hope many people contribute to this plugin.
