### ISSUE TITLE
Additional component parameters to be used when Geocoding

### ISSUE THREAD

**Issue by samuelgoldenbaum** [mapsplugin/cordova-plugin-googlemaps#947]
Looking at the source for geocoding, I don't see the ability add additional [component restrictions](https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering) to the request. I only see the address property being supplied. Is there a restriction in place to limit that? Thanks

**Comment by wf9a5m75** [comment]
Since the implements of the Android api and the iOS api are really different.
This plugin focus on providing the same functions for both OSs, so there are some missing functions.
I don't mind if you folk this plugin, and customize it by yourself, but at least I don't have any plan to implement these parameters at this time.

**Comment by samuelgoldenbaum** [comment]
Ok, pull get around to a pull
